import { FranchiseMedia } from "../types";

export const DCU_SEED_DATA: FranchiseMedia[] = [
  {
    "id": "dcu-1",
    "universe": "dcu",
    "title": "Man of Steel",
    "media_type": "movie",
    "release_order": 1,
    "chronological_order": 3,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 49521,
    "poster_path": "https://image.tmdb.org/t/p/w500/8GFtkImmK0K1VaUChR0n9O61CFU.jpg",
    "is_released": true,
    "release_date": "2013-06-12",
    "overview": "A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind."
  },
  {
    "id": "dcu-2",
    "universe": "dcu",
    "title": "Batman v Superman: Dawn of Justice",
    "media_type": "movie",
    "release_order": 2,
    "chronological_order": 4,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 209112,
    "poster_path": "https://image.tmdb.org/t/p/w500/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
    "is_released": true,
    "release_date": "2016-03-23",
    "overview": "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before."
  },
  {
    "id": "dcu-3",
    "universe": "dcu",
    "title": "Suicide Squad",
    "media_type": "movie",
    "release_order": 3,
    "chronological_order": 5,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 297761,
    "poster_path": "https://image.tmdb.org/t/p/w500/sk3FZgh3sRrmr8vyhaitNobMcfh.jpg",
    "is_released": true,
    "release_date": "2016-08-03",
    "overview": "From DC Comics comes the Suicide Squad, an antihero team of incarcerated supervillains who act as deniable assets for the United States government, undertaking high-risk black ops missions in exchange for commuted prison sentences."
  },
  {
    "id": "dcu-4",
    "universe": "dcu",
    "title": "Wonder Woman",
    "media_type": "movie",
    "release_order": 4,
    "chronological_order": 1,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 297762,
    "poster_path": "https://image.tmdb.org/t/p/w500/v4ncgZjG2Zu8ZW5al1vIZTsSjqX.jpg",
    "is_released": true,
    "release_date": "2017-05-30",
    "overview": "An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict."
  },
  {
    "id": "dcu-5",
    "universe": "dcu",
    "title": "Justice League",
    "media_type": "movie",
    "release_order": 5,
    "chronological_order": 6,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 141052,
    "poster_path": "https://image.tmdb.org/t/p/w500/eifGNCSDuxJeS1loAXil5bIGgvC.jpg",
    "is_released": true,
    "release_date": "2017-11-15",
    "overview": "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth."
  },
  {
    "id": "dcu-6",
    "universe": "dcu",
    "title": "Zack Snyder's Justice League",
    "media_type": "movie",
    "release_order": 6,
    "chronological_order": 7,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 791373,
    "poster_path": "https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
    "is_released": true,
    "release_date": "2021-03-18",
    "overview": "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions."
  },
  {
    "id": "dcu-7",
    "universe": "dcu",
    "title": "Aquaman",
    "media_type": "movie",
    "release_order": 7,
    "chronological_order": 8,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 297802,
    "poster_path": "https://image.tmdb.org/t/p/w500/ufl63EFcc5XpByEV2Ecdw6WJZAI.jpg",
    "is_released": true,
    "release_date": "2018-12-07",
    "overview": "Half-human, half-Atlantean Arthur Curry is taken on the journey of his lifetime to discover if he is worth of being a king."
  },
  {
    "id": "dcu-8",
    "universe": "dcu",
    "title": "Shazam!",
    "media_type": "movie",
    "release_order": 8,
    "chronological_order": 9,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 287947,
    "poster_path": "https://image.tmdb.org/t/p/w500/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
    "is_released": true,
    "release_date": "2019-03-29",
    "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word."
  },
  {
    "id": "dcu-9",
    "universe": "dcu",
    "title": "Birds of Prey",
    "media_type": "movie",
    "release_order": 9,
    "chronological_order": 10,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 495764,
    "poster_path": "https://image.tmdb.org/t/p/w500/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
    "is_released": true,
    "release_date": "2020-02-05",
    "overview": "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord."
  },
  {
    "id": "dcu-10",
    "universe": "dcu",
    "title": "Wonder Woman 1984",
    "media_type": "movie",
    "release_order": 10,
    "chronological_order": 2,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 464052,
    "poster_path": "https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
    "is_released": true,
    "release_date": "2020-12-16",
    "overview": "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy."
  },
  {
    "id": "dcu-11",
    "universe": "dcu",
    "title": "The Suicide Squad",
    "media_type": "movie",
    "release_order": 11,
    "chronological_order": 11,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 436969,
    "poster_path": "https://image.tmdb.org/t/p/w500/q61qEyssk2ku3okWICKArlAdhBn.jpg",
    "is_released": true,
    "release_date": "2021-07-28",
    "overview": "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese."
  },
  {
    "id": "dcu-12",
    "universe": "dcu",
    "title": "Peacemaker (Season 1)",
    "media_type": "show",
    "release_order": 12,
    "chronological_order": 12,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 110492,
    "poster_path": "https://image.tmdb.org/t/p/w500/eYzbGcYnOUlvj2fa76pTgIXogd7.jpg",
    "is_released": true,
    "release_date": "2022-01-13",
    "overview": "The continuing story of Peacemaker, a vainglorious superhero/supervillain who believes in peace at any cost — no matter how many people he has to kill. After a miraculous recovery from his duel with Bloodsport, Peacemaker soon discovers that his freedom comes at a price.",
    "seasons": 2,
    "episodes": 16
  },
  {
    "id": "dcu-13",
    "universe": "dcu",
    "title": "Black Adam",
    "media_type": "movie",
    "release_order": 13,
    "chronological_order": 13,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 436270,
    "poster_path": "https://image.tmdb.org/t/p/w500/rCtreCr4xiYEWDQTebybolIh6Xe.jpg",
    "is_released": true,
    "release_date": "2022-10-19",
    "overview": "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world."
  },
  {
    "id": "dcu-14",
    "universe": "dcu",
    "title": "Shazam! Fury of the Gods",
    "media_type": "movie",
    "release_order": 14,
    "chronological_order": 14,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 594767,
    "poster_path": "https://image.tmdb.org/t/p/w500/3GrRgt6CiLIUXUtoktcv1g2iwT5.jpg",
    "is_released": true,
    "release_date": "2023-03-15",
    "overview": "Billy Batson and his foster siblings, who transform into superheroes by saying \"Shazam!\", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world."
  },
  {
    "id": "dcu-15",
    "universe": "dcu",
    "title": "The Flash",
    "media_type": "movie",
    "release_order": 15,
    "chronological_order": 15,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 298618,
    "poster_path": "https://image.tmdb.org/t/p/w500/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
    "is_released": true,
    "release_date": "2023-06-13",
    "overview": "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?"
  },
  {
    "id": "dcu-16",
    "universe": "dcu",
    "title": "Blue Beetle",
    "media_type": "movie",
    "release_order": 16,
    "chronological_order": 16,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 565770,
    "poster_path": "https://image.tmdb.org/t/p/w500/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
    "is_released": true,
    "release_date": "2023-08-16",
    "overview": "Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab."
  },
  {
    "id": "dcu-17",
    "universe": "dcu",
    "title": "Aquaman and the Lost Kingdom",
    "media_type": "movie",
    "release_order": 17,
    "chronological_order": 17,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 572802,
    "poster_path": "https://image.tmdb.org/t/p/w500/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
    "is_released": true,
    "release_date": "2023-12-20",
    "overview": "Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Arthur (Aquaman) forges an alliance with his imprisoned brother. They must protect the kingdom."
  },
  {
    "id": "dcu-18",
    "universe": "dcu",
    "title": "Creature Commandos",
    "media_type": "show",
    "release_order": 18,
    "chronological_order": 18,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 220025,
    "poster_path": "https://image.tmdb.org/t/p/w500/dznyYm7FCyccwIhf1eekilG6jPq.jpg",
    "is_released": true,
    "release_date": "2023-02-08",
    "overview": "Creature Commandos",
    "seasons": 2,
    "episodes": 40
  },
  {
    "id": "dcu-19",
    "universe": "dcu",
    "title": "Superman (2025)",
    "media_type": "movie",
    "release_order": 19,
    "chronological_order": 19,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1064213,
    "poster_path": "https://image.tmdb.org/t/p/w500/cgXk2tNYhJZLXdBDO5DidAVzQ82.jpg",
    "is_released": false,
    "release_date": "2024-10-14",
    "overview": "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled."
  },
  {
    "id": "dcu-20",
    "universe": "dcu",
    "title": "Peacemaker (Season 2)",
    "media_type": "show",
    "release_order": 20,
    "chronological_order": 20,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 110492,
    "poster_path": "https://image.tmdb.org/t/p/w500/eYzbGcYnOUlvj2fa76pTgIXogd7.jpg",
    "is_released": false,
    "release_date": "2022-01-13",
    "overview": "The continuing story of Peacemaker, a vainglorious superhero/supervillain who believes in peace at any cost — no matter how many people he has to kill. After a miraculous recovery from his duel with Bloodsport, Peacemaker soon discovers that his freedom comes at a price.",
    "seasons": 2,
    "episodes": 16
  },
  {
    "id": "dcu-21",
    "universe": "dcu",
    "title": "Supergirl: Woman of Tomorrow",
    "media_type": "movie",
    "release_order": 21,
    "chronological_order": 21,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1084242,
    "poster_path": "https://image.tmdb.org/t/p/w500/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg",
    "is_released": false,
    "release_date": "2025-11-26",
    "overview": "After cracking the biggest case in Zootopia's history, rookie cops Judy Hopps and Nick Wilde find themselves on the twisting trail of a great mystery when Gary De'Snake arrives and turns the animal metropolis upside down. To crack the case, Judy and Nick must go undercover to unexpected new parts of town, where their growing partnership is tested like never before."
  },
  {
    "id": "dcu-22",
    "universe": "dcu",
    "title": "Lanterns",
    "media_type": "show",
    "release_order": 22,
    "chronological_order": 22,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 220026,
    "poster_path": "https://image.tmdb.org/t/p/w500/9yFBzd851dBTjhVpdV3cxJ4eah9.jpg",
    "is_released": false,
    "release_date": "2019-09-16",
    "overview": "Lanterns",
    "seasons": 1,
    "episodes": 32
  },
  {
    "id": "dcu-23",
    "universe": "dcu",
    "title": "Clayface",
    "media_type": "movie",
    "release_order": 23,
    "chronological_order": 23,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1400940,
    "poster_path": "https://image.tmdb.org/t/p/w500/5jCpQnWPikggmQZoDp1eAi6BI6w.jpg",
    "is_released": false,
    "release_date": "2026-10-21",
    "overview": "Follow the terrifying descent into hell of a promising Hollywood actor who has become a monster driven by revenge, exploring the loss of identity and humanity, the ravages of toxic love and the dark side of scientific ambition."
  },
  {
    "id": "dcu-24",
    "universe": "dcu",
    "title": "The Brave and the Bold",
    "media_type": "movie",
    "release_order": 24,
    "chronological_order": 24,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1081004,
    "poster_path": "https://image.tmdb.org/t/p/w500/yrp5UKKMcRfK68zT74tlDxdsrOI.jpg",
    "is_released": false,
    "release_date": "2027-01-01",
    "overview": "The story of Damian Wayne, who was raised as a little murderer and assassin, and Batman's son that he didn’t know existed for the first eight to ten years of his life."
  },
  {
    "id": "dcu-25",
    "universe": "dcu",
    "title": "Swamp Thing",
    "media_type": "movie",
    "release_order": 25,
    "chronological_order": 25,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1084244,
    "poster_path": "https://image.tmdb.org/t/p/w500/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
    "is_released": false,
    "release_date": "2026-06-17",
    "overview": "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime."
  },
  {
    "id": "dcu-26",
    "universe": "dcu",
    "title": "Booster Gold",
    "media_type": "show",
    "release_order": 26,
    "chronological_order": 26,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 220028,
    "poster_path": "https://image.tmdb.org/t/p/w500/j5j9SB7CErjPVP43q7zJsIQSNBt.jpg",
    "is_released": false,
    "release_date": "2018-01-25",
    "overview": "Booster Gold",
    "seasons": 1,
    "episodes": 26
  },
  {
    "id": "dcu-27",
    "universe": "dcu",
    "title": "Waller",
    "media_type": "show",
    "release_order": 27,
    "chronological_order": 27,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 220027,
    "poster_path": "https://image.tmdb.org/t/p/w500/7imkRYpmM7IVCLIiOZZARKLlkSL.jpg",
    "is_released": false,
    "release_date": "2018-10-21",
    "overview": "In the new SBS6 program Scammers on the internet, Kees van der Spek helps victims who have been scammed for large sums digitally. Kees travels at home and abroad to track down the internet scammers that cannot be found at that time. Will Kees succeed in finding out who is the online vendor who collects money but never delivers anything? And who is behind the counterfeit bank emails that many Dutch people receive?",
    "seasons": 1,
    "episodes": 4
  },
  {
    "id": "dcu-28",
    "universe": "dcu",
    "title": "Teen Titans",
    "media_type": "movie",
    "release_order": 28,
    "chronological_order": 28,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": null,
    "poster_path": "https://image.tmdb.org/t/p/w500/yNzj00TzH4gW3N6Q8T4P5n6Q4A7.jpg",
    "is_released": false,
    "release_date": "2028-01-01",
    "overview": "Live-action DCU adaptation focusing on the iconic team of young heroes led by Robin."
  },
  {
    "id": "dcu-29",
    "universe": "dcu",
    "title": "Blue Beetle (Animated)",
    "media_type": "show",
    "release_order": 29,
    "chronological_order": 29,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": null,
    "poster_path": "https://image.tmdb.org/t/p/w500/mXLOHHc1Zeuwsl4xYKjKh2280ne.jpg",
    "is_released": false,
    "release_date": "2028-01-01",
    "overview": "Animated DCU series continuing the adventures of Jaime Reyes and the Scarab.",
    "seasons": 1
  },
  {
    "id": "dcu-30",
    "universe": "dcu",
    "title": "Arrow",
    "media_type": "show",
    "release_order": 30,
    "chronological_order": 30,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 1412,
    "poster_path": "https://image.tmdb.org/t/p/w500/u8ZHFj1jC384JEkTt3vNg1DfWEb.jpg",
    "is_released": true,
    "release_date": "2012-10-10",
    "overview": "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.",
    "seasons": 8,
    "episodes": 170
  },
  {
    "id": "dcu-31",
    "universe": "dcu",
    "title": "The Flash (CW)",
    "media_type": "show",
    "release_order": 31,
    "chronological_order": 31,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/yZevl2vHQgmosfwUdVNzviIfaWS.jpg",
    "is_released": true,
    "release_date": "2014-10-07",
    "overview": "After being struck by lightning, CSI investigator Barry Allen awakens from a nine-month coma to discover he has been  granted the gift of super speed.  Teaming up with S.T.A.R. Labs, Barry takes on the persona of The Flash, the Fastest  Man Alive, to protect his city.",
    "seasons": 9,
    "episodes": 184
  },
  {
    "id": "dcu-32",
    "universe": "dcu",
    "title": "Vixen",
    "media_type": "show",
    "release_order": 32,
    "chronological_order": 32,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 64264,
    "poster_path": "https://image.tmdb.org/t/p/w500/7TMp3RMf9DCZaaR9XeAQ1N6tby4.jpg",
    "is_released": true,
    "release_date": "2015-09-12",
    "overview": "A live-action sitcom about two 12-year-old girls who start a multi-million-dollar gaming company and take on rap superstar Double G as a business partner.",
    "seasons": 3,
    "episodes": 63
  },
  {
    "id": "dcu-33",
    "universe": "dcu",
    "title": "Supergirl",
    "media_type": "show",
    "release_order": 33,
    "chronological_order": 33,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62688,
    "poster_path": "https://image.tmdb.org/t/p/w500/90mSQajf4STPROA6H7Hh8OvyWdK.jpg",
    "is_released": true,
    "release_date": "2015-10-26",
    "overview": "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
    "seasons": 6,
    "episodes": 126
  },
  {
    "id": "dcu-34",
    "universe": "dcu",
    "title": "DC's Legends of Tomorrow",
    "media_type": "show",
    "release_order": 34,
    "chronological_order": 34,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62643,
    "poster_path": "https://image.tmdb.org/t/p/w500/qNgAcg4gNYbZ9mySLB9ZX4ehZb6.jpg",
    "is_released": true,
    "release_date": "2016-01-21",
    "overview": "When heroes alone are not enough ... the world needs legends. Having seen the future, one he will desperately try to prevent from happening, time-traveling rogue Rip Hunter is tasked with assembling a disparate group of both heroes and villains to confront an unstoppable threat — one in which not only is the planet at stake, but all of time itself. Can this ragtag team defeat an immortal threat unlike anything they have ever known?",
    "seasons": 7,
    "episodes": 110
  },
  {
    "id": "dcu-35",
    "universe": "dcu",
    "title": "Freedom Fighters: The Ray",
    "media_type": "show",
    "release_order": 35,
    "chronological_order": 35,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 75219,
    "poster_path": "https://image.tmdb.org/t/p/w500/6njUqsd3By2mJsdZm1P0moPLzs3.jpg",
    "is_released": true,
    "release_date": "2018-01-03",
    "overview": "Explore the high-pressure experiences of police officers, paramedics and firefighters who are thrust into the most frightening, shocking and heart-stopping situations. These emergency responders must try to balance saving those who are at their most vulnerable with solving the problems in their own lives.",
    "seasons": 10,
    "episodes": 143
  },
  {
    "id": "dcu-36",
    "universe": "dcu",
    "title": "Black Lightning",
    "media_type": "show",
    "release_order": 36,
    "chronological_order": 36,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 71663,
    "poster_path": "https://image.tmdb.org/t/p/w500/h1xbvvO6oqchfLe6xh0yLNnQxeM.jpg",
    "is_released": true,
    "release_date": "2018-01-16",
    "overview": "Jefferson Pierce is a man wrestling with a secret. As the father of two daughters and principal of a charter high school that also serves as a safe haven for young people in a New Orleans neighborhood overrun by gang violence, he is a hero to his community.",
    "seasons": 4,
    "episodes": 58
  },
  {
    "id": "dcu-37",
    "universe": "dcu",
    "title": "Batwoman",
    "media_type": "show",
    "release_order": 37,
    "chronological_order": 37,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 89247,
    "poster_path": "https://image.tmdb.org/t/p/w500/pBpxKiitMuYXvtsXNSzya8DKKzV.jpg",
    "is_released": true,
    "release_date": "2019-10-06",
    "overview": "Kate Kane, armed with a passion for social justice and a flair for speaking her mind, soars onto the streets of Gotham as Batwoman, an out lesbian and highly trained street fighter primed to snuff out the failing city's criminal resurgence. But don't call her a hero yet. In a city desperate for a savior, Kate must overcome her own demons before embracing the call to be Gotham's symbol of hope",
    "seasons": 3,
    "episodes": 51
  },
  {
    "id": "dcu-38",
    "universe": "dcu",
    "title": "Batman: The Animated Series",
    "media_type": "show",
    "release_order": 38,
    "chronological_order": 38,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 2098,
    "poster_path": "https://image.tmdb.org/t/p/w500/lBomQFW1vlm1yUYMNSbFZ45R4Ox.jpg",
    "is_released": true,
    "release_date": "1992-09-05",
    "overview": "Vowing to avenge the murder of his parents, Bruce Wayne devotes his life to wiping out crime in Gotham City as the masked vigilante \"Batman\".",
    "seasons": 4,
    "episodes": 85
  },
  {
    "id": "dcu-39",
    "universe": "dcu",
    "title": "Batman: Mask of the Phantasm",
    "media_type": "movie",
    "release_order": 39,
    "chronological_order": 39,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 14919,
    "poster_path": "https://image.tmdb.org/t/p/w500/hT4ehUteagUrhUOHAtmYiY7mp5l.jpg",
    "is_released": true,
    "release_date": "1993-12-25",
    "overview": "Andrea Beaumont leaves her father to return to Gotham, rekindling an old romance with Bruce Wayne. At the same time, a mysterious figure begins to hunt down Gotham's criminals, wrongly implicating Batman in the murders. Now on the run from the law, Batman must find and stop the culprit, while also navigating his relationship with Andrea."
  },
  {
    "id": "dcu-40",
    "universe": "dcu",
    "title": "Superman: The Animated Series",
    "media_type": "show",
    "release_order": 40,
    "chronological_order": 40,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 987,
    "poster_path": "https://image.tmdb.org/t/p/w500/gS5iORCJHwP5moEXSF9b6ZcsZ1w.jpg",
    "is_released": true,
    "release_date": "1963-04-01",
    "overview": "Families, friends, enemies and lovers experience life-changing events in the large upstate New York city of Port Charles, which has a busy hospital, upscale hotel, cozy diner and dangerous waterfront frequented by the criminal underworld.",
    "seasons": 63,
    "episodes": 10827
  },
  {
    "id": "dcu-41",
    "universe": "dcu",
    "title": "The New Batman Adventures",
    "media_type": "show",
    "release_order": 41,
    "chronological_order": 41,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 46261,
    "poster_path": "https://image.tmdb.org/t/p/w500/h50lj7xO65qafNYZCrfQ7ztkMBD.jpg",
    "is_released": true,
    "release_date": "2009-10-12",
    "overview": "Lucy is a 17-year-old girl, who wants to be a full-fledged mage. One day when visiting Harujion Town, she meets Natsu, a young man who gets sick easily by any type of transportation. But Natsu isn't just any ordinary kid, he's a member of one of the world's most infamous mage guilds: Fairy Tail.",
    "seasons": 8,
    "episodes": 328
  },
  {
    "id": "dcu-42",
    "universe": "dcu",
    "title": "Batman & Mr. Freeze: SubZero",
    "media_type": "movie",
    "release_order": 42,
    "chronological_order": 42,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 15805,
    "poster_path": "https://image.tmdb.org/t/p/w500/kjjz8mVNrwNUa9uz8IMnqS79rxj.jpg",
    "is_released": true,
    "release_date": "1998-02-11",
    "overview": "When Mr. Freeze kidnaps Barbara Gordon, as an involuntary organ donor to save his dying wife, Batman and Robin must find her before the operation can begin."
  },
  {
    "id": "dcu-43",
    "universe": "dcu",
    "title": "Batman Beyond",
    "media_type": "show",
    "release_order": 43,
    "chronological_order": 43,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 513,
    "poster_path": "https://image.tmdb.org/t/p/w500/rpbHPyhLstNd5qgtjaDMdPtyPeQ.jpg",
    "is_released": true,
    "release_date": "1999-01-10",
    "overview": "As new villains overrun Gotham City of the future, the aging Bruce Wayne hangs up the cape of the once invincible Batman. But when troubled teenager Terry McGinnis stumbles upon the Dark Knight's secret, a new alliance is forged. And a triumphant new Batman is born.",
    "seasons": 3,
    "episodes": 52
  },
  {
    "id": "dcu-44",
    "universe": "dcu",
    "title": "Batman Beyond: Return of the Joker",
    "media_type": "movie",
    "release_order": 44,
    "chronological_order": 44,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 15370,
    "poster_path": "https://image.tmdb.org/t/p/w500/pqyY7IEWkCWNZ7EuRStQaJITEta.jpg",
    "is_released": true,
    "release_date": "2002-07-19",
    "overview": "Young Haru rescues a cat from being run over, but soon learns it's no ordinary feline; it happens to be the Prince of the Cats."
  },
  {
    "id": "dcu-45",
    "universe": "dcu",
    "title": "Static Shock",
    "media_type": "show",
    "release_order": 45,
    "chronological_order": 45,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 2269,
    "poster_path": "https://image.tmdb.org/t/p/w500/2byWyytcBRkEZiD34BhYhBOCOEl.jpg",
    "is_released": true,
    "release_date": "2003-03-23",
    "overview": "Hardware is a British sitcom that aired on ITV from 2003 to 2004. Starring Martin Freeman, it was written and created by Simon Nye, the creator of Men Behaving Badly.\n\nThe show's opening theme was A Taste of Honey by Herb Alpert's Tijuana Brass.",
    "seasons": 2,
    "episodes": 12
  },
  {
    "id": "dcu-46",
    "universe": "dcu",
    "title": "The Zeta Project",
    "media_type": "show",
    "release_order": 46,
    "chronological_order": 46,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 3241,
    "poster_path": "https://image.tmdb.org/t/p/w500/tS5X6AolvRL2Xw8A9aPoiTT99gN.jpg",
    "is_released": true,
    "release_date": "2006-07-10",
    "overview": "Minami is a 27-year-old female office worker in an advertisement agency. Though she has a boyfriend, she spends the majority of her time working and appears to feel ambivalent about the relationship at best. When the boyfriend finally breaks up with her, it's the push she needs to start a social life with her co-workers. In-office romances soon follow. Much of the story is told through Minami's thoughts, which are full of self-doubt.",
    "seasons": 1,
    "episodes": 11
  },
  {
    "id": "dcu-47",
    "universe": "dcu",
    "title": "Justice League (Animated)",
    "media_type": "show",
    "release_order": 47,
    "chronological_order": 47,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 1618,
    "poster_path": "https://image.tmdb.org/t/p/w500/caIAQIoM9NLZofT8fz8t47W1gYe.jpg",
    "is_released": true,
    "release_date": "2001-11-17",
    "overview": "The long-awaited rebirth of the greatest superhero team of all time: Batman, Superman, Wonder Woman, The Flash, Hawkgirl, Green Lantern, and Martian Manhunter.",
    "seasons": 2,
    "episodes": 50
  },
  {
    "id": "dcu-48",
    "universe": "dcu",
    "title": "Batman: Mystery of the Batwoman",
    "media_type": "movie",
    "release_order": 48,
    "chronological_order": 48,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 20533,
    "poster_path": "https://image.tmdb.org/t/p/w500/xwAdu0lOO2Y5sXjK87glhJg3c6r.jpg",
    "is_released": true,
    "release_date": "2010-06-18",
    "overview": "Gunslinger Jonah Hex is appointed by President Ulysses Grant to track down terrorist Quentin Turnbull, a former Confederate officer determined on unleashing hell on earth. Jonah not only secures freedom by accepting this task, he also gets revenge on the man who slew his wife and child."
  },
  {
    "id": "dcu-49",
    "universe": "dcu",
    "title": "Justice League Unlimited",
    "media_type": "show",
    "release_order": 49,
    "chronological_order": 49,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 2026,
    "poster_path": "https://image.tmdb.org/t/p/w500/5Znl8HNStdoHHy0hqdljpDZnVRn.jpg",
    "is_released": true,
    "release_date": "1999-09-19",
    "overview": "Judging Amy is an American television drama that was telecast from September 19, 1999, through May 3, 2005, on CBS-TV. This TV series starred Amy Brenneman and Tyne Daly. Its main character is a judge who serves in a family court, and in addition to the family-related cases that she adjudicates, many episodes of the show focus on her own experiences as a divorced mother, and on the experiences of her mother, a social worker who works in the field of child welfare. This series was based on the life experiences of Brenneman's mother.",
    "seasons": 6,
    "episodes": 138
  },
  {
    "id": "dcu-50",
    "universe": "dcu",
    "title": "Batman and Harley Quinn",
    "media_type": "movie",
    "release_order": 50,
    "chronological_order": 50,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 408648,
    "poster_path": "https://image.tmdb.org/t/p/w500/v3RP6pp6pfRdvch6QioeQvNdMJs.jpg",
    "is_released": true,
    "release_date": "2017-07-21",
    "overview": "Batman and Nightwing are forced to team with the Joker's sometimes-girlfriend Harley Quinn to stop a global threat brought about by Poison Ivy and Jason Woodrue, the Floronic Man."
  },
  {
    "id": "dcu-51",
    "universe": "dcu",
    "title": "Justice League vs. the Fatal Five",
    "media_type": "movie",
    "release_order": 51,
    "chronological_order": 51,
    "phase_or_chapter": "DCAU (Timmverse)",
    "tmdb_id": 567604,
    "poster_path": "https://image.tmdb.org/t/p/w500/w6Jk8BHohhoKBUcxGeSyDQGWGWc.jpg",
    "is_released": true,
    "release_date": "2018-12-11",
    "overview": "A kidnapped Fred Savage is forced to endure Deadpool's PG-13 rendition of Deadpool 2, as a Princess Bride-esque story full of magic, wonder, and zero Fs."
  },
  {
    "id": "dcu-52",
    "universe": "dcu",
    "title": "Justice League: The Flashpoint Paradox",
    "media_type": "movie",
    "release_order": 52,
    "chronological_order": 52,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 142061,
    "poster_path": "https://image.tmdb.org/t/p/w500/d1TqoVkyL4x0dlu9w3F9Ah4LjNv.jpg",
    "is_released": true,
    "release_date": "2013-01-03",
    "overview": "Batman has stopped the reign of terror that The Mutants had cast upon his city.  Now an old foe wants a reunion and the government wants The Man of Steel to put a stop to Batman."
  },
  {
    "id": "dcu-53",
    "universe": "dcu",
    "title": "Justice League: War",
    "media_type": "movie",
    "release_order": 53,
    "chronological_order": 53,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 216803,
    "poster_path": "https://image.tmdb.org/t/p/w500/mmi4oP8HZTznwuLtODyb6Uu2bKF.jpg",
    "is_released": true,
    "release_date": "1959-04-28",
    "overview": "Five longtime friends get back together, but are disappointed to find that their bonds are not as strong as they once were."
  },
  {
    "id": "dcu-54",
    "universe": "dcu",
    "title": "Son of Batman",
    "media_type": "movie",
    "release_order": 54,
    "chronological_order": 54,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 251519,
    "poster_path": "https://image.tmdb.org/t/p/w500/yHx8OLSKc3VtIBB5lIe90c0fHOX.jpg",
    "is_released": true,
    "release_date": "2014-05-13",
    "overview": "Batman learns he has a violent, unruly pre-teen son, secretly raised by the terrorist group known as The League of Assassins."
  },
  {
    "id": "dcu-55",
    "universe": "dcu",
    "title": "Justice League: Throne of Atlantis",
    "media_type": "movie",
    "release_order": 55,
    "chronological_order": 55,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 287590,
    "poster_path": "https://image.tmdb.org/t/p/w500/gxKfP9278RK4t3J8vLXoFfB8ihl.jpg",
    "is_released": true,
    "release_date": "2014-06-21",
    "overview": "Mitsumasa Kido discovers a misterious baby in the himalayas whom he adopts as his grandaughter. 16 years later, Saori Kido is a young girl troubled by her mysterious powers. She is saved by Seiya from an assassin sent to kill her. Saori then learns she is the reincarnation of the Goddess Athena with Seiya being one of her Saints sworn to protect her. Upon learning of her destiny, she heads to the Sanctuary to rebel against the Pope's murderous plot."
  },
  {
    "id": "dcu-56",
    "universe": "dcu",
    "title": "Batman vs. Robin",
    "media_type": "movie",
    "release_order": 56,
    "chronological_order": 56,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 321528,
    "poster_path": "https://image.tmdb.org/t/p/w500/aGp9XDXmVM5lCKHWtgBC15S7XLr.jpg",
    "is_released": true,
    "release_date": "2015-04-03",
    "overview": "Damian Wayne is having a hard time coping with his father's \"no killing\" rule. Meanwhile, Gotham is going through hell with threats such as the insane Dollmaker, and the secretive Court of Owls."
  },
  {
    "id": "dcu-57",
    "universe": "dcu",
    "title": "Batman: Bad Blood",
    "media_type": "movie",
    "release_order": 57,
    "chronological_order": 57,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 366924,
    "poster_path": "https://image.tmdb.org/t/p/w500/ktjbGsGm5GKlHDvvwQajXvDW2BN.jpg",
    "is_released": true,
    "release_date": "2016-01-19",
    "overview": "When Batman goes missing, it takes the entire Bat \"family\" - including Batwoman and Batwing - to keep the peace in Gotham and unravel the mystery behind the Dark Knight's disappearance."
  },
  {
    "id": "dcu-58",
    "universe": "dcu",
    "title": "Justice League vs. Teen Titans",
    "media_type": "movie",
    "release_order": 58,
    "chronological_order": 58,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 377264,
    "poster_path": "https://image.tmdb.org/t/p/w500/iqEFG5ldyeLIFPp7mMI7ZmS7Upm.jpg",
    "is_released": true,
    "release_date": "2016-09-01",
    "overview": "A corporate risk-management consultant must determine whether or not to terminate an artificial being's life that was made in a laboratory environment."
  },
  {
    "id": "dcu-59",
    "universe": "dcu",
    "title": "Justice League Dark",
    "media_type": "movie",
    "release_order": 59,
    "chronological_order": 59,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 408220,
    "poster_path": "https://image.tmdb.org/t/p/w500/gWcTaDFXDrOAPfVzfBFz0Aya5BE.jpg",
    "is_released": true,
    "release_date": "2017-01-24",
    "overview": "When innocent civilians begin committing unthinkable crimes across Metropolis, Gotham City and beyond, Batman must call upon mystical counterparts to eradicate this demonic threat to the planet; enter Justice League Dark. This team of Dark Arts specialists must unravel the mystery of Earth's supernatural plague and contend with the rising, powerful villainous forces behind the siege—before it's too late for all of mankind."
  },
  {
    "id": "dcu-60",
    "universe": "dcu",
    "title": "Teen Titans: The Judas Contract",
    "media_type": "movie",
    "release_order": 60,
    "chronological_order": 60,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 408647,
    "poster_path": "https://image.tmdb.org/t/p/w500/nuGIlNAJUati4qEAH1nrYKUA3xa.jpg",
    "is_released": true,
    "release_date": "2017-04-04",
    "overview": "Tara Markov is a girl who has power over earth and stone; she is also more than she seems. Is the newest Teen Titan an ally or a threat? And what are the mercenary Deathstroke's plans for the Titans?"
  },
  {
    "id": "dcu-61",
    "universe": "dcu",
    "title": "Suicide Squad: Hell to Pay",
    "media_type": "movie",
    "release_order": 61,
    "chronological_order": 61,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 493529,
    "poster_path": "https://image.tmdb.org/t/p/w500/v7UF7ypAqjsFZFdjksjQ7IUpXdn.jpg",
    "is_released": true,
    "release_date": "2023-03-23",
    "overview": "A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people."
  },
  {
    "id": "dcu-62",
    "universe": "dcu",
    "title": "The Death of Superman",
    "media_type": "movie",
    "release_order": 62,
    "chronological_order": 62,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 505262,
    "poster_path": "https://image.tmdb.org/t/p/w500/hC4nTxdhXqFWzgqynGvvXVMiMNp.jpg",
    "is_released": true,
    "release_date": "2018-08-03",
    "overview": "All Might and Deku accept an invitation to go abroad to a floating and mobile manmade city, called 'I-Island', where they research quirks as well as hero supplemental items at the special 'I-Expo' convention that is currently being held on the island. During that time, suddenly, despite an iron wall of security surrounding the island, the system is breached by a villain, and the only ones able to stop him are the students of Class 1-A."
  },
  {
    "id": "dcu-63",
    "universe": "dcu",
    "title": "Constantine: City of Demons",
    "media_type": "movie",
    "release_order": 63,
    "chronological_order": 63,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 541134,
    "poster_path": "https://image.tmdb.org/t/p/w500/rSq6cq0LCcbro10jbEaPTEb3WmW.jpg",
    "is_released": true,
    "release_date": "2022-10-19",
    "overview": "Suspicious that her colleague is responsible for a series of mysterious patient deaths, a nurse risks her own life to uncover the truth."
  },
  {
    "id": "dcu-64",
    "universe": "dcu",
    "title": "Reign of the Supermen",
    "media_type": "movie",
    "release_order": 64,
    "chronological_order": 64,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 537056,
    "poster_path": "https://image.tmdb.org/t/p/w500/eiVQORVyVuNNZHPAELuWtlXoQsD.jpg",
    "is_released": true,
    "release_date": "2019-07-19",
    "overview": "A mysterious new villain known only as Hush uses a gallery of villains to destroy Batman's crime-fighting career as well as Bruce Wayne's personal life, which has been further complicated by a relationship with Selina Kyle/Catwoman."
  },
  {
    "id": "dcu-65",
    "universe": "dcu",
    "title": "Batman: Hush",
    "media_type": "movie",
    "release_order": 65,
    "chronological_order": 65,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 537055,
    "poster_path": "https://image.tmdb.org/t/p/w500/w1SBqj0fn1j72ST5i1jauWo3swT.jpg",
    "is_released": true,
    "release_date": "2019-10-04",
    "overview": "Witness the legendary origin of renowned Justice League member Wonder Woman as she fights for good with her sword and magic lasso. Equally strong in body, heart and will, she makes it her mission to help a troubled young girl enlisted by a deadly organization known as Villainy, Inc., whose criminal members have their sights set on invading Themyscira, Wonder Woman’s paradise home. The battle will be epic, because if there's one thing an Amazon knows, it’s war!"
  },
  {
    "id": "dcu-66",
    "universe": "dcu",
    "title": "Wonder Woman: Bloodlines",
    "media_type": "movie",
    "release_order": 66,
    "chronological_order": 66,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 537059,
    "poster_path": "https://image.tmdb.org/t/p/w500/xXC0HrmyQDXlYTiHP7Tq6nzurDI.jpg",
    "is_released": true,
    "release_date": "2019-03-29",
    "overview": "The Justice League faces a powerful new threat — the Fatal Five! Superman, Batman and Wonder Woman seek answers as the time-traveling trio of Mano, Persuader and Tharok terrorize Metropolis in search of budding Green Lantern, Jessica Cruz. With her unwilling help, they aim to free remaining Fatal Five members Emerald Empress and Validus to carry out their sinister plan. But the Justice League has also discovered an ally from another time in the peculiar Star Boy — brimming with volatile power, could he be the key to thwarting the Fatal Five? An epic battle against ultimate evil awaits!"
  },
  {
    "id": "dcu-67",
    "universe": "dcu",
    "title": "Justice League Dark: Apokolips War",
    "media_type": "movie",
    "release_order": 67,
    "chronological_order": 67,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 618353,
    "poster_path": "https://image.tmdb.org/t/p/w500/k8Q9ulyRE8fkvZMkAM9LPYMKctb.jpg",
    "is_released": true,
    "release_date": "2020-10-13",
    "overview": "Tragedy strikes the Batman's life again when Robin Jason Todd tracks down his birth mother only to run afoul of the Joker. An adaptation of the 1988 comic book storyline of the same name."
  },
  {
    "id": "dcu-68",
    "universe": "dcu",
    "title": "Constantine: The House of Mystery",
    "media_type": "special",
    "release_order": 68,
    "chronological_order": 68,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 951470,
    "poster_path": "https://image.tmdb.org/t/p/w500/5HruMN0vvl84AqD7sCDXFNO4RhP.jpg",
    "is_released": true,
    "release_date": "2022-04-27",
    "overview": "After a failed sabotage mission, a trio of anti-apartheid freedom fighters ends up in a tense bank hostage situation. Based on a true story."
  },
  {
    "id": "dcu-69",
    "universe": "dcu",
    "title": "Superman: Man of Tomorrow",
    "media_type": "movie",
    "release_order": 69,
    "chronological_order": 69,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 671583,
    "poster_path": "https://image.tmdb.org/t/p/w500/r2MfnMmFzGvRvjGVLIuyx3R16a6.jpg",
    "is_released": true,
    "release_date": "2020-07-31",
    "overview": "Nory and her best friend Reina enter the Sage Academy for Magical Studies, where Nory’s unconventional powers land her in a class for those with wonky, or “upside-down,” magic. Undaunted, Nory sets out to prove that that upside-down magic can be just as powerful as right-side-up."
  },
  {
    "id": "dcu-70",
    "universe": "dcu",
    "title": "Justice Society: World War II",
    "media_type": "movie",
    "release_order": 70,
    "chronological_order": 70,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 736069,
    "poster_path": "https://image.tmdb.org/t/p/w500/tOUJvmdjppmPYZOoykWmerSspMT.jpg",
    "is_released": true,
    "release_date": "2021-04-27",
    "overview": "When the Flash finds himself dropped into the middle of World War II, he joins forces with Wonder Woman and her top-secret team known as the Justice Society of America."
  },
  {
    "id": "dcu-71",
    "universe": "dcu",
    "title": "Batman: The Long Halloween - Part One",
    "media_type": "movie",
    "release_order": 71,
    "chronological_order": 71,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 736073,
    "poster_path": "https://image.tmdb.org/t/p/w500/sR7gppb0YGjwLvE6Vnj6wYv5MnW.jpg",
    "is_released": true,
    "release_date": "2021-06-21",
    "overview": "Following a brutal series of murders taking place on Halloween, Thanksgiving, and Christmas, Gotham City's young vigilante known as the Batman sets out to pursue the mysterious serial killer alongside police officer James Gordon and district attorney Harvey Dent."
  },
  {
    "id": "dcu-72",
    "universe": "dcu",
    "title": "Batman: The Long Halloween - Part Two",
    "media_type": "movie",
    "release_order": 72,
    "chronological_order": 72,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 736074,
    "poster_path": "https://image.tmdb.org/t/p/w500/5X1n5q08mZ7NpNpxehMFODxfNYq.jpg",
    "is_released": true,
    "release_date": "2021-07-26",
    "overview": "As Gotham City's young vigilante, the Batman, struggles to pursue a brutal serial killer, district attorney Harvey Dent gets caught in a feud involving the criminal family of the Falcones."
  },
  {
    "id": "dcu-73",
    "universe": "dcu",
    "title": "Green Lantern: Beware My Power",
    "media_type": "movie",
    "release_order": 73,
    "chronological_order": 73,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 885110,
    "poster_path": "https://image.tmdb.org/t/p/w500/hMIQiwLpBfTfe3ZbRlNx4225Mgg.jpg",
    "is_released": true,
    "release_date": "2021-11-04",
    "overview": "In 16th-century Zazzau, now Zaria, Nigeria, Amina must utilize her military skills and tactics to defend her family's kingdom. Based on a true story."
  },
  {
    "id": "dcu-74",
    "universe": "dcu",
    "title": "Legion of Super-Heroes",
    "media_type": "movie",
    "release_order": 74,
    "chronological_order": 74,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1003580,
    "poster_path": "https://image.tmdb.org/t/p/w500/3whQLi8RI7h2h2Si2KTDFJxfEcR.jpg",
    "is_released": true,
    "release_date": "2023-02-07",
    "overview": "Kara, devastated by the loss of Krypton, struggles to adjust to her new life on Earth. Her cousin, Superman, mentors her and suggests she leave their space-time to attend the Legion Academy in the 31st century, where she makes new friends and a new enemy: Brainiac 5. Meanwhile, she must contend with a mysterious group called the Dark Circle as it searches for a powerful weapon held in the Academy’s vault."
  },
  {
    "id": "dcu-75",
    "universe": "dcu",
    "title": "Justice League: Warworld",
    "media_type": "movie",
    "release_order": 75,
    "chronological_order": 75,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1003581,
    "poster_path": "https://image.tmdb.org/t/p/w500/pHdSS5G3wDwJp6jWgMpbSjNiTbr.jpg",
    "is_released": true,
    "release_date": "2023-07-25",
    "overview": "Until now, the Justice League has been a loose association of superpowered individuals. But when they are swept away to Warworld, a place of unending brutal gladiatorial combat, Batman, Superman, Wonder Woman and the others must somehow unite to form an unbeatable resistance able to lead an entire planet to freedom."
  },
  {
    "id": "dcu-76",
    "universe": "dcu",
    "title": "Justice League: Crisis on Infinite Earths Part One",
    "media_type": "movie",
    "release_order": 76,
    "chronological_order": 76,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1155089,
    "poster_path": "https://image.tmdb.org/t/p/w500/mcRVsjMbhFstRK9z2oGRHiIvulr.jpg",
    "is_released": true,
    "release_date": "2024-01-08",
    "overview": "Death is coming. Worse than death: oblivion. Not just for our Earth, but for everyone, everywhere, in every universe! Against this ultimate destruction, the mysterious Monitor has gathered the greatest team of Super Heroes ever assembled. But what can the combined might of Superman, Wonder Woman, Batman, The Flash, Green Lantern and hundreds of Super Heroes from multiple Earths even do to save all of reality from an unstoppable antimatter armageddon?!"
  },
  {
    "id": "dcu-77",
    "universe": "dcu",
    "title": "Justice League: Crisis on Infinite Earths Part Two",
    "media_type": "movie",
    "release_order": 77,
    "chronological_order": 77,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1209288,
    "poster_path": "https://image.tmdb.org/t/p/w500/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg",
    "is_released": true,
    "release_date": "2024-04-22",
    "overview": "An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?"
  },
  {
    "id": "dcu-78",
    "universe": "dcu",
    "title": "Justice League: Crisis on Infinite Earths Part Three",
    "media_type": "movie",
    "release_order": 78,
    "chronological_order": 78,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1209290,
    "poster_path": "https://image.tmdb.org/t/p/w500/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg",
    "is_released": true,
    "release_date": "2024-07-15",
    "overview": "Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?"
  },
  {
    "id": "dcu-79",
    "universe": "dcu",
    "title": "The Batman",
    "media_type": "movie",
    "release_order": 79,
    "chronological_order": 79,
    "phase_or_chapter": "The Reevesverse",
    "tmdb_id": 414906,
    "poster_path": "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    "is_released": true,
    "release_date": "2022-03-01",
    "overview": "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler."
  },
  {
    "id": "dcu-80",
    "universe": "dcu",
    "title": "The Penguin",
    "media_type": "show",
    "release_order": 80,
    "chronological_order": 80,
    "phase_or_chapter": "The Reevesverse",
    "tmdb_id": 137437,
    "poster_path": "https://image.tmdb.org/t/p/w500/9VW8wF6KpG01fMY4erZ9bw7A4Er.jpg",
    "is_released": true,
    "release_date": "2022-12-14",
    "overview": "While searching for history's greatest treasure, Jess Valenzuela unburies her family's secret past.",
    "seasons": 1,
    "episodes": 10
  },
  {
    "id": "dcu-81",
    "universe": "dcu",
    "title": "The Batman Part II",
    "media_type": "movie",
    "release_order": 81,
    "chronological_order": 81,
    "phase_or_chapter": "The Reevesverse",
    "tmdb_id": 974950,
    "poster_path": "https://image.tmdb.org/t/p/w500/7seqaCaaXDNUHOx4DqwpoOH8pPa.jpg",
    "is_released": false,
    "release_date": "2024-08-21",
    "overview": "Rita, an underrated lawyer working for a large law firm more interested in getting criminals out of jail than bringing them to justice, is hired by the leader of a criminal organization."
  },
  {
    "id": "dcu-82",
    "universe": "dcu",
    "title": "Joker",
    "media_type": "movie",
    "release_order": 82,
    "chronological_order": 82,
    "phase_or_chapter": "The Joker Duology",
    "tmdb_id": 475557,
    "poster_path": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    "is_released": true,
    "release_date": "2019-10-01",
    "overview": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure."
  },
  {
    "id": "dcu-83",
    "universe": "dcu",
    "title": "Joker: Folie à Deux",
    "media_type": "movie",
    "release_order": 83,
    "chronological_order": 83,
    "phase_or_chapter": "The Joker Duology",
    "tmdb_id": 889737,
    "poster_path": "https://image.tmdb.org/t/p/w500/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg",
    "is_released": true,
    "release_date": "2024-10-01",
    "overview": "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him."
  },
  {
    "id": "dcu-84",
    "universe": "dcu",
    "title": "Batman Begins",
    "media_type": "movie",
    "release_order": 84,
    "chronological_order": 84,
    "phase_or_chapter": "The Dark Knight Trilogy",
    "tmdb_id": 272,
    "poster_path": "https://image.tmdb.org/t/p/w500/sPX89Td70IDDjVr85jdSBb4rWGr.jpg",
    "is_released": true,
    "release_date": "2005-06-10",
    "overview": "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman."
  },
  {
    "id": "dcu-85",
    "universe": "dcu",
    "title": "The Dark Knight",
    "media_type": "movie",
    "release_order": 85,
    "chronological_order": 85,
    "phase_or_chapter": "The Dark Knight Trilogy",
    "tmdb_id": 155,
    "poster_path": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "is_released": true,
    "release_date": "2008-07-16",
    "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker."
  },
  {
    "id": "dcu-86",
    "universe": "dcu",
    "title": "The Dark Knight Rises",
    "media_type": "movie",
    "release_order": 86,
    "chronological_order": 86,
    "phase_or_chapter": "The Dark Knight Trilogy",
    "tmdb_id": 49026,
    "poster_path": "https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
    "is_released": true,
    "release_date": "2012-07-17",
    "overview": "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy."
  },
  {
    "id": "dcu-87",
    "universe": "dcu",
    "title": "Batman (1989)",
    "media_type": "movie",
    "release_order": 87,
    "chronological_order": 87,
    "phase_or_chapter": "Burton / Schumacher (Earth-89)",
    "tmdb_id": 268,
    "poster_path": "https://image.tmdb.org/t/p/w500/cij4dd21v2Rk2YtUQbV5kW69WB2.jpg",
    "is_released": true,
    "release_date": "1989-06-21",
    "overview": "Having witnessed his parents' brutal murder as a child, millionaire philanthropist Bruce Wayne fights crime in Gotham City disguised as Batman, a costumed hero who strikes fear into the hearts of villains. But when a deformed madman known as 'The Joker' seizes control of Gotham's criminal underworld, Batman must face his most ruthless nemesis ever while protecting both his identity and his love interest, reporter Vicki Vale."
  },
  {
    "id": "dcu-88",
    "universe": "dcu",
    "title": "Batman Returns",
    "media_type": "movie",
    "release_order": 88,
    "chronological_order": 88,
    "phase_or_chapter": "Burton / Schumacher (Earth-89)",
    "tmdb_id": 364,
    "poster_path": "https://image.tmdb.org/t/p/w500/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg",
    "is_released": true,
    "release_date": "1992-06-19",
    "overview": "The monstrous Penguin, who dwells in the sewers beneath Gotham, joins up with corrupt mayoral candidate Max Shreck to topple the Batman once and for all. But when Shreck's timid assistant Selina Kyle finds out, and Shreck tries to kill her, she's transformed into the sexy Catwoman. She teams up with the Penguin and Shreck to destroy Batman, but sparks fly unexpectedly when she confronts the caped crusader."
  },
  {
    "id": "dcu-89",
    "universe": "dcu",
    "title": "Batman Forever",
    "media_type": "movie",
    "release_order": 89,
    "chronological_order": 89,
    "phase_or_chapter": "Burton / Schumacher (Earth-89)",
    "tmdb_id": 414,
    "poster_path": "https://image.tmdb.org/t/p/w500/i0fJS8M5UKoETjjJ0zwUiKaR8tr.jpg",
    "is_released": true,
    "release_date": "1995-06-16",
    "overview": "Batman faces off against two foes: the schizophrenic, horribly scarred former District Attorney Harvey Dent, aka Two-Face, and the Riddler, a disgruntled ex-Wayne Enterprises inventor seeking revenge against his former employer by unleashing his brain-sucking weapon on Gotham City's residents. As the caped crusader also copes with tortured memories of his parents' murder, he has a new romance, with psychologist Chase Meridian."
  },
  {
    "id": "dcu-90",
    "universe": "dcu",
    "title": "Batman & Robin",
    "media_type": "movie",
    "release_order": 90,
    "chronological_order": 90,
    "phase_or_chapter": "Burton / Schumacher (Earth-89)",
    "tmdb_id": 415,
    "poster_path": "https://image.tmdb.org/t/p/w500/i7hEUpDuMN2LOrCEifFyGSHZQSY.jpg",
    "is_released": true,
    "release_date": "1997-06-20",
    "overview": "Batman and his sidekick Robin attempt to the foil the sinister schemes of a deranged set of new villains, most notably the melancholy Mr. Freeze, who wants to make Gotham City into an arctic region, and the sultry Poison Ivy, a botanical femme fatale. As the Dynamic Duo contend with these bad guys, a third hero, Batgirl, joins the ranks of the city's crime-fighters."
  },
  {
    "id": "dcu-91",
    "universe": "dcu",
    "title": "Superman (1978)",
    "media_type": "movie",
    "release_order": 91,
    "chronological_order": 91,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 1924,
    "poster_path": "https://image.tmdb.org/t/p/w500/d7px1FQxW4tngdACVRsCSaZq0Xl.jpg",
    "is_released": true,
    "release_date": "1978-12-14",
    "overview": "Mild-mannered Clark Kent works as a reporter at the Daily Planet alongside his crush, Lois Lane. Clark must summon his superhero alter-ego when the nefarious Lex Luthor launches a plan to take over the world."
  },
  {
    "id": "dcu-92",
    "universe": "dcu",
    "title": "Superman II",
    "media_type": "movie",
    "release_order": 92,
    "chronological_order": 92,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 8536,
    "poster_path": "https://image.tmdb.org/t/p/w500/3xk5cno9BHcnwc97XO9k21aI1Zi.jpg",
    "is_released": true,
    "release_date": "1980-12-04",
    "overview": "Three Kryptonian criminals led by General Zod team up with Lex Luthor to conquer Earth, forcing a depowered Superman to regain his strength and stop them."
  },
  {
    "id": "dcu-93",
    "universe": "dcu",
    "title": "Superman III",
    "media_type": "movie",
    "release_order": 93,
    "chronological_order": 93,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 9531,
    "poster_path": "https://image.tmdb.org/t/p/w500/c4oR6qgZW2s5foGkQi2Dd86KuAS.jpg",
    "is_released": true,
    "release_date": "1983-06-17",
    "overview": "Aiming to defeat the Man of Steel, wealthy executive Ross Webster hires bumbling but brilliant Gus Gorman to develop synthetic kryptonite, which yields some unexpected psychological effects. Between rekindling romance with his high school sweetheart and saving himself, Superman must contend with a powerful supercomputer."
  },
  {
    "id": "dcu-94",
    "universe": "dcu",
    "title": "Supergirl (1984)",
    "media_type": "movie",
    "release_order": 94,
    "chronological_order": 94,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 9655,
    "poster_path": "https://image.tmdb.org/t/p/w500/xRElqFcUVuGf0s2rAQSSNAn1IS9.jpg",
    "is_released": true,
    "release_date": "2006-03-17",
    "overview": "Viola Hastings is in a real jam. Complications threaten her scheme to pose as her twin brother, Sebastian, and take his place at a new boarding school. She falls in love with her handsome roommate, Duke, who loves beautiful Olivia, who has fallen for Sebastian! As if that were not enough, Viola's twin returns from London ahead of schedule but has no idea that his sister has already replaced him on campus."
  },
  {
    "id": "dcu-95",
    "universe": "dcu",
    "title": "Superman IV: The Quest for Peace",
    "media_type": "movie",
    "release_order": 95,
    "chronological_order": 95,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 11411,
    "poster_path": "https://image.tmdb.org/t/p/w500/nJFBeU1oKIaIoLVyQYUeB36DW55.jpg",
    "is_released": true,
    "release_date": "1987-07-24",
    "overview": "With global superpowers engaged in an increasingly hostile arms race, Superman leads a crusade to rid the world of nuclear weapons. But Lex Luthor, recently sprung from jail, is declaring war on the Man of Steel and his quest to save the planet. Using a strand of Superman's hair, Luthor synthesizes a powerful ally known as Nuclear Man and ignites an epic battle spanning Earth and space."
  },
  {
    "id": "dcu-96",
    "universe": "dcu",
    "title": "Superman Returns",
    "media_type": "movie",
    "release_order": 96,
    "chronological_order": 96,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 1452,
    "poster_path": "https://image.tmdb.org/t/p/w500/385XwTQZDpRX2d3kxtnpiLrjBXw.jpg",
    "is_released": true,
    "release_date": "2006-06-28",
    "overview": "Superman returns to discover his 5-year absence has allowed Lex Luthor to walk free, and that those he was closest to felt abandoned and have moved on. Luthor plots his ultimate revenge that could see millions killed and change the face of the planet forever, as well as ridding himself of the Man of Steel."
  },
  {
    "id": "dcu-97",
    "universe": "dcu",
    "title": "Smallville",
    "media_type": "show",
    "release_order": 97,
    "chronological_order": 97,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/mHZSq8LA5Dt48JjaOZ5tcPXQRVN.jpg",
    "is_released": true,
    "release_date": "2001-10-16",
    "overview": "The origins of the world’s greatest hero–from Krypton refugee Kal-el’s arrival on Earth through his tumultuous teen years to Clark Kent’s final steps toward embracing his destiny as the Man of Steel.",
    "seasons": 10,
    "episodes": 216
  },
  {
    "id": "dcu-98",
    "universe": "dcu",
    "title": "Young Justice",
    "media_type": "show",
    "release_order": 98,
    "chronological_order": 98,
    "phase_or_chapter": "Young Justice (Earth-16)",
    "tmdb_id": 33217,
    "poster_path": "https://image.tmdb.org/t/p/w500/zMJw34G4OJhcd9NjKSRjJdDqjbR.jpg",
    "is_released": true,
    "release_date": "2010-11-26",
    "overview": "Teenage superheroes strive to prove themselves as members of the Justice League.",
    "seasons": 4,
    "episodes": 98
  },
  {
    "id": "dcu-99",
    "universe": "dcu",
    "title": "Injustice",
    "media_type": "movie",
    "release_order": 99,
    "chronological_order": 99,
    "phase_or_chapter": "The Injustice Universe",
    "tmdb_id": 831405,
    "poster_path": "https://image.tmdb.org/t/p/w500/rzrSeqqpm1BwJ3tcTznztBtLLSD.jpg",
    "is_released": true,
    "release_date": "2021-10-09",
    "overview": "When Lois Lane is killed, an unhinged Superman decides to take control of the Earth. Determined to stop him, Batman creates a team of freedom-fighting heroes. But when superheroes go to war, can the world survive?"
  },
  {
    "id": "dcu-100",
    "universe": "dcu",
    "title": "Batman: Assault on Arkham",
    "media_type": "movie",
    "release_order": 100,
    "chronological_order": 100,
    "phase_or_chapter": "The Arkhamverse",
    "tmdb_id": 266396,
    "poster_path": "https://image.tmdb.org/t/p/w500/lnUozDnDANTsDYEdsNsHC6b8IiS.jpg",
    "is_released": true,
    "release_date": "2015-02-16",
    "overview": "Eight years after fleeing the Congo following his assassination of that country's minister of mining, former assassin Jim Terrier is back, suffering from PTSD and digging wells to atone for his violent past. After an attempt is made on his life, Terrier flies to London to find out who wants him dead -- and why. Terrier's search leads him to a reunion with Annie, a woman he once loved, who is now married to an oily businessman with dealings in Africa."
  }
];
