import { FranchiseMedia } from "../types";

export const DCU_SEED_DATA: FranchiseMedia[] = [
  {
    "id": "dcu-1",
    "universe": "dcu",
    "title": "Justice League: War",
    "media_type": "movie",
    "release_order": 1,
    "chronological_order": 34,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 216803,
    "poster_path": "https://image.tmdb.org/t/p/w500/mmi4oP8HZTznwuLtODyb6Uu2bKF.jpg",
    "is_released": true,
    "release_date": "1959-04-28",
    "overview": "Five longtime friends get back together, but are disappointed to find that their bonds are not as strong as they once were."
  },
  {
    "id": "dcu-2",
    "universe": "dcu",
    "title": "Superman",
    "media_type": "movie",
    "release_order": 2,
    "chronological_order": 2,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 1924,
    "poster_path": "https://image.tmdb.org/t/p/w500/d7px1FQxW4tngdACVRsCSaZq0Xl.jpg",
    "is_released": true,
    "release_date": "1978-12-14",
    "overview": "Mild-mannered Clark Kent works as a reporter at the Daily Planet alongside his crush, Lois Lane. Clark must summon his superhero alter-ego when the nefarious Lex Luthor launches a plan to take over the world."
  },
  {
    "id": "dcu-3",
    "universe": "dcu",
    "title": "Superman II",
    "media_type": "movie",
    "release_order": 3,
    "chronological_order": 3,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 8536,
    "poster_path": "https://image.tmdb.org/t/p/w500/3xk5cno9BHcnwc97XO9k21aI1Zi.jpg",
    "is_released": true,
    "release_date": "1980-12-04",
    "overview": "Three Kryptonian criminals led by General Zod team up with Lex Luthor to conquer Earth, forcing a depowered Superman to regain his strength and stop them."
  },
  {
    "id": "dcu-4",
    "universe": "dcu",
    "title": "Superman III",
    "media_type": "movie",
    "release_order": 4,
    "chronological_order": 5,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 9531,
    "poster_path": "https://image.tmdb.org/t/p/w500/c4oR6qgZW2s5foGkQi2Dd86KuAS.jpg",
    "is_released": true,
    "release_date": "1983-06-17",
    "overview": "Aiming to defeat the Man of Steel, wealthy executive Ross Webster hires bumbling but brilliant Gus Gorman to develop synthetic kryptonite, which yields some unexpected psychological effects. Between rekindling romance with his high school sweetheart and saving himself, Superman must contend with a powerful supercomputer."
  },
  {
    "id": "dcu-5",
    "universe": "dcu",
    "title": "Superman IV: The Quest for Peace",
    "media_type": "movie",
    "release_order": 5,
    "chronological_order": 9,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 11411,
    "poster_path": "https://image.tmdb.org/t/p/w500/nJFBeU1oKIaIoLVyQYUeB36DW55.jpg",
    "is_released": true,
    "release_date": "1987-07-24",
    "overview": "With global superpowers engaged in an increasingly hostile arms race, Superman leads a crusade to rid the world of nuclear weapons. But Lex Luthor, recently sprung from jail, is declaring war on the Man of Steel and his quest to save the planet. Using a strand of Superman's hair, Luthor synthesizes a powerful ally known as Nuclear Man and ignites an epic battle spanning Earth and space."
  },
  {
    "id": "dcu-6",
    "universe": "dcu",
    "title": "Batman (1989)",
    "media_type": "movie",
    "release_order": 6,
    "chronological_order": 10,
    "phase_or_chapter": "Burton / Schumacher (Earth-89)",
    "tmdb_id": 268,
    "poster_path": "https://image.tmdb.org/t/p/w500/cij4dd21v2Rk2YtUQbV5kW69WB2.jpg",
    "is_released": true,
    "release_date": "1989-06-21",
    "overview": "Having witnessed his parents' brutal murder as a child, millionaire philanthropist Bruce Wayne fights crime in Gotham City disguised as Batman, a costumed hero who strikes fear into the hearts of villains. But when a deformed madman known as 'The Joker' seizes control of Gotham's criminal underworld, Batman must face his most ruthless nemesis ever while protecting both his identity and his love interest, reporter Vicki Vale."
  },
  {
    "id": "dcu-7",
    "universe": "dcu",
    "title": "Batman Returns",
    "media_type": "movie",
    "release_order": 7,
    "chronological_order": 11,
    "phase_or_chapter": "Burton / Schumacher (Earth-89)",
    "tmdb_id": 364,
    "poster_path": "https://image.tmdb.org/t/p/w500/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg",
    "is_released": true,
    "release_date": "1992-06-19",
    "overview": "The monstrous Penguin, who dwells in the sewers beneath Gotham, joins up with corrupt mayoral candidate Max Shreck to topple the Batman once and for all. But when Shreck's timid assistant Selina Kyle finds out, and Shreck tries to kill her, she's transformed into the sexy Catwoman. She teams up with the Penguin and Shreck to destroy Batman, but sparks fly unexpectedly when she confronts the caped crusader."
  },
  {
    "id": "dcu-8",
    "universe": "dcu",
    "title": "Batman Forever",
    "media_type": "movie",
    "release_order": 8,
    "chronological_order": 12,
    "phase_or_chapter": "Burton / Schumacher (Earth-89)",
    "tmdb_id": 414,
    "poster_path": "https://image.tmdb.org/t/p/w500/i0fJS8M5UKoETjjJ0zwUiKaR8tr.jpg",
    "is_released": true,
    "release_date": "1995-06-16",
    "overview": "Batman faces off against two foes: the schizophrenic, horribly scarred former District Attorney Harvey Dent, aka Two-Face, and the Riddler, a disgruntled ex-Wayne Enterprises inventor seeking revenge against his former employer by unleashing his brain-sucking weapon on Gotham City's residents. As the caped crusader also copes with tortured memories of his parents' murder, he has a new romance, with psychologist Chase Meridian."
  },
  {
    "id": "dcu-9",
    "universe": "dcu",
    "title": "Batman & Robin",
    "media_type": "movie",
    "release_order": 9,
    "chronological_order": 13,
    "phase_or_chapter": "Burton / Schumacher (Earth-89)",
    "tmdb_id": 415,
    "poster_path": "https://image.tmdb.org/t/p/w500/i7hEUpDuMN2LOrCEifFyGSHZQSY.jpg",
    "is_released": true,
    "release_date": "1997-06-20",
    "overview": "Batman and his sidekick Robin attempt to the foil the sinister schemes of a deranged set of new villains, most notably the melancholy Mr. Freeze, who wants to make Gotham City into an arctic region, and the sultry Poison Ivy, a botanical femme fatale. As the Dynamic Duo contend with these bad guys, a third hero, Batgirl, joins the ranks of the city's crime-fighters."
  },
  {
    "id": "dcu-10",
    "universe": "dcu",
    "title": "Smallville (Season 1)",
    "media_type": "show",
    "release_order": 10,
    "chronological_order": 14,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/8dZVKFytdZAT0B5dMNrHxbZ9NrO.jpg",
    "is_released": true,
    "release_date": "2001-10-16",
    "overview": "Between the boy Clark Kent thought he was and the man he is destined to become lie the compelling stories of Smallville, the popular action series that reimagines the Superman saga from its roots.",
    "seasons": 1,
    "episodes": 21
  },
  {
    "id": "dcu-11",
    "universe": "dcu",
    "title": "Smallville (Season 2)",
    "media_type": "show",
    "release_order": 11,
    "chronological_order": 15,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/uSr3nf44jkWSswhNnToln9t1dLB.jpg",
    "is_released": true,
    "release_date": "2002-09-24",
    "overview": "The legend continues to grow stronger in the second super season of Smallville.  Throughout the season’s twenty-three episodes, Clark Kent grapples with his calling as he explores his true origins: was he sent to Earth to save humanity or destroy it?  Amidst all the chaos, Lana and Clark grow closer than before; Lex gets married; Lionel lures Chloe toward the dark side; the Kents receive miraculous news; and Pete becomes the keeper of Clark’s secret.",
    "seasons": 2,
    "episodes": 23
  },
  {
    "id": "dcu-12",
    "universe": "dcu",
    "title": "Smallville (Season 3)",
    "media_type": "show",
    "release_order": 12,
    "chronological_order": 16,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/f60xCocHvSKZE3hNh7JrlqVKg9V.jpg",
    "is_released": true,
    "release_date": "2003-10-01",
    "overview": "Everyone has a future.  Clark Kent has a destiny — if he’s willing to accept it and to master all the awesome powers and responsibilities that come with it. In an event-packed third season, the fascinating reinterpretation of the Superman mythology and its classic characters continues as Clark embraces the dark side and Jonathan Kent strikes a devil’s bargain with Jor-El to rescue his son.",
    "seasons": 3,
    "episodes": 22
  },
  {
    "id": "dcu-13",
    "universe": "dcu",
    "title": "Smallville (Season 4)",
    "media_type": "show",
    "release_order": 13,
    "chronological_order": 17,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/aVi3L1r9ZWOOSacAXvpIdoNCfWW.jpg",
    "is_released": true,
    "release_date": "2004-09-22",
    "overview": "Clark Kent will have plenty of reasons to remember his senior year! Lois Lane  — smart, opinionated, and entirely annoying to Clark — arrives in Smallville to investigate the death of her cousin. Lana gets a new older boyfriend. Clark decides to go against his parents' wishes and joins the football team as a quarterback. And while Clark sets off on a quest to find three mysterious Kryptonian crystals, Lex steps further from the light into darkness.",
    "seasons": 4,
    "episodes": 22
  },
  {
    "id": "dcu-14",
    "universe": "dcu",
    "title": "Batman Begins",
    "media_type": "movie",
    "release_order": 14,
    "chronological_order": 18,
    "phase_or_chapter": "The Dark Knight Trilogy",
    "tmdb_id": 272,
    "poster_path": "https://image.tmdb.org/t/p/w500/sPX89Td70IDDjVr85jdSBb4rWGr.jpg",
    "is_released": true,
    "release_date": "2005-06-10",
    "overview": "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman."
  },
  {
    "id": "dcu-15",
    "universe": "dcu",
    "title": "Smallville (Season 5)",
    "media_type": "show",
    "release_order": 15,
    "chronological_order": 19,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/ssd1X4oehoyv7AU75hwoGGX75nS.jpg",
    "is_released": true,
    "release_date": "2005-09-29",
    "overview": "Clark Kent now carries a full load of classes at Central Kansas University, but that's not all he carries. He carries the full weight of his — perhaps the world's — destiny. In season five, Clark finally begins to accept his destiny and takes giant leaps towards becoming the Man of Steel. He also crosses paths with Professor Milton Fine, whose presence in Smallville will have a devastating effect on his already deteriorating friendship with Lex.",
    "seasons": 5,
    "episodes": 22
  },
  {
    "id": "dcu-16",
    "universe": "dcu",
    "title": "Supergirl (1984)",
    "media_type": "movie",
    "release_order": 16,
    "chronological_order": 7,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 9655,
    "poster_path": "https://image.tmdb.org/t/p/w500/xRElqFcUVuGf0s2rAQSSNAn1IS9.jpg",
    "is_released": true,
    "release_date": "2006-03-17",
    "overview": "Viola Hastings is in a real jam. Complications threaten her scheme to pose as her twin brother, Sebastian, and take his place at a new boarding school. She falls in love with her handsome roommate, Duke, who loves beautiful Olivia, who has fallen for Sebastian! As if that were not enough, Viola's twin returns from London ahead of schedule but has no idea that his sister has already replaced him on campus."
  },
  {
    "id": "dcu-17",
    "universe": "dcu",
    "title": "Superman Returns",
    "media_type": "movie",
    "release_order": 17,
    "chronological_order": 20,
    "phase_or_chapter": "The Donnerverse (Earth-789)",
    "tmdb_id": 1452,
    "poster_path": "https://image.tmdb.org/t/p/w500/385XwTQZDpRX2d3kxtnpiLrjBXw.jpg",
    "is_released": true,
    "release_date": "2006-06-28",
    "overview": "Superman returns to discover his 5-year absence has allowed Lex Luthor to walk free, and that those he was closest to felt abandoned and have moved on. Luthor plots his ultimate revenge that could see millions killed and change the face of the planet forever, as well as ridding himself of the Man of Steel."
  },
  {
    "id": "dcu-18",
    "universe": "dcu",
    "title": "Smallville (Season 6)",
    "media_type": "show",
    "release_order": 18,
    "chronological_order": 21,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/r8xOSL0V4srx6KrWjgYY0ZqZfFS.jpg",
    "is_released": true,
    "release_date": "2006-09-28",
    "overview": "Clark manages to escape from the Phantom Zone with the help of an unexpected ally. He subsequently sets out on a mission to hunt down the dangerous prisoners who followed him to Earth. Adding to Clark's troubles, there is a new vigilante in town who goes by the name Green Arrow. Meanwhile, Lex and Lana take the next step in their relationship. As the season progresses, the rivalry between Clark Kent and Lex Luthor will explode into a fierce good-versus-evil battle.",
    "seasons": 6,
    "episodes": 22
  },
  {
    "id": "dcu-19",
    "universe": "dcu",
    "title": "Smallville (Season 7)",
    "media_type": "show",
    "release_order": 19,
    "chronological_order": 22,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/6lGHd6lBbpEkoq5pgI8XDRy2WYB.jpg",
    "is_released": true,
    "release_date": "2007-09-27",
    "overview": "When Clark's cousin Kara arrives on the scene, Clark advises her to keep a low profile and master her powers, but Kara has other ideas and becomes the focus of Lex Luthor's powerlust. And, there are two Clark Kents: one is the young man whose life in a tiny Kansas town sets him on destiny's path. The other is a Bizarro who shares Clark's DNA, but not his values. Lane makes a career leap and Chloe Sullivan finds that balancing a meteor power with a personal life isn't easy.",
    "seasons": 7,
    "episodes": 20
  },
  {
    "id": "dcu-20",
    "universe": "dcu",
    "title": "The Dark Knight",
    "media_type": "movie",
    "release_order": 20,
    "chronological_order": 23,
    "phase_or_chapter": "The Dark Knight Trilogy",
    "tmdb_id": 155,
    "poster_path": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "is_released": true,
    "release_date": "2008-07-16",
    "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker."
  },
  {
    "id": "dcu-21",
    "universe": "dcu",
    "title": "Smallville (Season 8)",
    "media_type": "show",
    "release_order": 21,
    "chronological_order": 24,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/jqEDADJiQbdtLMLSoXVulSiQkfh.jpg",
    "is_released": true,
    "release_date": "2008-09-18",
    "overview": "Last season, Clark Kent and Lex Luthor became sworn enemies and Clark discovered more about his home planet, who his parents were, what his future holds and why he was sent to Earth. In season eight, Clark Kent is now reporter at the Daily Planet who shares a workspace with Lois Lane. And there's a new hero in Metropolis - a hero everyone now calls the Red-Blue Blur.",
    "seasons": 8,
    "episodes": 22
  },
  {
    "id": "dcu-22",
    "universe": "dcu",
    "title": "Smallville (Season 9)",
    "media_type": "show",
    "release_order": 22,
    "chronological_order": 25,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/sxfkMgX4aEqvMQhDicf8LcbBWs3.jpg",
    "is_released": true,
    "release_date": "2009-09-25",
    "overview": "Last season, the enticing Tess Mercer maneuvered her way through town, discovered Clark's true identity and unleashed a new world of danger. Clark, he also met his greatest match: Doomsday. When Clark wasn't busy battling the beast, he was knee-deep in work at the Daily Planet. As Clark's persona as the cub Planet reporter emerged, so did his feelings for Lois, the fated love of his life. In season nine, Clark Kent has to rise to the occasion as Zod and his followers scheme to take control of planet Earth.",
    "seasons": 9,
    "episodes": 21
  },
  {
    "id": "dcu-23",
    "universe": "dcu",
    "title": "Smallville (Season 10)",
    "media_type": "show",
    "release_order": 23,
    "chronological_order": 26,
    "phase_or_chapter": "Smallville (Earth-167)",
    "tmdb_id": 4604,
    "poster_path": "https://image.tmdb.org/t/p/w500/nUiw76eCg1uT8uz5Ibtu6FWYlgX.jpg",
    "is_released": true,
    "release_date": "2010-09-24",
    "overview": "As season nine drew to a close, Clark sacrificed himself to save the world from General Zod. In the tenth and final season, the timeless romance between Clark and Lois romance continues to develop, and Clark will come face-to-face with his destiny as he overcomes his final trials and forges the iconic identity that will be known for all time.",
    "seasons": 10,
    "episodes": 21
  },
  {
    "id": "dcu-24",
    "universe": "dcu",
    "title": "Young Justice (Season 1)",
    "media_type": "show",
    "release_order": 24,
    "chronological_order": 27,
    "phase_or_chapter": "Young Justice (Earth-16)",
    "tmdb_id": 33217,
    "poster_path": "https://image.tmdb.org/t/p/w500/fn2wMnrPWIjDMnxIf0H89ZtDehK.jpg",
    "is_released": true,
    "release_date": "2010-11-26",
    "overview": "Robin, Aqualad, Kid Flash, Superboy, Miss Martian, and Artemis form Young Justice -- and find out whether they have what it takes to be a proven hero.",
    "seasons": 1,
    "episodes": 26
  },
  {
    "id": "dcu-25",
    "universe": "dcu",
    "title": "Young Justice: Invasion (Season 2)",
    "media_type": "show",
    "release_order": 25,
    "chronological_order": 38,
    "phase_or_chapter": "Young Justice (Earth-16)",
    "tmdb_id": 33217,
    "poster_path": "https://image.tmdb.org/t/p/w500/ufu4g1s98H0Q5NbsEdoTct44IUW.jpg",
    "is_released": true,
    "release_date": "2012-04-28",
    "overview": "In Season 2, we pick up with the team five years later, as they fight off a secret alien invasion affecting the entire planet.",
    "seasons": 2,
    "episodes": 20
  },
  {
    "id": "dcu-26",
    "universe": "dcu",
    "title": "The Dark Knight Rises",
    "media_type": "movie",
    "release_order": 26,
    "chronological_order": 28,
    "phase_or_chapter": "The Dark Knight Trilogy",
    "tmdb_id": 49026,
    "poster_path": "https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
    "is_released": true,
    "release_date": "2012-07-17",
    "overview": "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy."
  },
  {
    "id": "dcu-27",
    "universe": "dcu",
    "title": "Arrow (Season 1)",
    "media_type": "show",
    "release_order": 27,
    "chronological_order": 29,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 1412,
    "poster_path": "https://image.tmdb.org/t/p/w500/pAdZsHyk7ROQqHzzK8QIM8OnR5f.jpg",
    "is_released": true,
    "release_date": "2012-10-10",
    "overview": "Oliver Queen returns to Starling city after being deserted on a hellish island for five years. He decides to become a mask wearing vigilante to fulfil his father's wishes and rid the city of crime. In his journey to do so, he is forced to make tough decisions even as he makes new friends and even more enemies which continue question his lethal ways of controlling crime.",
    "seasons": 1,
    "episodes": 23
  },
  {
    "id": "dcu-28",
    "universe": "dcu",
    "title": "Justice League: The Flashpoint Paradox",
    "media_type": "movie",
    "release_order": 28,
    "chronological_order": 31,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 142061,
    "poster_path": "https://image.tmdb.org/t/p/w500/d1TqoVkyL4x0dlu9w3F9Ah4LjNv.jpg",
    "is_released": true,
    "release_date": "2013-01-03",
    "overview": "Batman has stopped the reign of terror that The Mutants had cast upon his city.  Now an old foe wants a reunion and the government wants The Man of Steel to put a stop to Batman."
  },
  {
    "id": "dcu-29",
    "universe": "dcu",
    "title": "Man of Steel",
    "media_type": "movie",
    "release_order": 29,
    "chronological_order": 32,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 49521,
    "poster_path": "https://image.tmdb.org/t/p/w500/8GFtkImmK0K1VaUChR0n9O61CFU.jpg",
    "is_released": true,
    "release_date": "2013-06-12",
    "overview": "A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind."
  },
  {
    "id": "dcu-30",
    "universe": "dcu",
    "title": "Arrow (Season 2)",
    "media_type": "show",
    "release_order": 30,
    "chronological_order": 30,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 1412,
    "poster_path": "https://image.tmdb.org/t/p/w500/wF9HS0mLjO0rwjUYw9iCxlpy0KU.jpg",
    "is_released": true,
    "release_date": "2013-10-09",
    "overview": "Sworn to fight crime and corruption in his city, Oliver Queen – with the help of tech-savvy Felicity Smoak and his iron-fisted right hand, John Diggle – narrowly averts the rich and powerful's \"Undertaking\" as the Dark Archer rocked Queen's world in the first season finale of ARROW. But who's going to pick up the pieces? In Season Two, see how Oliver Queen goes from Hood to Hero!",
    "seasons": 2,
    "episodes": 23
  },
  {
    "id": "dcu-31",
    "universe": "dcu",
    "title": "Son of Batman",
    "media_type": "movie",
    "release_order": 31,
    "chronological_order": 36,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 251519,
    "poster_path": "https://image.tmdb.org/t/p/w500/yHx8OLSKc3VtIBB5lIe90c0fHOX.jpg",
    "is_released": true,
    "release_date": "2014-05-13",
    "overview": "Batman learns he has a violent, unruly pre-teen son, secretly raised by the terrorist group known as The League of Assassins."
  },
  {
    "id": "dcu-32",
    "universe": "dcu",
    "title": "Justice League: Throne of Atlantis",
    "media_type": "movie",
    "release_order": 32,
    "chronological_order": 40,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 287590,
    "poster_path": "https://image.tmdb.org/t/p/w500/gxKfP9278RK4t3J8vLXoFfB8ihl.jpg",
    "is_released": true,
    "release_date": "2014-06-21",
    "overview": "Mitsumasa Kido discovers a misterious baby in the himalayas whom he adopts as his grandaughter. 16 years later, Saori Kido is a young girl troubled by her mysterious powers. She is saved by Seiya from an assassin sent to kill her. Saori then learns she is the reincarnation of the Goddess Athena with Seiya being one of her Saints sworn to protect her. Upon learning of her destiny, she heads to the Sanctuary to rebel against the Pope's murderous plot."
  },
  {
    "id": "dcu-33",
    "universe": "dcu",
    "title": "The Flash (Season 1)",
    "media_type": "show",
    "release_order": 33,
    "chronological_order": 33,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/A3H6pewHfoy2bXmNhvycOe0xzlC.jpg",
    "is_released": true,
    "release_date": "2014-10-06",
    "overview": "When an unexpected accident at the S.T.A.R. Labs Particle Accelerator facility strikes Barry, he finds himself suddenly charged with the incredible power to move at super speeds. While Barry has always been a hero in his soul, his newfound powers have finally given him the ability to act like one. With the help of the research team at S.T.A.R. Labs, Barry begins testing the limits of his evolving powers and using them to stop crime. With a winning personality and a smile on his face, Barry Allen — aka The Flash — is finally moving forward in life … very, very fast!",
    "seasons": 1,
    "episodes": 23
  },
  {
    "id": "dcu-34",
    "universe": "dcu",
    "title": "Arrow (Season 3)",
    "media_type": "show",
    "release_order": 34,
    "chronological_order": 35,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 1412,
    "poster_path": "https://image.tmdb.org/t/p/w500/uWwGLfG1SVeXseEo5VYO2IfT5VJ.jpg",
    "is_released": true,
    "release_date": "2014-10-08",
    "overview": "Protecting his city from crime and corruption, vigilante hero Oliver Queen (aka The Green Arrow) uses his formidable combat skills and marksmanship to go up against lethal foes including Deathstroke, Ra's al Ghul and Damien Darhk's HIVE, becoming a beacon of hope for all in need.",
    "seasons": 3,
    "episodes": 23
  },
  {
    "id": "dcu-35",
    "universe": "dcu",
    "title": "Batman: Assault on Arkham",
    "media_type": "movie",
    "release_order": 35,
    "chronological_order": 37,
    "phase_or_chapter": "The Arkhamverse",
    "tmdb_id": 266396,
    "poster_path": "https://image.tmdb.org/t/p/w500/lnUozDnDANTsDYEdsNsHC6b8IiS.jpg",
    "is_released": true,
    "release_date": "2015-02-16",
    "overview": "Eight years after fleeing the Congo following his assassination of that country's minister of mining, former assassin Jim Terrier is back, suffering from PTSD and digging wells to atone for his violent past. After an attempt is made on his life, Terrier flies to London to find out who wants him dead -- and why. Terrier's search leads him to a reunion with Annie, a woman he once loved, who is now married to an oily businessman with dealings in Africa."
  },
  {
    "id": "dcu-36",
    "universe": "dcu",
    "title": "Batman vs. Robin",
    "media_type": "movie",
    "release_order": 36,
    "chronological_order": 42,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 321528,
    "poster_path": "https://image.tmdb.org/t/p/w500/aGp9XDXmVM5lCKHWtgBC15S7XLr.jpg",
    "is_released": true,
    "release_date": "2015-04-03",
    "overview": "Damian Wayne is having a hard time coping with his father's \"no killing\" rule. Meanwhile, Gotham is going through hell with threats such as the insane Dollmaker, and the secretive Court of Owls."
  },
  {
    "id": "dcu-37",
    "universe": "dcu",
    "title": "Vixen (Season 1)",
    "media_type": "show",
    "release_order": 37,
    "chronological_order": 39,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 64264,
    "poster_path": "https://image.tmdb.org/t/p/w500/pF6vrER1XYF4hrtGytMVysoiGR8.jpg",
    "is_released": true,
    "release_date": "2015-09-12",
    "overview": "A live-action sitcom about two 12-year-old girls who start a multi-million-dollar gaming company and take on rap superstar Double G as a business partner.",
    "seasons": 1,
    "episodes": 21
  },
  {
    "id": "dcu-38",
    "universe": "dcu",
    "title": "The Flash (Season 2)",
    "media_type": "show",
    "release_order": 38,
    "chronological_order": 41,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/8xWZPVX1cv9V5YD1RPeLj9QZDE9.jpg",
    "is_released": true,
    "release_date": "2015-10-05",
    "overview": "Following the dramatic events of season 1, Team Flash quickly turns their attention to a threat high above Central City. Armed with the heart of a hero and the ability to move at super speeds, will Barry be able to save his city from impending doom?",
    "seasons": 2,
    "episodes": 23
  },
  {
    "id": "dcu-39",
    "universe": "dcu",
    "title": "Arrow (Season 4)",
    "media_type": "show",
    "release_order": 39,
    "chronological_order": 43,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 1412,
    "poster_path": "https://image.tmdb.org/t/p/w500/hAl1Ypfsb01UOUGNmopMu6skThT.jpg",
    "is_released": true,
    "release_date": "2015-10-07",
    "overview": "After defeating his most formidable foe to date, Oliver Queen left Starling City with the hopes of beginning a new life with longtime flame Felicity Smoak. But will Oliver ever truly be able to leave behind his past as the Arrow, and, if so, what becomes of his team? Will Diggle, Thea, and Laurel continue the crusade? And with Malcolm Merlyn leading the League of Assassins is anyone really safe?",
    "seasons": 4,
    "episodes": 23
  },
  {
    "id": "dcu-40",
    "universe": "dcu",
    "title": "Supergirl (Season 1)",
    "media_type": "show",
    "release_order": 40,
    "chronological_order": 44,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62688,
    "poster_path": "https://image.tmdb.org/t/p/w500/29KJKrp0wxnixFXLfNGTNCEBIyb.jpg",
    "is_released": true,
    "release_date": "2015-10-26",
    "overview": "Kara Zor-El, Superman’s cousin, decides to finally embrace her superhuman abilities and become the hero she was always meant to be. Though Kara will need to find a way to manage her newfound powers with her very human relationships, her heart soars as she takes to the skies to fight crime.",
    "seasons": 1,
    "episodes": 20
  },
  {
    "id": "dcu-41",
    "universe": "dcu",
    "title": "Batman: Bad Blood",
    "media_type": "movie",
    "release_order": 41,
    "chronological_order": 47,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 366924,
    "poster_path": "https://image.tmdb.org/t/p/w500/ktjbGsGm5GKlHDvvwQajXvDW2BN.jpg",
    "is_released": true,
    "release_date": "2016-01-19",
    "overview": "When Batman goes missing, it takes the entire Bat \"family\" - including Batwoman and Batwing - to keep the peace in Gotham and unravel the mystery behind the Dark Knight's disappearance."
  },
  {
    "id": "dcu-42",
    "universe": "dcu",
    "title": "DC's Legends of Tomorrow (Season 1)",
    "media_type": "show",
    "release_order": 42,
    "chronological_order": 46,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62643,
    "poster_path": "https://image.tmdb.org/t/p/w500/xEY4YPu7FCKQNSnMaaHo4NJl3ID.jpg",
    "is_released": true,
    "release_date": "2016-01-21",
    "overview": "When heroes alone are not enough… The world needs legends. Having seen the future, traveling rogue Rip Hunter assembles a disparate group of both heroes and villains to confront the unstoppable threat of the immortal Vandal Savage- a threat which not only puts the planet at stake, but all of time itself. From the creators of The Flash and Arrow comes this super hero team-up that combines characters from both shows – in addition to new heroes from the DC Comics pantheon. Featuring Arrow’s Brandon Routh as The Atom and Caity Lotz as the resurrected Sara Lance/White Canary; with The Flash’s Victor Garber as Dr. Martin Stein alongside Wentworth Miller as Captain Cold and Dominic Purcell as Heat Wave; plus, the newest heroes Rip Hunter, Jeff Jackson and the reincarnated warrior queen Hawkgirl, this singular super hero spinoff series pits the ragtag team against one of the most powerful villains in the DC Comics universe.",
    "seasons": 1,
    "episodes": 16
  },
  {
    "id": "dcu-43",
    "universe": "dcu",
    "title": "Batman v Superman: Dawn of Justice",
    "media_type": "movie",
    "release_order": 43,
    "chronological_order": 45,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 209112,
    "poster_path": "https://image.tmdb.org/t/p/w500/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
    "is_released": true,
    "release_date": "2016-03-23",
    "overview": "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before."
  },
  {
    "id": "dcu-44",
    "universe": "dcu",
    "title": "Suicide Squad",
    "media_type": "movie",
    "release_order": 44,
    "chronological_order": 48,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 297761,
    "poster_path": "https://image.tmdb.org/t/p/w500/sk3FZgh3sRrmr8vyhaitNobMcfh.jpg",
    "is_released": true,
    "release_date": "2016-08-03",
    "overview": "From DC Comics comes the Suicide Squad, an antihero team of incarcerated supervillains who act as deniable assets for the United States government, undertaking high-risk black ops missions in exchange for commuted prison sentences."
  },
  {
    "id": "dcu-45",
    "universe": "dcu",
    "title": "Justice League vs. Teen Titans",
    "media_type": "movie",
    "release_order": 45,
    "chronological_order": 50,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 377264,
    "poster_path": "https://image.tmdb.org/t/p/w500/iqEFG5ldyeLIFPp7mMI7ZmS7Upm.jpg",
    "is_released": true,
    "release_date": "2016-09-01",
    "overview": "A corporate risk-management consultant must determine whether or not to terminate an artificial being's life that was made in a laboratory environment."
  },
  {
    "id": "dcu-46",
    "universe": "dcu",
    "title": "Vixen (Season 2)",
    "media_type": "show",
    "release_order": 46,
    "chronological_order": 49,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 64264,
    "poster_path": "https://image.tmdb.org/t/p/w500/9OWXHslRJgue3r3BjzRzQB8m91b.jpg",
    "is_released": true,
    "release_date": "2016-09-18",
    "overview": "A live-action sitcom about two 12-year-old girls who start a multi-million-dollar gaming company and take on rap superstar Double G as a business partner.",
    "seasons": 2,
    "episodes": 24
  },
  {
    "id": "dcu-47",
    "universe": "dcu",
    "title": "The Flash (Season 3)",
    "media_type": "show",
    "release_order": 47,
    "chronological_order": 51,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/rN1hgV8Ag3bZmkv33Udm93hIxQp.jpg",
    "is_released": true,
    "release_date": "2016-10-03",
    "overview": "Forensic scientist Barry Allen, aka The Flash, is living his dream life. His parents are alive. He's dating beautiful, smart Iris West. And he's able to stand back and let the new speedster in town, Kid Flash, step in to protect Central City. But the better Barry's life gets, the more dangerous it becomes. His nemesis, Reverse Flash, warns Barry of serious repercussions if he remains in the alternate Flashpoint universe: In addition to memory loss, his powers will fade. When disaster strikes, Barry must decide whether to continue life as Barry Allen or return to his universe as The Flash. As Barry deals with his identity crisis, he and the S.T.A.R. Labs team fight off lethal threats from the God of Speed, Savitar.",
    "seasons": 3,
    "episodes": 23
  },
  {
    "id": "dcu-48",
    "universe": "dcu",
    "title": "Arrow (Season 5)",
    "media_type": "show",
    "release_order": 48,
    "chronological_order": 52,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 1412,
    "poster_path": "https://image.tmdb.org/t/p/w500/uzGRZtaDTh0nKruS0raXVZnGQAj.jpg",
    "is_released": true,
    "release_date": "2016-10-05",
    "overview": "Protecting his city from crime and corruption, vigilante hero Oliver Queen uses his formidable combat skills and marksmanship to go up against lethal foes including Deathstroke, Ra's al Ghul and Damien Darhk and Prometheus, becoming a beacon of hope for all in need.",
    "seasons": 5,
    "episodes": 23
  },
  {
    "id": "dcu-49",
    "universe": "dcu",
    "title": "Supergirl (Season 2)",
    "media_type": "show",
    "release_order": 49,
    "chronological_order": 53,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62688,
    "poster_path": "https://image.tmdb.org/t/p/w500/acTFrLvvkVo5kWBKR8QwX2CVcQg.jpg",
    "is_released": true,
    "release_date": "2016-10-10",
    "overview": "Having left the safety of being Cat Grant’s assistant in order to figure out what she really wants to do, Kara continues to work at the DEO as Supergirl, protecting the citizens of National City and searching for Jeremiah and Cadmus. Along the way, she will team up with Superman to battle new villains, as she strives to balance her personal life with her life as a superhero.",
    "seasons": 2,
    "episodes": 22
  },
  {
    "id": "dcu-50",
    "universe": "dcu",
    "title": "DC's Legends of Tomorrow (Season 2)",
    "media_type": "show",
    "release_order": 50,
    "chronological_order": 54,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62643,
    "poster_path": "https://image.tmdb.org/t/p/w500/eEbK6AJlVBtRqagPJvHk8wQ4Ktb.jpg",
    "is_released": true,
    "release_date": "2016-10-13",
    "overview": "Season two amps up the firepower by enlisting both a league and a legion of new characters. Joining Rex Tyler aka Hourman will be other members of the Justice Society of America. And for every force of good, there is an opposing force of darkness. The Legends of Tomorrow will face off against the first ever team of Super-Villains: the Legion of Doom, including Malcolm Merlyn, Damien Darhk, Captain Cold and the Reverse Flash. After saving the world from Vandal Savage, the Legends of Tomorrow are now charged with protecting time (past, present and future) itself, taking them across history and up against a threat unlike any humanity has ever known.",
    "seasons": 2,
    "episodes": 17
  },
  {
    "id": "dcu-51",
    "universe": "dcu",
    "title": "Justice League Dark",
    "media_type": "movie",
    "release_order": 51,
    "chronological_order": 56,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 408220,
    "poster_path": "https://image.tmdb.org/t/p/w500/gWcTaDFXDrOAPfVzfBFz0Aya5BE.jpg",
    "is_released": true,
    "release_date": "2017-01-24",
    "overview": "When innocent civilians begin committing unthinkable crimes across Metropolis, Gotham City and beyond, Batman must call upon mystical counterparts to eradicate this demonic threat to the planet; enter Justice League Dark. This team of Dark Arts specialists must unravel the mystery of Earth's supernatural plague and contend with the rising, powerful villainous forces behind the siege—before it's too late for all of mankind."
  },
  {
    "id": "dcu-52",
    "universe": "dcu",
    "title": "Teen Titans: The Judas Contract",
    "media_type": "movie",
    "release_order": 52,
    "chronological_order": 59,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 408647,
    "poster_path": "https://image.tmdb.org/t/p/w500/nuGIlNAJUati4qEAH1nrYKUA3xa.jpg",
    "is_released": true,
    "release_date": "2017-04-04",
    "overview": "Tara Markov is a girl who has power over earth and stone; she is also more than she seems. Is the newest Teen Titan an ally or a threat? And what are the mercenary Deathstroke's plans for the Titans?"
  },
  {
    "id": "dcu-53",
    "universe": "dcu",
    "title": "Wonder Woman",
    "media_type": "movie",
    "release_order": 53,
    "chronological_order": 1,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 297762,
    "poster_path": "https://image.tmdb.org/t/p/w500/v4ncgZjG2Zu8ZW5al1vIZTsSjqX.jpg",
    "is_released": true,
    "release_date": "2017-05-30",
    "overview": "An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict."
  },
  {
    "id": "dcu-54",
    "universe": "dcu",
    "title": "Supergirl (Season 3)",
    "media_type": "show",
    "release_order": 54,
    "chronological_order": 55,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62688,
    "poster_path": "https://image.tmdb.org/t/p/w500/oNOXcu8SdfSAHfHGnpb7NvcFLww.jpg",
    "is_released": true,
    "release_date": "2017-10-09",
    "overview": "As season three returns with all-new supercharged adventures this fall, Kara and team will come up against a new threat in the form of DC Worldkiller, Reign.",
    "seasons": 3,
    "episodes": 23
  },
  {
    "id": "dcu-55",
    "universe": "dcu",
    "title": "The Flash (Season 4)",
    "media_type": "show",
    "release_order": 55,
    "chronological_order": 58,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/e6A65vhYFLqgSsMI294ZQi0rQfH.jpg",
    "is_released": true,
    "release_date": "2017-10-10",
    "overview": "The mission of Barry Allen, aka The Flash, is once more to protect Central City from metahuman threats. But with Barry trapped in the Speed Force, this mission falls to his family – Detective Joe West; fiancée Iris West; and Wally West/Kid Flash – and the team at S.T.A.R. Labs: Caitlin Snow/Killer Frost, Cisco Ramon/Vibe and brilliant scientist Harrison Wells. When a powerful villain threatens to level the city unless The Flash appears, Cisco risks everything to free Barry. But this is only the first move in a deadly game with Clifford DeVoe, aka The Thinker, a mastermind who’s always ten steps ahead of Barry, no matter how fast Barry runs.",
    "seasons": 4,
    "episodes": 23
  },
  {
    "id": "dcu-56",
    "universe": "dcu",
    "title": "DC's Legends of Tomorrow (Season 3)",
    "media_type": "show",
    "release_order": 56,
    "chronological_order": 61,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62643,
    "poster_path": "https://image.tmdb.org/t/p/w500/krLJpUiuJOGroJ6xvAcTQcy2iZO.jpg",
    "is_released": true,
    "release_date": "2017-10-10",
    "overview": "In season three, DC’s Legends of Tomorrow face a new existential threat created by their actions at the end of last season. By revisiting a moment in time they’d already participated in, they’ve essentially fractured the timeline and created anachronisms all across time! Our team must find a way to return all the anachronisms to their original timelines before the time stream falls apart. But before our Legends can jump back into action, Rip Hunter and his newly established Time Bureau call their methods into question and disband the team. Challenging the Time Bureau’s authority, they recruit a hacker from the future, Zari Tomaz and continue their time travelling shenanigans, while insisting that however messy their methods may be, some problems are beyond the Bureau’s capabilities. Some problems can only be fixed by Legends.",
    "seasons": 3,
    "episodes": 18
  },
  {
    "id": "dcu-57",
    "universe": "dcu",
    "title": "Arrow (Season 6)",
    "media_type": "show",
    "release_order": 57,
    "chronological_order": 62,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 1412,
    "poster_path": "https://image.tmdb.org/t/p/w500/wVWsK34umDltQPaYsfhW1mZhkN0.jpg",
    "is_released": true,
    "release_date": "2017-10-12",
    "overview": "After last season's emotional showdown between Oliver Queen and Adrian Chase, the focus shifts into uncovering the fate of each and every member of Team Arrow – with their futures left hanging precariously in the balance. Having finally solidified and strengthened his crime-fighting team, the Green Arrow might be forced to rethink his relationships with his \"family\" in Season 6.",
    "seasons": 6,
    "episodes": 23
  },
  {
    "id": "dcu-58",
    "universe": "dcu",
    "title": "Justice League",
    "media_type": "movie",
    "release_order": 58,
    "chronological_order": 57,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 141052,
    "poster_path": "https://image.tmdb.org/t/p/w500/eifGNCSDuxJeS1loAXil5bIGgvC.jpg",
    "is_released": true,
    "release_date": "2017-11-15",
    "overview": "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth."
  },
  {
    "id": "dcu-59",
    "universe": "dcu",
    "title": "Freedom Fighters: The Ray (Season 1)",
    "media_type": "show",
    "release_order": 59,
    "chronological_order": 63,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 75219,
    "poster_path": "https://image.tmdb.org/t/p/w500/pNDfftsiCLLUZxy7dUbGW4daRjH.jpg",
    "is_released": true,
    "release_date": "2018-01-03",
    "overview": "Explore the high-pressure experiences of police officers, paramedics and firefighters who are thrust into the most frightening, shocking and heart-stopping situations. These emergency responders must try to balance saving those who are at their most vulnerable with solving the problems in their own lives.",
    "seasons": 1,
    "episodes": 10
  },
  {
    "id": "dcu-60",
    "universe": "dcu",
    "title": "Black Lightning (Season 1)",
    "media_type": "show",
    "release_order": 60,
    "chronological_order": 65,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 71663,
    "poster_path": "https://image.tmdb.org/t/p/w500/wnDoA1QFNHLUwte9YVozLd86D9N.jpg",
    "is_released": true,
    "release_date": "2018-01-16",
    "overview": "School principal and retired superhero Jefferson Pierce leaps back into action as the legendary Black Lightning after a gang threatens his family.",
    "seasons": 1,
    "episodes": 13
  },
  {
    "id": "dcu-61",
    "universe": "dcu",
    "title": "Booster Gold (Season 1)",
    "media_type": "show",
    "release_order": 61,
    "chronological_order": 129,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 220028,
    "poster_path": "https://image.tmdb.org/t/p/w500/bkCuGL8oocvJsYtqZ39F04EpCWJ.jpg",
    "is_released": false,
    "release_date": "2018-01-25",
    "overview": "Booster Gold (Season 1)",
    "seasons": 1,
    "episodes": 26
  },
  {
    "id": "dcu-62",
    "universe": "dcu",
    "title": "The Death of Superman",
    "media_type": "movie",
    "release_order": 62,
    "chronological_order": 69,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 505262,
    "poster_path": "https://image.tmdb.org/t/p/w500/hC4nTxdhXqFWzgqynGvvXVMiMNp.jpg",
    "is_released": true,
    "release_date": "2018-08-03",
    "overview": "All Might and Deku accept an invitation to go abroad to a floating and mobile manmade city, called 'I-Island', where they research quirks as well as hero supplemental items at the special 'I-Expo' convention that is currently being held on the island. During that time, suddenly, despite an iron wall of security surrounding the island, the system is breached by a villain, and the only ones able to stop him are the students of Class 1-A."
  },
  {
    "id": "dcu-63",
    "universe": "dcu",
    "title": "Freedom Fighters: The Ray (Season 2)",
    "media_type": "show",
    "release_order": 63,
    "chronological_order": 68,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 75219,
    "poster_path": "https://image.tmdb.org/t/p/w500/o8gfGyvvU1YhCC0RMVktzDbsph0.jpg",
    "is_released": true,
    "release_date": "2018-09-23",
    "overview": "Explore the high-pressure experiences of police officers, paramedics and firefighters who are thrust into the most frightening, shocking and heart-stopping situations. These emergency responders must try to balance saving those who are at their most vulnerable with solving the problems in their own lives.",
    "seasons": 2,
    "episodes": 18
  },
  {
    "id": "dcu-64",
    "universe": "dcu",
    "title": "The Flash (Season 5)",
    "media_type": "show",
    "release_order": 64,
    "chronological_order": 70,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/z3CqL2vnjgLuefOiR5AYD9Tf91S.jpg",
    "is_released": true,
    "release_date": "2018-10-09",
    "overview": "Barry Allen and his new wife, Iris West, finally settling into married life when they're visited by Nora West-Allen, their speedster daughter from the future. Nora's arrival brings to light the legacy every member of Team Flash will leave years from now, causing many to question who they are today. And while Nora idolizes Barry, she holds a mysterious grudge against Iris. As Team Flash adjusts to the next generation of speedster, they discover Nora's presence has triggered the arrival of the most ruthless, vicious and relentless villain they have ever faced: Cicada!",
    "seasons": 5,
    "episodes": 22
  },
  {
    "id": "dcu-65",
    "universe": "dcu",
    "title": "Black Lightning (Season 2)",
    "media_type": "show",
    "release_order": 65,
    "chronological_order": 72,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 71663,
    "poster_path": "https://image.tmdb.org/t/p/w500/7R3jEEfRV2a3ElvMzrY4DnYJS8I.jpg",
    "is_released": true,
    "release_date": "2018-10-09",
    "overview": "As Jefferson and his family wrestle with shocking revelations and new threats from Tobias, Freeland demands justice for the \"pod people.\"",
    "seasons": 2,
    "episodes": 16
  },
  {
    "id": "dcu-66",
    "universe": "dcu",
    "title": "Supergirl (Season 4)",
    "media_type": "show",
    "release_order": 66,
    "chronological_order": 73,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62688,
    "poster_path": "https://image.tmdb.org/t/p/w500/ivqcndOjIWBuDJBjcFmtzehBzET.jpg",
    "is_released": true,
    "release_date": "2018-10-14",
    "overview": "In season four, Supergirl is facing a bigger threat than she's ever faced before – a new wave of anti-alien sentiment, spreading across National City that’s fomented by Agent Liberty. As Kara mentors a new reporter at CatCo, Nia Nal, and tries to use the power of the press to shine a light on the issues threatening to tear the city apart, Supergirl takes to the skies to battle the many villains who rise up in this era of divisiveness.",
    "seasons": 4,
    "episodes": 22
  },
  {
    "id": "dcu-67",
    "universe": "dcu",
    "title": "Arrow (Season 7)",
    "media_type": "show",
    "release_order": 67,
    "chronological_order": 74,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 1412,
    "poster_path": "https://image.tmdb.org/t/p/w500/ggkzHq0CBRcCwY5NL2MLaUzGXGW.jpg",
    "is_released": true,
    "release_date": "2018-10-15",
    "overview": "In Season Seven, Oliver Queen will find himself vulnerable in a way unlike ever before when a mysterious new enemy begins to unravel his work as Green Arrow, forcing him to redeem his name or risk losing everything.",
    "seasons": 7,
    "episodes": 22
  },
  {
    "id": "dcu-68",
    "universe": "dcu",
    "title": "Waller (Season 1)",
    "media_type": "show",
    "release_order": 68,
    "chronological_order": 123,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 220027,
    "poster_path": "https://image.tmdb.org/t/p/w500/7imkRYpmM7IVCLIiOZZARKLlkSL.jpg",
    "is_released": false,
    "release_date": "2018-10-21",
    "overview": "In the new SBS6 program Scammers on the internet, Kees van der Spek helps victims who have been scammed for large sums digitally. Kees travels at home and abroad to track down the internet scammers that cannot be found at that time. Will Kees succeed in finding out who is the online vendor who collects money but never delivers anything? And who is behind the counterfeit bank emails that many Dutch people receive?",
    "seasons": 1,
    "episodes": 4
  },
  {
    "id": "dcu-69",
    "universe": "dcu",
    "title": "DC's Legends of Tomorrow (Season 4)",
    "media_type": "show",
    "release_order": 69,
    "chronological_order": 75,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62643,
    "poster_path": "https://image.tmdb.org/t/p/w500/icv3e1l8od9VjQD4NlvpBySyY09.jpg",
    "is_released": true,
    "release_date": "2018-10-22",
    "overview": "In season four, the Legends find themselves in unfamiliar territory with the Time Bureau. All that changes when Constantine informs Sara of a new magical threat that leads the team to Woodstock.",
    "seasons": 4,
    "episodes": 16
  },
  {
    "id": "dcu-70",
    "universe": "dcu",
    "title": "Aquaman",
    "media_type": "movie",
    "release_order": 70,
    "chronological_order": 67,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 297802,
    "poster_path": "https://image.tmdb.org/t/p/w500/ufl63EFcc5XpByEV2Ecdw6WJZAI.jpg",
    "is_released": true,
    "release_date": "2018-12-07",
    "overview": "Half-human, half-Atlantean Arthur Curry is taken on the journey of his lifetime to discover if he is worth of being a king."
  },
  {
    "id": "dcu-71",
    "universe": "dcu",
    "title": "Young Justice: Outsiders (Season 3)",
    "media_type": "show",
    "release_order": 71,
    "chronological_order": 64,
    "phase_or_chapter": "Young Justice (Earth-16)",
    "tmdb_id": 33217,
    "poster_path": "https://image.tmdb.org/t/p/w500/oL31ADgSgVdgoJPRAdWISQBIO0w.jpg",
    "is_released": true,
    "release_date": "2019-01-04",
    "overview": "In Season 3, the team faces its greatest challenge yet as it takes on meta-human trafficking and the terrifying threat it creates for a society caught in the crossfire of a global and galaxy-wide genetic arms race.",
    "seasons": 3,
    "episodes": 26
  },
  {
    "id": "dcu-72",
    "universe": "dcu",
    "title": "Shazam!",
    "media_type": "movie",
    "release_order": 72,
    "chronological_order": 78,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 287947,
    "poster_path": "https://image.tmdb.org/t/p/w500/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
    "is_released": true,
    "release_date": "2019-03-29",
    "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word."
  },
  {
    "id": "dcu-73",
    "universe": "dcu",
    "title": "Wonder Woman: Bloodlines",
    "media_type": "movie",
    "release_order": 73,
    "chronological_order": 82,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 537059,
    "poster_path": "https://image.tmdb.org/t/p/w500/xXC0HrmyQDXlYTiHP7Tq6nzurDI.jpg",
    "is_released": true,
    "release_date": "2019-03-29",
    "overview": "The Justice League faces a powerful new threat — the Fatal Five! Superman, Batman and Wonder Woman seek answers as the time-traveling trio of Mano, Persuader and Tharok terrorize Metropolis in search of budding Green Lantern, Jessica Cruz. With her unwilling help, they aim to free remaining Fatal Five members Emerald Empress and Validus to carry out their sinister plan. But the Justice League has also discovered an ally from another time in the peculiar Star Boy — brimming with volatile power, could he be the key to thwarting the Fatal Five? An epic battle against ultimate evil awaits!"
  },
  {
    "id": "dcu-74",
    "universe": "dcu",
    "title": "Reign of the Supermen",
    "media_type": "movie",
    "release_order": 74,
    "chronological_order": 77,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 537056,
    "poster_path": "https://image.tmdb.org/t/p/w500/eiVQORVyVuNNZHPAELuWtlXoQsD.jpg",
    "is_released": true,
    "release_date": "2019-07-19",
    "overview": "A mysterious new villain known only as Hush uses a gallery of villains to destroy Batman's crime-fighting career as well as Bruce Wayne's personal life, which has been further complicated by a relationship with Selina Kyle/Catwoman."
  },
  {
    "id": "dcu-75",
    "universe": "dcu",
    "title": "Lanterns (Season 1)",
    "media_type": "show",
    "release_order": 75,
    "chronological_order": 124,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 220026,
    "poster_path": "https://image.tmdb.org/t/p/w500/3uDmoeepe8WKr09DDDUwr714oWk.jpg",
    "is_released": false,
    "release_date": "2019-09-16",
    "overview": "Lanterns (Season 1)",
    "seasons": 1,
    "episodes": 32
  },
  {
    "id": "dcu-76",
    "universe": "dcu",
    "title": "Joker",
    "media_type": "movie",
    "release_order": 76,
    "chronological_order": 4,
    "phase_or_chapter": "The Joker Duology",
    "tmdb_id": 475557,
    "poster_path": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    "is_released": true,
    "release_date": "2019-10-01",
    "overview": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure."
  },
  {
    "id": "dcu-77",
    "universe": "dcu",
    "title": "Batman: Hush",
    "media_type": "movie",
    "release_order": 77,
    "chronological_order": 80,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 537055,
    "poster_path": "https://image.tmdb.org/t/p/w500/w1SBqj0fn1j72ST5i1jauWo3swT.jpg",
    "is_released": true,
    "release_date": "2019-10-04",
    "overview": "Witness the legendary origin of renowned Justice League member Wonder Woman as she fights for good with her sword and magic lasso. Equally strong in body, heart and will, she makes it her mission to help a troubled young girl enlisted by a deadly organization known as Villainy, Inc., whose criminal members have their sights set on invading Themyscira, Wonder Woman’s paradise home. The battle will be epic, because if there's one thing an Amazon knows, it’s war!"
  },
  {
    "id": "dcu-78",
    "universe": "dcu",
    "title": "Batwoman (Season 1)",
    "media_type": "show",
    "release_order": 78,
    "chronological_order": 76,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 89247,
    "poster_path": "https://image.tmdb.org/t/p/w500/reY4gJiMSNoL2THKJcPJk1E2KTq.jpg",
    "is_released": true,
    "release_date": "2019-10-06",
    "overview": "Kate Kane, armed with a passion for social justice and a flair for speaking her mind, soars onto the streets of Gotham as Batwoman, an out lesbian and highly trained street fighter primed to snuff out the failing city's criminal resurgence. But don't call her a hero yet. In a city desperate for a savior, Kate must overcome her own demons before embracing the call to be Gotham's symbol of hope",
    "seasons": 1,
    "episodes": 20
  },
  {
    "id": "dcu-79",
    "universe": "dcu",
    "title": "Supergirl (Season 5)",
    "media_type": "show",
    "release_order": 79,
    "chronological_order": 79,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62688,
    "poster_path": "https://image.tmdb.org/t/p/w500/vqK3KiosopXvZPWOugYh6RZki56.jpg",
    "is_released": true,
    "release_date": "2019-10-06",
    "overview": "Season four showed that truth, justice and the American way are stronger than fear and hate, as Supergirl stopped Lex Luthor’s anti-alien campaign with the power of the press, no cape required. As the world returns to normal, some things will never be the same now that Lena knows Kara's secret and the Monitor has arrived on Earth 38!",
    "seasons": 5,
    "episodes": 19
  },
  {
    "id": "dcu-80",
    "universe": "dcu",
    "title": "Black Lightning (Season 3)",
    "media_type": "show",
    "release_order": 80,
    "chronological_order": 81,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 71663,
    "poster_path": "https://image.tmdb.org/t/p/w500/90QFKG1QK7szgMIB2SxFADY1pvy.jpg",
    "is_released": true,
    "release_date": "2019-10-07",
    "overview": "Markovian attacks prompt the ASA to put Freeland on lockdown, Anissa adopts a new secret identity, and Green Light takes a toll on the Pierce family.",
    "seasons": 3,
    "episodes": 16
  },
  {
    "id": "dcu-81",
    "universe": "dcu",
    "title": "The Flash (Season 6)",
    "media_type": "show",
    "release_order": 81,
    "chronological_order": 83,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/qDntRDRs5XohN4ClcV2SH9WlzpI.jpg",
    "is_released": true,
    "release_date": "2019-10-08",
    "overview": "When Barry and Iris deal with loss of their daughter, the team faces their greatest threat yet - one that threatens to destroy all of Central City; Killer Frost has a brush with death that will change her relationship with Caitlin. Faced with the news of his impending death, Barry's resiliency suffers as he struggles to fight fate.",
    "seasons": 6,
    "episodes": 19
  },
  {
    "id": "dcu-82",
    "universe": "dcu",
    "title": "Arrow (Season 8)",
    "media_type": "show",
    "release_order": 82,
    "chronological_order": 84,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 1412,
    "poster_path": "https://image.tmdb.org/t/p/w500/gKG5QGz5Ngf8fgWpBsWtlg5L2SF.jpg",
    "is_released": true,
    "release_date": "2019-10-15",
    "overview": "Following the arrival of The Monitor, Oliver Queen left his home, his family, & his team behind to take on his most challenging battle yet, knowing the cost may be his life. But this time it's not just his city he's seeking to protect – it's the entire multiverse. Oliver's quest will send him on a journey where he is forced to confront the ultimate question: what is the true cost of being a hero?",
    "seasons": 8,
    "episodes": 10
  },
  {
    "id": "dcu-83",
    "universe": "dcu",
    "title": "DC's Legends of Tomorrow (Season 5)",
    "media_type": "show",
    "release_order": 83,
    "chronological_order": 86,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62643,
    "poster_path": "https://image.tmdb.org/t/p/w500/bSE5LzQegjaMDANeS3J9Oy8rTTX.jpg",
    "is_released": true,
    "release_date": "2020-01-14",
    "overview": "In season five, the Legends wrestle with changes to the timeline and themselves while trying to stop the \"encores\" of history's most infamous villains unleashed by Astra.",
    "seasons": 5,
    "episodes": 15
  },
  {
    "id": "dcu-84",
    "universe": "dcu",
    "title": "Birds of Prey",
    "media_type": "movie",
    "release_order": 84,
    "chronological_order": 88,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 495764,
    "poster_path": "https://image.tmdb.org/t/p/w500/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
    "is_released": true,
    "release_date": "2020-02-05",
    "overview": "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord."
  },
  {
    "id": "dcu-85",
    "universe": "dcu",
    "title": "Superman: Man of Tomorrow",
    "media_type": "movie",
    "release_order": 85,
    "chronological_order": 89,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 671583,
    "poster_path": "https://image.tmdb.org/t/p/w500/r2MfnMmFzGvRvjGVLIuyx3R16a6.jpg",
    "is_released": true,
    "release_date": "2020-07-31",
    "overview": "Nory and her best friend Reina enter the Sage Academy for Magical Studies, where Nory’s unconventional powers land her in a class for those with wonky, or “upside-down,” magic. Undaunted, Nory sets out to prove that that upside-down magic can be just as powerful as right-side-up."
  },
  {
    "id": "dcu-86",
    "universe": "dcu",
    "title": "Justice League Dark: Apokolips War",
    "media_type": "movie",
    "release_order": 86,
    "chronological_order": 87,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 618353,
    "poster_path": "https://image.tmdb.org/t/p/w500/k8Q9ulyRE8fkvZMkAM9LPYMKctb.jpg",
    "is_released": true,
    "release_date": "2020-10-13",
    "overview": "Tragedy strikes the Batman's life again when Robin Jason Todd tracks down his birth mother only to run afoul of the Joker. An adaptation of the 1988 comic book storyline of the same name."
  },
  {
    "id": "dcu-87",
    "universe": "dcu",
    "title": "Wonder Woman 1984",
    "media_type": "movie",
    "release_order": 87,
    "chronological_order": 8,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 464052,
    "poster_path": "https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
    "is_released": true,
    "release_date": "2020-12-16",
    "overview": "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy."
  },
  {
    "id": "dcu-88",
    "universe": "dcu",
    "title": "Batwoman (Season 2)",
    "media_type": "show",
    "release_order": 88,
    "chronological_order": 90,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 89247,
    "poster_path": "https://image.tmdb.org/t/p/w500/5qazdW8H20AlGpF1opHvGgKFPGD.jpg",
    "is_released": true,
    "release_date": "2021-01-17",
    "overview": "In season two, when Ryan Wilder first discovers Kate Kane's Batsuit, she has no idea how drastically her life is about to change. A sassy, smart lesbian with a difficult past, Ryan sees the suit as her chance to finally be powerful and no longer a victim as she survives in the tough streets of the city.",
    "seasons": 2,
    "episodes": 18
  },
  {
    "id": "dcu-89",
    "universe": "dcu",
    "title": "Black Lightning (Season 4)",
    "media_type": "show",
    "release_order": 89,
    "chronological_order": 93,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 71663,
    "poster_path": "https://image.tmdb.org/t/p/w500/h1xbvvO6oqchfLe6xh0yLNnQxeM.jpg",
    "is_released": true,
    "release_date": "2021-02-08",
    "overview": "Wracked with guilt, Jefferson vows to leave his hero days behind. But new threats to Freeland — and metas — draw all the Pierces back into the fray.",
    "seasons": 4,
    "episodes": 13
  },
  {
    "id": "dcu-90",
    "universe": "dcu",
    "title": "The Flash (Season 7)",
    "media_type": "show",
    "release_order": 90,
    "chronological_order": 95,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/lJA2RCMfsWoskqlQhXPSLFQGXEJ.jpg",
    "is_released": true,
    "release_date": "2021-03-02",
    "overview": "After a thrilling cliffhanger last season which saw Mirror Monarch victorious and still-at-large in Central City, The Flash must regroup in order to stop her and find a way to make contact with his missing wife, Iris West-Allen. With help from the rest of Team Flash, Barry will ultimately defeat Mirror Master. But in doing so, he’ll also unleash an even more powerful and devastating threat on Central City: one that threatens to tear his team—and his marriage—apart.",
    "seasons": 7,
    "episodes": 18
  },
  {
    "id": "dcu-91",
    "universe": "dcu",
    "title": "Zack Snyder's Justice League",
    "media_type": "movie",
    "release_order": 91,
    "chronological_order": 60,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 791373,
    "poster_path": "https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
    "is_released": true,
    "release_date": "2021-03-18",
    "overview": "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions."
  },
  {
    "id": "dcu-92",
    "universe": "dcu",
    "title": "Supergirl (Season 6)",
    "media_type": "show",
    "release_order": 92,
    "chronological_order": 97,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62688,
    "poster_path": "https://image.tmdb.org/t/p/w500/qq4TkhMymMKTajMX3zc7BL5zyo5.jpg",
    "is_released": true,
    "release_date": "2021-03-30",
    "overview": "Proving that friendship is every bit as important as truth and justice, Kara Danvers balances her work as a reporter for CatCo Worldwide Media with her role as Supergirl, keeping National City and the Earth safe from sinister threats. As she struggles to navigate her day job and friends, her heart soars as she takes to the skies as Supergirl.",
    "seasons": 6,
    "episodes": 20
  },
  {
    "id": "dcu-93",
    "universe": "dcu",
    "title": "Justice Society: World War II",
    "media_type": "movie",
    "release_order": 93,
    "chronological_order": 91,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 736069,
    "poster_path": "https://image.tmdb.org/t/p/w500/tOUJvmdjppmPYZOoykWmerSspMT.jpg",
    "is_released": true,
    "release_date": "2021-04-27",
    "overview": "When the Flash finds himself dropped into the middle of World War II, he joins forces with Wonder Woman and her top-secret team known as the Justice Society of America."
  },
  {
    "id": "dcu-94",
    "universe": "dcu",
    "title": "DC's Legends of Tomorrow (Season 6)",
    "media_type": "show",
    "release_order": 94,
    "chronological_order": 98,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62643,
    "poster_path": "https://image.tmdb.org/t/p/w500/3e1ja5IbJ8cl17vA5hHI5IX2wf4.jpg",
    "is_released": true,
    "release_date": "2021-05-02",
    "overview": "In season six, Waverider co-captains Sara Lance and Ava Sharpe have dealt with monsters, time anomalies, and most recently, villains from Hell, but this time they will face something even more challenging and bizarre ... space aliens! After one of their own is abducted by a ruthless alien, this new mission becomes personal. It will take more than the combined powers of John Constantine, Mick Rory, Nate Heywood, and brother-sister duo, Zari and Behrad Tarazi, to save the world for a sixth time.",
    "seasons": 6,
    "episodes": 15
  },
  {
    "id": "dcu-95",
    "universe": "dcu",
    "title": "Batman: The Long Halloween - Part One",
    "media_type": "movie",
    "release_order": 95,
    "chronological_order": 94,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 736073,
    "poster_path": "https://image.tmdb.org/t/p/w500/sR7gppb0YGjwLvE6Vnj6wYv5MnW.jpg",
    "is_released": true,
    "release_date": "2021-06-21",
    "overview": "Following a brutal series of murders taking place on Halloween, Thanksgiving, and Christmas, Gotham City's young vigilante known as the Batman sets out to pursue the mysterious serial killer alongside police officer James Gordon and district attorney Harvey Dent."
  },
  {
    "id": "dcu-96",
    "universe": "dcu",
    "title": "Batman: The Long Halloween - Part Two",
    "media_type": "movie",
    "release_order": 96,
    "chronological_order": 96,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 736074,
    "poster_path": "https://image.tmdb.org/t/p/w500/5X1n5q08mZ7NpNpxehMFODxfNYq.jpg",
    "is_released": true,
    "release_date": "2021-07-26",
    "overview": "As Gotham City's young vigilante, the Batman, struggles to pursue a brutal serial killer, district attorney Harvey Dent gets caught in a feud involving the criminal family of the Falcones."
  },
  {
    "id": "dcu-97",
    "universe": "dcu",
    "title": "The Suicide Squad",
    "media_type": "movie",
    "release_order": 97,
    "chronological_order": 92,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 436969,
    "poster_path": "https://image.tmdb.org/t/p/w500/q61qEyssk2ku3okWICKArlAdhBn.jpg",
    "is_released": true,
    "release_date": "2021-07-28",
    "overview": "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese."
  },
  {
    "id": "dcu-98",
    "universe": "dcu",
    "title": "Injustice",
    "media_type": "movie",
    "release_order": 98,
    "chronological_order": 99,
    "phase_or_chapter": "The Injustice Universe",
    "tmdb_id": 831405,
    "poster_path": "https://image.tmdb.org/t/p/w500/rzrSeqqpm1BwJ3tcTznztBtLLSD.jpg",
    "is_released": true,
    "release_date": "2021-10-09",
    "overview": "When Lois Lane is killed, an unhinged Superman decides to take control of the Earth. Determined to stop him, Batman creates a team of freedom-fighting heroes. But when superheroes go to war, can the world survive?"
  },
  {
    "id": "dcu-99",
    "universe": "dcu",
    "title": "DC's Legends of Tomorrow (Season 7)",
    "media_type": "show",
    "release_order": 99,
    "chronological_order": 100,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 62643,
    "poster_path": "https://image.tmdb.org/t/p/w500/AcEFDh272YVTR6B6zrrusk8BjJG.jpg",
    "is_released": true,
    "release_date": "2021-10-13",
    "overview": "In season seven, the Waverider gets blown up by a second Waverider…meaning the Legends are now trapped in 1925 Odessa, Texas! The only way to get home, and get payback on their mysterious new enemy, is to journey to New York City and find the forefather of time travel, Welsh inventor Dr. Gwyn Davies. Along the way, they pick up a familiar but shocking new teammate: a real-life, human Gideon, who’s knowledge of the timeline may be the key to solving all of the Legends’ problems.",
    "seasons": 7,
    "episodes": 13
  },
  {
    "id": "dcu-100",
    "universe": "dcu",
    "title": "Batwoman (Season 3)",
    "media_type": "show",
    "release_order": 100,
    "chronological_order": 101,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 89247,
    "poster_path": "https://image.tmdb.org/t/p/w500/pBpxKiitMuYXvtsXNSzya8DKKzV.jpg",
    "is_released": true,
    "release_date": "2021-10-13",
    "overview": "In season three, Ryan Wilder has shed her parole for the Batsuit and her van for the Batcave to carry out the legacy of Batwoman and protect Gotham's underserved communities. Her journey continues as she and the Bat Team focus on finding Batman's scattered trophies, a collection of objects seized from Gotham's most infamous villains, before they land in pernicious hands.",
    "seasons": 3,
    "episodes": 13
  },
  {
    "id": "dcu-101",
    "universe": "dcu",
    "title": "Young Justice: Phantoms (Season 4)",
    "media_type": "show",
    "release_order": 101,
    "chronological_order": 85,
    "phase_or_chapter": "Young Justice (Earth-16)",
    "tmdb_id": 33217,
    "poster_path": "https://image.tmdb.org/t/p/w500/uV75k4z66w7BSc10viWeXBK5yW5.jpg",
    "is_released": true,
    "release_date": "2021-10-16",
    "overview": "The original team—Nightwing, Aquaman, Superboy, Miss Martian, Tigress, Zatanna and Rocket—are back, leading a new generation of young heroes on a quest for justice across the Earth, the Solar System, the Galaxy and beyond. Between Order and Chaos, through time and space, life and death battles will be fought, won and lost. Who will rise? Who will fall? And who will haunt them forever?",
    "seasons": 4,
    "episodes": 26
  },
  {
    "id": "dcu-102",
    "universe": "dcu",
    "title": "Green Lantern: Beware My Power",
    "media_type": "movie",
    "release_order": 102,
    "chronological_order": 106,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 885110,
    "poster_path": "https://image.tmdb.org/t/p/w500/hMIQiwLpBfTfe3ZbRlNx4225Mgg.jpg",
    "is_released": true,
    "release_date": "2021-11-04",
    "overview": "In 16th-century Zazzau, now Zaria, Nigeria, Amina must utilize her military skills and tactics to defend her family's kingdom. Based on a true story."
  },
  {
    "id": "dcu-103",
    "universe": "dcu",
    "title": "The Flash (Season 8)",
    "media_type": "show",
    "release_order": 103,
    "chronological_order": 102,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/9Oayqj8PXBZIjl4K5UZeM3t9VVJ.jpg",
    "is_released": true,
    "release_date": "2021-11-16",
    "overview": "Six months after stopping the Godspeed War, Barry and Iris West-Allen are now at the top of their game—both in their careers as superhero and reporter and as a devoted couple. But when the powerful alien Despero unleashes near annihilation on Central City, The Flash and his team must once again defy impossible odds to save the day. But their victory is short-lived as two new threats rise from the ashes of \"Armageddon,\" one of which will unleash unforeseen horrors into the lives of Barry and his teammates... and change Team Flash forever.",
    "seasons": 8,
    "episodes": 20
  },
  {
    "id": "dcu-104",
    "universe": "dcu",
    "title": "Peacemaker (Season 1)",
    "media_type": "show",
    "release_order": 104,
    "chronological_order": 104,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 110492,
    "poster_path": "https://image.tmdb.org/t/p/w500/hE3LRZAY84fG19a18pzpkZERjTE.jpg",
    "is_released": true,
    "release_date": "2022-01-13",
    "overview": "After surviving being shot and then buried beneath a collapsing building, Peacemaker returns home only to realize that his freedom comes at a price. He is now part of Amanda Waller's new team fighting a mysterious new threat. Can he eliminate the threat without making things worse?",
    "seasons": 1,
    "episodes": 8
  },
  {
    "id": "dcu-105",
    "universe": "dcu",
    "title": "The Batman",
    "media_type": "movie",
    "release_order": 105,
    "chronological_order": 105,
    "phase_or_chapter": "The Reevesverse",
    "tmdb_id": 414906,
    "poster_path": "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    "is_released": true,
    "release_date": "2022-03-01",
    "overview": "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler."
  },
  {
    "id": "dcu-106",
    "universe": "dcu",
    "title": "Constantine: The House of Mystery",
    "media_type": "special",
    "release_order": 106,
    "chronological_order": 103,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 951470,
    "poster_path": "https://image.tmdb.org/t/p/w500/5HruMN0vvl84AqD7sCDXFNO4RhP.jpg",
    "is_released": true,
    "release_date": "2022-04-27",
    "overview": "After a failed sabotage mission, a trio of anti-apartheid freedom fighters ends up in a tense bank hostage situation. Based on a true story."
  },
  {
    "id": "dcu-107",
    "universe": "dcu",
    "title": "Constantine: City of Demons",
    "media_type": "movie",
    "release_order": 107,
    "chronological_order": 71,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 541134,
    "poster_path": "https://image.tmdb.org/t/p/w500/rSq6cq0LCcbro10jbEaPTEb3WmW.jpg",
    "is_released": true,
    "release_date": "2022-10-19",
    "overview": "Suspicious that her colleague is responsible for a series of mysterious patient deaths, a nurse risks her own life to uncover the truth."
  },
  {
    "id": "dcu-108",
    "universe": "dcu",
    "title": "Black Adam",
    "media_type": "movie",
    "release_order": 108,
    "chronological_order": 107,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 436270,
    "poster_path": "https://image.tmdb.org/t/p/w500/rCtreCr4xiYEWDQTebybolIh6Xe.jpg",
    "is_released": true,
    "release_date": "2022-10-19",
    "overview": "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world."
  },
  {
    "id": "dcu-109",
    "universe": "dcu",
    "title": "The Penguin (Season 1)",
    "media_type": "show",
    "release_order": 109,
    "chronological_order": 108,
    "phase_or_chapter": "The Reevesverse",
    "tmdb_id": 137437,
    "poster_path": "https://image.tmdb.org/t/p/w500/noRVimjdx6PwPBCVikhExYqogsX.jpg",
    "is_released": true,
    "release_date": "2022-12-14",
    "overview": "Jess Valenzuela, an adventurous 20-year-old Dreamer, along with the help of her friends, sets off on a journey to recover lost Pan-American treasures from around the globe, while uncovering family secrets along the way.",
    "seasons": 1,
    "episodes": 10
  },
  {
    "id": "dcu-110",
    "universe": "dcu",
    "title": "Legion of Super-Heroes",
    "media_type": "movie",
    "release_order": 110,
    "chronological_order": 110,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1003580,
    "poster_path": "https://image.tmdb.org/t/p/w500/3whQLi8RI7h2h2Si2KTDFJxfEcR.jpg",
    "is_released": true,
    "release_date": "2023-02-07",
    "overview": "Kara, devastated by the loss of Krypton, struggles to adjust to her new life on Earth. Her cousin, Superman, mentors her and suggests she leave their space-time to attend the Legion Academy in the 31st century, where she makes new friends and a new enemy: Brainiac 5. Meanwhile, she must contend with a mysterious group called the Dark Circle as it searches for a powerful weapon held in the Academy’s vault."
  },
  {
    "id": "dcu-111",
    "universe": "dcu",
    "title": "The Flash (Season 9)",
    "media_type": "show",
    "release_order": 111,
    "chronological_order": 109,
    "phase_or_chapter": "The Arrowverse",
    "tmdb_id": 60735,
    "poster_path": "https://image.tmdb.org/t/p/w500/lSIraXr6r1v5CvkjE7CjMcJZld0.jpg",
    "is_released": true,
    "release_date": "2023-02-08",
    "overview": "After defeating the Reverse Flash once and for all, Barry Allen and Iris West-Allen are reconnecting and growing closer than ever before. But when a deadly group of Rogues descend on Central City led by a powerful new threat, The Flash and his team must once again defy impossible odds to save the day. But as The Rogues are defeated, a deadly new adversary rises to challenge Barry Allen's heroic legacy. And in their greatest battle yet, Barry and Team Flash will be pushed to their limits, in order to save Central City one last time.",
    "seasons": 9,
    "episodes": 13
  },
  {
    "id": "dcu-112",
    "universe": "dcu",
    "title": "Creature Commandos (Season 1)",
    "media_type": "show",
    "release_order": 112,
    "chronological_order": 120,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 220025,
    "poster_path": "https://image.tmdb.org/t/p/w500/dznyYm7FCyccwIhf1eekilG6jPq.jpg",
    "is_released": true,
    "release_date": "2023-02-08",
    "overview": "Creature Commandos (Season 1)",
    "seasons": 1,
    "episodes": 20
  },
  {
    "id": "dcu-113",
    "universe": "dcu",
    "title": "Shazam! Fury of the Gods",
    "media_type": "movie",
    "release_order": 113,
    "chronological_order": 111,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 594767,
    "poster_path": "https://image.tmdb.org/t/p/w500/3GrRgt6CiLIUXUtoktcv1g2iwT5.jpg",
    "is_released": true,
    "release_date": "2023-03-15",
    "overview": "Billy Batson and his foster siblings, who transform into superheroes by saying \"Shazam!\", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world."
  },
  {
    "id": "dcu-114",
    "universe": "dcu",
    "title": "Suicide Squad: Hell to Pay",
    "media_type": "movie",
    "release_order": 114,
    "chronological_order": 66,
    "phase_or_chapter": "DC Animated Movie Universe",
    "tmdb_id": 493529,
    "poster_path": "https://image.tmdb.org/t/p/w500/v7UF7ypAqjsFZFdjksjQ7IUpXdn.jpg",
    "is_released": true,
    "release_date": "2023-03-23",
    "overview": "A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people."
  },
  {
    "id": "dcu-115",
    "universe": "dcu",
    "title": "The Flash",
    "media_type": "movie",
    "release_order": 115,
    "chronological_order": 113,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 298618,
    "poster_path": "https://image.tmdb.org/t/p/w500/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
    "is_released": true,
    "release_date": "2023-06-13",
    "overview": "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?"
  },
  {
    "id": "dcu-116",
    "universe": "dcu",
    "title": "Justice League: Warworld",
    "media_type": "movie",
    "release_order": 116,
    "chronological_order": 112,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1003581,
    "poster_path": "https://image.tmdb.org/t/p/w500/pHdSS5G3wDwJp6jWgMpbSjNiTbr.jpg",
    "is_released": true,
    "release_date": "2023-07-25",
    "overview": "Until now, the Justice League has been a loose association of superpowered individuals. But when they are swept away to Warworld, a place of unending brutal gladiatorial combat, Batman, Superman, Wonder Woman and the others must somehow unite to form an unbeatable resistance able to lead an entire planet to freedom."
  },
  {
    "id": "dcu-117",
    "universe": "dcu",
    "title": "Blue Beetle",
    "media_type": "movie",
    "release_order": 117,
    "chronological_order": 114,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 565770,
    "poster_path": "https://image.tmdb.org/t/p/w500/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
    "is_released": true,
    "release_date": "2023-08-16",
    "overview": "Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab."
  },
  {
    "id": "dcu-118",
    "universe": "dcu",
    "title": "Aquaman and the Lost Kingdom",
    "media_type": "movie",
    "release_order": 118,
    "chronological_order": 115,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 572802,
    "poster_path": "https://image.tmdb.org/t/p/w500/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
    "is_released": true,
    "release_date": "2023-12-20",
    "overview": "Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Arthur (Aquaman) forges an alliance with his imprisoned brother. They must protect the kingdom."
  },
  {
    "id": "dcu-119",
    "universe": "dcu",
    "title": "Justice League: Crisis on Infinite Earths Part One",
    "media_type": "movie",
    "release_order": 119,
    "chronological_order": 116,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1155089,
    "poster_path": "https://image.tmdb.org/t/p/w500/mcRVsjMbhFstRK9z2oGRHiIvulr.jpg",
    "is_released": true,
    "release_date": "2024-01-08",
    "overview": "Death is coming. Worse than death: oblivion. Not just for our Earth, but for everyone, everywhere, in every universe! Against this ultimate destruction, the mysterious Monitor has gathered the greatest team of Super Heroes ever assembled. But what can the combined might of Superman, Wonder Woman, Batman, The Flash, Green Lantern and hundreds of Super Heroes from multiple Earths even do to save all of reality from an unstoppable antimatter armageddon?!"
  },
  {
    "id": "dcu-120",
    "universe": "dcu",
    "title": "Justice League: Crisis on Infinite Earths Part Two",
    "media_type": "movie",
    "release_order": 120,
    "chronological_order": 118,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1209288,
    "poster_path": "https://image.tmdb.org/t/p/w500/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg",
    "is_released": true,
    "release_date": "2024-04-22",
    "overview": "An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?"
  },
  {
    "id": "dcu-121",
    "universe": "dcu",
    "title": "Justice League: Crisis on Infinite Earths Part Three",
    "media_type": "movie",
    "release_order": 121,
    "chronological_order": 119,
    "phase_or_chapter": "The Tomorrowverse",
    "tmdb_id": 1209290,
    "poster_path": "https://image.tmdb.org/t/p/w500/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg",
    "is_released": true,
    "release_date": "2024-07-15",
    "overview": "Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?"
  },
  {
    "id": "dcu-122",
    "universe": "dcu",
    "title": "The Batman Part II",
    "media_type": "movie",
    "release_order": 122,
    "chronological_order": 117,
    "phase_or_chapter": "The Reevesverse",
    "tmdb_id": 974950,
    "poster_path": "https://image.tmdb.org/t/p/w500/7seqaCaaXDNUHOx4DqwpoOH8pPa.jpg",
    "is_released": false,
    "release_date": "2024-08-21",
    "overview": "Rita, an underrated lawyer working for a large law firm more interested in getting criminals out of jail than bringing them to justice, is hired by the leader of a criminal organization."
  },
  {
    "id": "dcu-123",
    "universe": "dcu",
    "title": "Joker: Folie à Deux",
    "media_type": "movie",
    "release_order": 123,
    "chronological_order": 6,
    "phase_or_chapter": "The Joker Duology",
    "tmdb_id": 889737,
    "poster_path": "https://image.tmdb.org/t/p/w500/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg",
    "is_released": true,
    "release_date": "2024-10-01",
    "overview": "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him."
  },
  {
    "id": "dcu-124",
    "universe": "dcu",
    "title": "Superman (2025)",
    "media_type": "movie",
    "release_order": 124,
    "chronological_order": 121,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1064213,
    "poster_path": "https://image.tmdb.org/t/p/w500/cgXk2tNYhJZLXdBDO5DidAVzQ82.jpg",
    "is_released": false,
    "release_date": "2024-10-14",
    "overview": "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled."
  },
  {
    "id": "dcu-125",
    "universe": "dcu",
    "title": "Peacemaker (Season 2)",
    "media_type": "show",
    "release_order": 125,
    "chronological_order": 122,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 110492,
    "poster_path": "https://image.tmdb.org/t/p/w500/2Wv0Zinc9nQ6ktL10Z9ckk2wjyZ.jpg",
    "is_released": false,
    "release_date": "2025-08-21",
    "overview": "Following the exposure of Project Butterfly and the disbandment of Task Force X, the 11th Street Kids grapple with new identities, new friendships, and new rivalries. For Peacemaker, this means reconciling his past with his newfound sense of purpose — here and in an alternate dimension. Meanwhile, Rick Flag Sr. reappears as the director of A.R.G.U.S., focused on controlling metahumans and avenging the death of his son at the hands of Peacemaker.",
    "seasons": 2,
    "episodes": 8
  },
  {
    "id": "dcu-126",
    "universe": "dcu",
    "title": "Supergirl: Woman of Tomorrow",
    "media_type": "movie",
    "release_order": 126,
    "chronological_order": 125,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1084242,
    "poster_path": "https://image.tmdb.org/t/p/w500/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg",
    "is_released": false,
    "release_date": "2025-11-26",
    "overview": "After cracking the biggest case in Zootopia's history, rookie cops Judy Hopps and Nick Wilde find themselves on the twisting trail of a great mystery when Gary De'Snake arrives and turns the animal metropolis upside down. To crack the case, Judy and Nick must go undercover to unexpected new parts of town, where their growing partnership is tested like never before."
  },
  {
    "id": "dcu-127",
    "universe": "dcu",
    "title": "Swamp Thing",
    "media_type": "movie",
    "release_order": 127,
    "chronological_order": 128,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1084244,
    "poster_path": "https://image.tmdb.org/t/p/w500/sfQtVlIHljToOwYjhe21KPGzZWK.jpg",
    "is_released": false,
    "release_date": "2026-06-17",
    "overview": "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime."
  },
  {
    "id": "dcu-128",
    "universe": "dcu",
    "title": "Clayface",
    "media_type": "movie",
    "release_order": 128,
    "chronological_order": 126,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1400940,
    "poster_path": "https://image.tmdb.org/t/p/w500/5jCpQnWPikggmQZoDp1eAi6BI6w.jpg",
    "is_released": false,
    "release_date": "2026-10-21",
    "overview": "Follow the terrifying descent into hell of a promising Hollywood actor who has become a monster driven by revenge, exploring the loss of identity and humanity, the ravages of toxic love and the dark side of scientific ambition."
  },
  {
    "id": "dcu-129",
    "universe": "dcu",
    "title": "The Brave and the Bold",
    "media_type": "movie",
    "release_order": 129,
    "chronological_order": 127,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1081004,
    "poster_path": "https://image.tmdb.org/t/p/w500/yrp5UKKMcRfK68zT74tlDxdsrOI.jpg",
    "is_released": false,
    "release_date": "2027-01-01",
    "overview": "The story of Damian Wayne, who was raised as a little murderer and assassin, and Batman's son that he didn’t know existed for the first eight to ten years of his life."
  },
  {
    "id": "dcu-130",
    "universe": "dcu",
    "title": "Teen Titans",
    "media_type": "movie",
    "release_order": 130,
    "chronological_order": 130,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": null,
    "poster_path": "https://image.tmdb.org/t/p/w500/yNzj00TzH4gW3N6Q8T4P5n6Q4A7.jpg",
    "is_released": false,
    "release_date": "2028-01-01",
    "overview": "Live-action DCU adaptation focusing on the iconic team of young heroes led by Robin."
  },
  {
    "id": "dcu-131",
    "universe": "dcu",
    "title": "Blue Beetle (Animated)",
    "media_type": "show",
    "release_order": 131,
    "chronological_order": 131,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": null,
    "poster_path": "https://image.tmdb.org/t/p/w500/mXLOHHc1Zeuwsl4xYKjKh2280ne.jpg",
    "is_released": false,
    "release_date": "2028-06-01",
    "overview": "Animated DCU series continuing the adventures of Jaime Reyes and the Scarab.",
    "seasons": 1
  }
];
