import { FranchiseMedia } from "../types";

export const DCU_SEED_DATA: FranchiseMedia[] = [
  {
    "id": "dcu-4",
    "universe": "dcu",
    "title": "Wonder Woman",
    "media_type": "movie",
    "release_order": 4,
    "chronological_order": 1,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 297762,
    "poster_path": "https://image.tmdb.org/t/p/w500/v4ncgZjG2Zu8ZW5al1vIZTsSjqX.jpg",
    "is_released": true,
    "release_date": "2017-05-30",
    "overview": "An Amazon princess comes to the world of Man in the grips of the First World War to confront the forces of evil and bring an end to human conflict."
  },
  {
    "id": "dcu-9",
    "universe": "dcu",
    "title": "Wonder Woman 1984",
    "media_type": "movie",
    "release_order": 9,
    "chronological_order": 2,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 464052,
    "poster_path": "https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
    "is_released": true,
    "release_date": "2020-12-16",
    "overview": "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy."
  },
  {
    "id": "dcu-1",
    "universe": "dcu",
    "title": "Man of Steel",
    "media_type": "movie",
    "release_order": 1,
    "chronological_order": 3,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 49521,
    "poster_path": "https://image.tmdb.org/t/p/w500/8GFtkImmK0K1VaUChR0n9O61CFU.jpg",
    "is_released": true,
    "release_date": "2013-06-12",
    "overview": "A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind."
  },
  {
    "id": "dcu-2",
    "universe": "dcu",
    "title": "Batman v Superman: Dawn of Justice",
    "media_type": "movie",
    "release_order": 2,
    "chronological_order": 4,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 209112,
    "poster_path": "https://image.tmdb.org/t/p/w500/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
    "is_released": true,
    "release_date": "2016-03-23",
    "overview": "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before."
  },
  {
    "id": "dcu-3",
    "universe": "dcu",
    "title": "Suicide Squad",
    "media_type": "movie",
    "release_order": 3,
    "chronological_order": 5,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 297761,
    "poster_path": "https://image.tmdb.org/t/p/w500/sk3FZgh3sRrmr8vyhaitNobMcfh.jpg",
    "is_released": true,
    "release_date": "2016-08-03",
    "overview": "From DC Comics comes the Suicide Squad, an antihero team of incarcerated supervillains who act as deniable assets for the United States government, undertaking high-risk black ops missions in exchange for commuted prison sentences."
  },
  {
    "id": "dcu-5",
    "universe": "dcu",
    "title": "Zack Snyder's Justice League",
    "media_type": "movie",
    "release_order": 5,
    "chronological_order": 6,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 791373,
    "poster_path": "https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
    "is_released": true,
    "release_date": "2021-03-18",
    "overview": "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions."
  },
  {
    "id": "dcu-6",
    "universe": "dcu",
    "title": "Aquaman",
    "media_type": "movie",
    "release_order": 6,
    "chronological_order": 7,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 297802,
    "poster_path": "https://image.tmdb.org/t/p/w500/ufl63EFcc5XpByEV2Ecdw6WJZAI.jpg",
    "is_released": true,
    "release_date": "2018-12-07",
    "overview": "Half-human, half-Atlantean Arthur Curry is taken on the journey of his lifetime to discover if he is worth of being a king."
  },
  {
    "id": "dcu-7",
    "universe": "dcu",
    "title": "Shazam!",
    "media_type": "movie",
    "release_order": 7,
    "chronological_order": 8,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 287947,
    "poster_path": "https://image.tmdb.org/t/p/w500/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
    "is_released": true,
    "release_date": "2019-03-29",
    "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word."
  },
  {
    "id": "dcu-8",
    "universe": "dcu",
    "title": "Birds of Prey",
    "media_type": "movie",
    "release_order": 8,
    "chronological_order": 9,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 495764,
    "poster_path": "https://image.tmdb.org/t/p/w500/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
    "is_released": true,
    "release_date": "2020-02-05",
    "overview": "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord."
  },
  {
    "id": "dcu-10",
    "universe": "dcu",
    "title": "The Suicide Squad",
    "media_type": "movie",
    "release_order": 10,
    "chronological_order": 10,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 436969,
    "poster_path": "https://image.tmdb.org/t/p/w500/q61qEyssk2ku3okWICKArlAdhBn.jpg",
    "is_released": true,
    "release_date": "2021-07-28",
    "overview": "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese."
  },
  {
    "id": "dcu-11",
    "universe": "dcu",
    "title": "Peacemaker (Season 1)",
    "media_type": "show",
    "release_order": 11,
    "chronological_order": 11,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 110492,
    "poster_path": "https://image.tmdb.org/t/p/w500/eYzbGcYnOUlvj2fa76pTgIXogd7.jpg",
    "is_released": true,
    "release_date": "2022-01-13",
    "overview": "The continuing story of Peacemaker, a vainglorious superhero/supervillain who believes in peace at any cost — no matter how many people he has to kill. After a miraculous recovery from his duel with Bloodsport, Peacemaker soon discovers that his freedom comes at a price."
  },
  {
    "id": "dcu-12",
    "universe": "dcu",
    "title": "Black Adam",
    "media_type": "movie",
    "release_order": 12,
    "chronological_order": 12,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 436270,
    "poster_path": "https://image.tmdb.org/t/p/w500/rCtreCr4xiYEWDQTebybolIh6Xe.jpg",
    "is_released": true,
    "release_date": "2022-10-19",
    "overview": "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world."
  },
  {
    "id": "dcu-13",
    "universe": "dcu",
    "title": "Shazam! Fury of the Gods",
    "media_type": "movie",
    "release_order": 13,
    "chronological_order": 13,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 594767,
    "poster_path": "https://image.tmdb.org/t/p/w500/3GrRgt6CiLIUXUtoktcv1g2iwT5.jpg",
    "is_released": true,
    "release_date": "2023-03-15",
    "overview": "Billy Batson and his foster siblings, who transform into superheroes by saying \"Shazam!\", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world."
  },
  {
    "id": "dcu-14",
    "universe": "dcu",
    "title": "The Flash",
    "media_type": "movie",
    "release_order": 14,
    "chronological_order": 14,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 298618,
    "poster_path": "https://image.tmdb.org/t/p/w500/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
    "is_released": true,
    "release_date": "2023-06-13",
    "overview": "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?"
  },
  {
    "id": "dcu-15",
    "universe": "dcu",
    "title": "Blue Beetle",
    "media_type": "movie",
    "release_order": 15,
    "chronological_order": 15,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 565770,
    "poster_path": "https://image.tmdb.org/t/p/w500/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
    "is_released": true,
    "release_date": "2023-08-16",
    "overview": "Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab."
  },
  {
    "id": "dcu-16",
    "universe": "dcu",
    "title": "Aquaman and the Lost Kingdom",
    "media_type": "movie",
    "release_order": 16,
    "chronological_order": 16,
    "phase_or_chapter": "DCEU Era",
    "tmdb_id": 572802,
    "poster_path": "https://image.tmdb.org/t/p/w500/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
    "is_released": true,
    "release_date": "2023-12-20",
    "overview": "Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Arthur (Aquaman) forges an alliance with his imprisoned brother. They must protect the kingdom."
  },
  {
    "id": "dcu-17",
    "universe": "dcu",
    "title": "Creature Commandos",
    "media_type": "show",
    "release_order": 17,
    "chronological_order": 17,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 219109,
    "poster_path": "https://image.tmdb.org/t/p/w500/hCSH5KvSqShWXhFiXr88wtJXwlO.jpg",
    "is_released": true,
    "release_date": "2023-09-25",
    "overview": "\"Crossed Paths\" tells a history about seven friends who met in their youth at an English course meet again 25 years later; Lara, Taís, Helena, Adriana, Renée, Natália and Carol, each of them has a different personality and origin, but they share a deep affection."
  },
  {
    "id": "dcu-18",
    "universe": "dcu",
    "title": "Superman",
    "media_type": "movie",
    "release_order": 18,
    "chronological_order": 18,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 539972,
    "poster_path": "https://image.tmdb.org/t/p/w500/ombsmhYUqkhpnZlhDY1aqtBaiv4.jpg",
    "is_released": true,
    "release_date": "2025-07-11",
    "overview": "Follows the titular superhero as he reconciles his heritage with his human upbringing. He is the embodiment of truth, justice and the American way in a world that views kindness as old-fashioned."
  },
  {
    "id": "dcu-19",
    "universe": "dcu",
    "title": "Peacemaker (Season 2)",
    "media_type": "show",
    "release_order": 19,
    "chronological_order": 19,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 110492,
    "poster_path": "https://image.tmdb.org/t/p/w500/eYzbGcYnOUlvj2fa76pTgIXogd7.jpg",
    "is_released": true,
    "release_date": "2025-08-01",
    "overview": "Peacemaker and his ragtag team return for the second season under James Gunn's DCU."
  },
  {
    "id": "dcu-20",
    "universe": "dcu",
    "title": "Supergirl: Woman of Tomorrow",
    "media_type": "movie",
    "release_order": 20,
    "chronological_order": 20,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1084199,
    "poster_path": "https://image.tmdb.org/t/p/w500/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg",
    "is_released": false,
    "release_date": "2026-06-26",
    "overview": "Kara Zor-El travels across the cosmos with Krypto to help a young alien girl seek vengeance for her destroyed world."
  },
  {
    "id": "dcu-21",
    "universe": "dcu",
    "title": "Lanterns",
    "media_type": "show",
    "release_order": 21,
    "chronological_order": 21,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 219113,
    "poster_path": "https://image.tmdb.org/t/p/w500/bZledG7Q3TyMu57grHO6ZvCKjpG.jpg",
    "is_released": false,
    "release_date": "2026-09-01",
    "overview": "Intergalactic cops Hal Jordan and John Stewart investigate a dark mystery on Earth in this gritty detective HBO series."
  },
  {
    "id": "dcu-22",
    "universe": "dcu",
    "title": "The Brave and the Bold",
    "media_type": "movie",
    "release_order": 22,
    "chronological_order": 22,
    "phase_or_chapter": "Chapter 1: Gods & Monsters",
    "tmdb_id": 1084201,
    "poster_path": null,
    "is_released": false,
    "release_date": "2027-01-01",
    "overview": "The DCU introduction of Batman and his son Damian Wayne as Robin."
  },
  {
    "id": "dcu-23",
    "universe": "dcu",
    "title": "Joker",
    "media_type": "movie",
    "release_order": 23,
    "chronological_order": 23,
    "phase_or_chapter": "Elseworlds",
    "tmdb_id": 475557,
    "poster_path": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    "is_released": true,
    "release_date": "2019-10-01",
    "overview": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure."
  },
  {
    "id": "dcu-24",
    "universe": "dcu",
    "title": "The Batman",
    "media_type": "movie",
    "release_order": 24,
    "chronological_order": 24,
    "phase_or_chapter": "Elseworlds",
    "tmdb_id": 414906,
    "poster_path": "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    "is_released": true,
    "release_date": "2022-03-01",
    "overview": "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler."
  },
  {
    "id": "dcu-25",
    "universe": "dcu",
    "title": "The Penguin",
    "media_type": "show",
    "release_order": 25,
    "chronological_order": 25,
    "phase_or_chapter": "Elseworlds",
    "tmdb_id": 137437,
    "poster_path": "https://image.tmdb.org/t/p/w500/yrp5UKKMcRfK68zT74tlDxdsrOI.jpg",
    "is_released": true,
    "release_date": "2024-09-19",
    "overview": "Following the events of The Batman, Oz Cobb seeks to seize control of the criminal underworld in Gotham City."
  },
  {
    "id": "dcu-26",
    "universe": "dcu",
    "title": "Joker: Folie à Deux",
    "media_type": "movie",
    "release_order": 26,
    "chronological_order": 26,
    "phase_or_chapter": "Elseworlds",
    "tmdb_id": 889737,
    "poster_path": "https://image.tmdb.org/t/p/w500/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg",
    "is_released": true,
    "release_date": "2024-10-01",
    "overview": "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him."
  },
  {
    "id": "dcu-27",
    "universe": "dcu",
    "title": "The Batman Part II",
    "media_type": "movie",
    "release_order": 27,
    "chronological_order": 27,
    "phase_or_chapter": "Elseworlds",
    "tmdb_id": 974950,
    "poster_path": "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    "is_released": false,
    "release_date": "2026-10-02",
    "overview": "The second chapter of Matt Reeves' epic Batman crime saga starring Robert Pattinson."
  }
];
