import { FranchiseMedia } from "../types";

export const MCU_SEED_DATA: FranchiseMedia[] = [
  {
    "id": "marvel-1",
    "universe": "mcu",
    "title": "Iron Man",
    "media_type": "movie",
    "release_order": 1,
    "chronological_order": 32,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 1726,
    "poster_path": "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    "is_released": true,
    "release_date": "2008-01-01",
    "overview": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil."
  },
  {
    "id": "marvel-2",
    "universe": "mcu",
    "title": "The Incredible Hulk",
    "media_type": "movie",
    "release_order": 2,
    "chronological_order": 34,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 1724,
    "poster_path": "https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
    "is_released": true,
    "release_date": "2008-01-01",
    "overview": "Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him."
  },
  {
    "id": "marvel-3",
    "universe": "mcu",
    "title": "Iron Man 2",
    "media_type": "movie",
    "release_order": 3,
    "chronological_order": 33,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 10138,
    "poster_path": "https://image.tmdb.org/t/p/w500/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
    "is_released": true,
    "release_date": "2010-01-01",
    "overview": "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful madman."
  },
  {
    "id": "marvel-4",
    "universe": "mcu",
    "title": "Thor",
    "media_type": "movie",
    "release_order": 4,
    "chronological_order": 37,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 10195,
    "poster_path": "https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
    "is_released": true,
    "release_date": "2011-01-01",
    "overview": "Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - is cast down to Earth."
  },
  {
    "id": "marvel-5",
    "universe": "mcu",
    "title": "Captain America: The First Avenger",
    "media_type": "movie",
    "release_order": 5,
    "chronological_order": 1,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 1771,
    "poster_path": "https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg",
    "is_released": true,
    "release_date": "2011-01-01",
    "overview": "During World War II, Steve Rogers is transformed into the super-soldier Captain America."
  },
  {
    "id": "marvel-6",
    "universe": "mcu",
    "title": "The Consultant",
    "media_type": "special",
    "release_order": 6,
    "chronological_order": 35,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 76122,
    "poster_path": "https://image.tmdb.org/t/p/w500/xqNLXUUvBnfVk6m3QFGGU0Grgs7.jpg",
    "is_released": true,
    "release_date": "2011-01-01",
    "overview": "Agents Coulson and Sitwell plot how to prevent Emil Blonsky from being released into the Avengers Initiative."
  },
  {
    "id": "marvel-7",
    "universe": "mcu",
    "title": "A Funny Thing Happened on the Way to Thor's Hammer",
    "media_type": "special",
    "release_order": 7,
    "chronological_order": 36,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 76535,
    "poster_path": "https://image.tmdb.org/t/p/w500/njrOqsmFH4pxBrhcoslqLfw2OGk.jpg",
    "is_released": true,
    "release_date": "2011-01-01",
    "overview": "Agent Phil Coulson stops at a convenience store on his way to New Mexico and handles a robbery."
  },
  {
    "id": "marvel-8",
    "universe": "mcu",
    "title": "The Avengers",
    "media_type": "movie",
    "release_order": 8,
    "chronological_order": 38,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 24428,
    "poster_path": "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    "is_released": true,
    "release_date": "2012-01-01",
    "overview": "Earth's Mightiest Heroes must come together and learn to fight as a team to stop Loki and an alien army."
  },
  {
    "id": "marvel-9",
    "universe": "mcu",
    "title": "Item 47",
    "media_type": "special",
    "release_order": 9,
    "chronological_order": 4,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 119569,
    "poster_path": "https://image.tmdb.org/t/p/w500/hnSxG8clwLuAXEkp9emc8HCUcHD.jpg",
    "is_released": true,
    "release_date": "2012-01-01",
    "overview": "A down-on-their-luck couple finds a discarded Chitauri gun following the Battle of New York."
  },
  {
    "id": "marvel-10",
    "universe": "mcu",
    "title": "Iron Man 3",
    "media_type": "movie",
    "release_order": 10,
    "chronological_order": 39,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 68721,
    "poster_path": "https://image.tmdb.org/t/p/w500/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg",
    "is_released": true,
    "release_date": "2013-01-01",
    "overview": "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding."
  },
  {
    "id": "marvel-11",
    "universe": "mcu",
    "title": "Agent Carter",
    "media_type": "special",
    "release_order": 11,
    "chronological_order": 41,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 211387,
    "poster_path": "https://image.tmdb.org/t/p/w500/u3vK3K9z4w63G3WzJkYwQf4H6c7.jpg",
    "is_released": true,
    "release_date": "2013-01-01",
    "overview": "Peggy Carter undertakes a solo field mission to retrieve the mysterious Zodiac key."
  },
  {
    "id": "marvel-12",
    "universe": "mcu",
    "title": "Thor: The Dark World",
    "media_type": "movie",
    "release_order": 12,
    "chronological_order": 42,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 76338,
    "poster_path": "https://image.tmdb.org/t/p/w500/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
    "is_released": true,
    "release_date": "2013-01-01",
    "overview": "Thor fights to restore order across the cosmos as an ancient race led by Malekith returns."
  },
  {
    "id": "marvel-13",
    "universe": "mcu",
    "title": "All Hail the King",
    "media_type": "special",
    "release_order": 13,
    "chronological_order": 44,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 253980,
    "poster_path": "https://image.tmdb.org/t/p/w500/f877h89kE9L1yX4K0u7fB6FwQvB.jpg",
    "is_released": true,
    "release_date": "2014-01-01",
    "overview": "Trevor Slattery is enjoying his newfound fame behind bars at Seagate Prison until an unexpected visitor arrives."
  },
  {
    "id": "marvel-14",
    "universe": "mcu",
    "title": "Captain America: The Winter Soldier",
    "media_type": "movie",
    "release_order": 14,
    "chronological_order": 46,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 100402,
    "poster_path": "https://image.tmdb.org/t/p/w500/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
    "is_released": true,
    "release_date": "2014-01-01",
    "overview": "Steve Rogers teams up with Natasha Romanoff and Sam Wilson to battle a powerful enemy within S.H.I.E.L.D."
  },
  {
    "id": "marvel-15",
    "universe": "mcu",
    "title": "Guardians of the Galaxy",
    "media_type": "movie",
    "release_order": 15,
    "chronological_order": 48,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 118340,
    "poster_path": "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    "is_released": true,
    "release_date": "2014-01-01",
    "overview": "An unruly band of galactic misfits must rally together to stop a cosmic warrior from cleansing the universe."
  },
  {
    "id": "marvel-16",
    "universe": "mcu",
    "title": "Avengers: Age of Ultron",
    "media_type": "movie",
    "release_order": 16,
    "chronological_order": 54,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 99861,
    "poster_path": "https://image.tmdb.org/t/p/w500/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
    "is_released": true,
    "release_date": "2015-01-01",
    "overview": "When Tony Stark jumpstarts a dormant peacekeeping program, things go awry and the Avengers face Ultron."
  },
  {
    "id": "marvel-17",
    "universe": "mcu",
    "title": "Ant-Man",
    "media_type": "movie",
    "release_order": 17,
    "chronological_order": 55,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 102899,
    "poster_path": "https://image.tmdb.org/t/p/w500/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
    "is_released": true,
    "release_date": "2015-01-01",
    "overview": "Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang becomes Ant-Man."
  },
  {
    "id": "marvel-18",
    "universe": "mcu",
    "title": "Captain America: Civil War",
    "media_type": "movie",
    "release_order": 18,
    "chronological_order": 62,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 271110,
    "poster_path": "https://image.tmdb.org/t/p/w500/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
    "is_released": true,
    "release_date": "2016-01-01",
    "overview": "Political pressure mounts to install a system of accountability when the actions of the Avengers lead to collateral damage."
  },
  {
    "id": "marvel-19",
    "universe": "mcu",
    "title": "Doctor Strange",
    "media_type": "movie",
    "release_order": 19,
    "chronological_order": 68,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 284052,
    "poster_path": "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
    "is_released": true,
    "release_date": "2016-01-01",
    "overview": "After a horrific car crash robs him of his hands, brilliant neurosurgeon Stephen Strange learns the mystic arts."
  },
  {
    "id": "marvel-20",
    "universe": "mcu",
    "title": "Guardians of the Galaxy Vol. 2",
    "media_type": "movie",
    "release_order": 20,
    "chronological_order": 50,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 283995,
    "poster_path": "https://image.tmdb.org/t/p/w500/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
    "is_released": true,
    "release_date": "2017-01-01",
    "overview": "The Guardians must fight to keep their newfound family together as they unravel the mystery of Peter Quill's true parentage."
  },
  {
    "id": "marvel-21",
    "universe": "mcu",
    "title": "Spider-Man: Homecoming",
    "media_type": "movie",
    "release_order": 21,
    "chronological_order": 65,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 315635,
    "poster_path": "https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
    "is_released": true,
    "release_date": "2017-01-01",
    "overview": "Following the events of Captain America: Civil War, Peter Parker navigates high school life while fighting the Vulture."
  },
  {
    "id": "marvel-22",
    "universe": "mcu",
    "title": "Thor: Ragnarok",
    "media_type": "movie",
    "release_order": 22,
    "chronological_order": 72,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 284053,
    "poster_path": "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    "is_released": true,
    "release_date": "2017-01-01",
    "overview": "Thor is imprisoned on the other side of the universe and must race against time to stop Hela from destroying Asgard."
  },
  {
    "id": "marvel-23",
    "universe": "mcu",
    "title": "Black Panther",
    "media_type": "movie",
    "release_order": 23,
    "chronological_order": 64,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 284054,
    "poster_path": "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    "is_released": true,
    "release_date": "2018-01-01",
    "overview": "T'Challa returns home to the isolated, technologically advanced African nation of Wakanda to serve as its new king."
  },
  {
    "id": "marvel-24",
    "universe": "mcu",
    "title": "Avengers: Infinity War",
    "media_type": "movie",
    "release_order": 24,
    "chronological_order": 90,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 299536,
    "poster_path": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    "is_released": true,
    "release_date": "2018-01-01",
    "overview": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos."
  },
  {
    "id": "marvel-25",
    "universe": "mcu",
    "title": "Ant-Man and the Wasp",
    "media_type": "movie",
    "release_order": 25,
    "chronological_order": 89,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 363088,
    "poster_path": "https://image.tmdb.org/t/p/w500/cFQEO687n1K6umXbInzocxcnAQz.jpg",
    "is_released": true,
    "release_date": "2018-01-01",
    "overview": "Scott Lang grapples with the consequences of his choices as both a superhero and a father as he teams with Hope van Dyne."
  },
  {
    "id": "marvel-26",
    "universe": "mcu",
    "title": "Captain Marvel",
    "media_type": "movie",
    "release_order": 26,
    "chronological_order": 10,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 299537,
    "poster_path": "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
    "is_released": true,
    "release_date": "2019-01-01",
    "overview": "The story follows Carol Danvers as she becomes one of the universe's most powerful heroes when galactic war reaches Earth."
  },
  {
    "id": "marvel-27",
    "universe": "mcu",
    "title": "Avengers: Endgame",
    "media_type": "movie",
    "release_order": 27,
    "chronological_order": 96,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 299534,
    "poster_path": "https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    "is_released": true,
    "release_date": "2019-01-01",
    "overview": "After the devastating events of Infinity War, the surviving Avengers assemble once more to reverse Thanos's actions."
  },
  {
    "id": "marvel-28",
    "universe": "mcu",
    "title": "Spider-Man: Far From Home",
    "media_type": "movie",
    "release_order": 28,
    "chronological_order": 102,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 429617,
    "poster_path": "https://image.tmdb.org/t/p/w500/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    "is_released": true,
    "release_date": "2019-01-01",
    "overview": "Peter Parker and his friends go on a summer trip to Europe, where Peter finds himself helping Nick Fury against Elementals."
  },
  {
    "id": "marvel-29",
    "universe": "mcu",
    "title": "WandaVision (Season 1)",
    "media_type": "show",
    "release_order": 29,
    "chronological_order": 99,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 85271,
    "poster_path": "https://image.tmdb.org/t/p/w500/ijWWwINc8h71NQ8j1LTJMFSj5wr.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "Wanda Maximoff and Vision are living idealized suburban lives in Westview until they suspect everything is not as it seems."
  },
  {
    "id": "marvel-30",
    "universe": "mcu",
    "title": "The Falcon and the Winter Soldier (Season 1)",
    "media_type": "show",
    "release_order": 30,
    "chronological_order": 101,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 88396,
    "poster_path": "https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "Sam Wilson and Bucky Barnes team up on a global adventure that tests their abilities and their patience."
  },
  {
    "id": "marvel-31",
    "universe": "mcu",
    "title": "Loki (Season 1)",
    "media_type": "show",
    "release_order": 31,
    "chronological_order": 97,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 84958,
    "poster_path": "https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after Avengers: Endgame."
  },
  {
    "id": "marvel-32",
    "universe": "mcu",
    "title": "Black Widow",
    "media_type": "movie",
    "release_order": 32,
    "chronological_order": 63,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 497698,
    "poster_path": "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises."
  },
  {
    "id": "marvel-33",
    "universe": "mcu",
    "title": "What If...? (Season 1)",
    "media_type": "show",
    "release_order": 33,
    "chronological_order": 98,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 91363,
    "poster_path": "https://image.tmdb.org/t/p/w500/zaqfFDUrSfIljdD0OBxSjcutX8n.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "Taking inspiration from the comic books of the same name, each episode explores a pivotal moment from the MCU turned on its head."
  },
  {
    "id": "marvel-34",
    "universe": "mcu",
    "title": "Shang-Chi and the Legend of the Ten Rings",
    "media_type": "movie",
    "release_order": 34,
    "chronological_order": 100,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 566525,
    "poster_path": "https://image.tmdb.org/t/p/w500/9f2Q0U3IOsLgrI2HkvldwSABZy5.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization."
  },
  {
    "id": "marvel-35",
    "universe": "mcu",
    "title": "Eternals",
    "media_type": "movie",
    "release_order": 35,
    "chronological_order": 105,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 524434,
    "poster_path": "https://image.tmdb.org/t/p/w500/lFByFSLV5WDJEv3KabbdAF959F2.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "The Eternals, a race of immortal beings with superhuman powers who have secretly lived on Earth for thousands of years, reunite."
  },
  {
    "id": "marvel-36",
    "universe": "mcu",
    "title": "Hawkeye (Season 1)",
    "media_type": "show",
    "release_order": 36,
    "chronological_order": 107,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 88329,
    "poster_path": "https://image.tmdb.org/t/p/w500/ct5pNE5dDHryHLDnxyZPYcqO1sz.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas. Possible? Maybe with help from Kate Bishop."
  },
  {
    "id": "marvel-37",
    "universe": "mcu",
    "title": "Spider-Man: No Way Home",
    "media_type": "movie",
    "release_order": 37,
    "chronological_order": 104,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 634649,
    "poster_path": "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "Peter Parker seeks Doctor Strange's help to make everyone forget he is Spider-Man, which breaks the multiverse open."
  },
  {
    "id": "marvel-38",
    "universe": "mcu",
    "title": "Moon Knight (Season 1)",
    "media_type": "show",
    "release_order": 38,
    "chronological_order": 108,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 92749,
    "poster_path": "https://image.tmdb.org/t/p/w500/x6FsYvt33846IQnDSFxla9j0RX8.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "Mild-mannered gift-shop employee Steven Grant becomes plagued with blackouts and discovers he has dissociative identity disorder."
  },
  {
    "id": "marvel-39",
    "universe": "mcu",
    "title": "Doctor Strange in the Multiverse of Madness",
    "media_type": "movie",
    "release_order": 39,
    "chronological_order": 106,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 453395,
    "poster_path": "https://image.tmdb.org/t/p/w500/ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "Doctor Strange traverses the mind-bending and dangerous alternate realities of the Multiverse with America Chavez."
  },
  {
    "id": "marvel-40",
    "universe": "mcu",
    "title": "Ms. Marvel (Season 1)",
    "media_type": "show",
    "release_order": 40,
    "chronological_order": 112,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 92782,
    "poster_path": "https://image.tmdb.org/t/p/w500/3HWWh92kZbD7odwJX7nKmXNZsYo.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "A great student, an avid gamer and a voracious fan-fiction scribe, Kamala Khan feels like she doesn't fit in until she gets superpowers."
  },
  {
    "id": "marvel-41",
    "universe": "mcu",
    "title": "Thor: Love and Thunder",
    "media_type": "movie",
    "release_order": 41,
    "chronological_order": 113,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 616037,
    "poster_path": "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "Thor embarks on a journey unlike anything he's ever faced -- a quest for inner peace. But his retirement is interrupted by Gorr."
  },
  {
    "id": "marvel-42",
    "universe": "mcu",
    "title": "I Am Groot (Season 1)",
    "media_type": "show",
    "release_order": 42,
    "chronological_order": 49,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 114478,
    "poster_path": "https://image.tmdb.org/t/p/w500/lG9ltUP4FwvsQBcwOJYceDbP48E.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "A collection of shorts following Baby Groot’s glory days growing up, and getting into trouble, among the stars."
  },
  {
    "id": "marvel-43",
    "universe": "mcu",
    "title": "She-Hulk: Attorney at Law (Season 1)",
    "media_type": "show",
    "release_order": 43,
    "chronological_order": 111,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 92783,
    "poster_path": "https://image.tmdb.org/t/p/w500/5xz2orV8f0usyrfGNshcoXHmiaV.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk."
  },
  {
    "id": "marvel-44",
    "universe": "mcu",
    "title": "Werewolf by Night",
    "media_type": "special",
    "release_order": 44,
    "chronological_order": 114,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 894205,
    "poster_path": "https://image.tmdb.org/t/p/w500/mvIvNKRIJPPS7WSFarFhOAGIVnU.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the Bloodstone Temple."
  },
  {
    "id": "marvel-45",
    "universe": "mcu",
    "title": "Black Panther: Wakanda Forever",
    "media_type": "movie",
    "release_order": 45,
    "chronological_order": 109,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 505642,
    "poster_path": "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "Queen Ramonda, Shuri, M'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers and Namor."
  },
  {
    "id": "marvel-46",
    "universe": "mcu",
    "title": "The Guardians of the Galaxy Holiday Special",
    "media_type": "special",
    "release_order": 46,
    "chronological_order": 115,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 774752,
    "poster_path": "https://image.tmdb.org/t/p/w500/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present."
  },
  {
    "id": "marvel-47",
    "universe": "mcu",
    "title": "Ant-Man and the Wasp: Quantumania",
    "media_type": "movie",
    "release_order": 47,
    "chronological_order": 116,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 640146,
    "poster_path": "https://image.tmdb.org/t/p/w500/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
    "is_released": true,
    "release_date": "2023-01-01",
    "overview": "Super-Hero partners Scott Lang and Hope van Dyne return to continue their adventures as Ant-Man and the Wasp in the Quantum Realm."
  },
  {
    "id": "marvel-48",
    "universe": "mcu",
    "title": "Guardians of the Galaxy Vol. 3",
    "media_type": "movie",
    "release_order": 48,
    "chronological_order": 117,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 447365,
    "poster_path": "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    "is_released": true,
    "release_date": "2023-01-01",
    "overview": "Peter Quill must rally his team around him to defend the universe along with protecting one of their own: Rocket."
  },
  {
    "id": "marvel-49",
    "universe": "mcu",
    "title": "Secret Invasion (Season 1)",
    "media_type": "show",
    "release_order": 49,
    "chronological_order": 118,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 114479,
    "poster_path": "https://image.tmdb.org/t/p/w500/mztdt3y6GBsJR69zHtszFezTCLT.jpg",
    "is_released": true,
    "release_date": "2023-01-01",
    "overview": "Nick Fury learns of a clandestine invasion of Earth by a faction of shapeshifting Skrulls."
  },
  {
    "id": "marvel-50",
    "universe": "mcu",
    "title": "I Am Groot (Season 2)",
    "media_type": "show",
    "release_order": 50,
    "chronological_order": 51,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 114478,
    "poster_path": "https://image.tmdb.org/t/p/w500/8yECMpsZ8wAvra4Sow6Bz9WOO5f.jpg",
    "is_released": true,
    "release_date": "2023-01-01",
    "overview": "The troublemaking twig returns for mischief in the second season of I Am Groot."
  },
  {
    "id": "marvel-51",
    "universe": "mcu",
    "title": "Loki (Season 2)",
    "media_type": "show",
    "release_order": 51,
    "chronological_order": 120,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 84958,
    "poster_path": "https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    "is_released": true,
    "release_date": "2023-01-01",
    "overview": "Loki navigates an ever-expanding and increasingly dangerous multiverse in search of Sylvie, Judge Renslayer and Miss Minutes."
  },
  {
    "id": "marvel-52",
    "universe": "mcu",
    "title": "The Marvels",
    "media_type": "movie",
    "release_order": 52,
    "chronological_order": 119,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 609681,
    "poster_path": "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
    "is_released": true,
    "release_date": "2023-01-01",
    "overview": "Carol Danvers, Kamala Khan, and Monica Rambeau discover their powers have become entangled, swapping places whenever they are used."
  },
  {
    "id": "marvel-53",
    "universe": "mcu",
    "title": "What If...? (Season 2)",
    "media_type": "show",
    "release_order": 53,
    "chronological_order": 121,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 91363,
    "poster_path": "https://image.tmdb.org/t/p/w500/zaqfFDUrSfIljdD0OBxSjcutX8n.jpg",
    "is_released": true,
    "release_date": "2023-01-01",
    "overview": "The Watcher continues the journey through the vast multiverse, introducing brand-new and familiar faces."
  },
  {
    "id": "marvel-54",
    "universe": "mcu",
    "title": "Echo (Season 1)",
    "media_type": "show",
    "release_order": 54,
    "chronological_order": 110,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 122226,
    "poster_path": "https://image.tmdb.org/t/p/w500/vFyJH630cF68LohVYjQW49074Sy.jpg",
    "is_released": true,
    "release_date": "2024-01-01",
    "overview": "Maya Lopez must face her past, reconnect with her Native American roots and embrace the meaning of family."
  },
  {
    "id": "marvel-55",
    "universe": "mcu",
    "title": "Deadpool & Wolverine",
    "media_type": "movie",
    "release_order": 55,
    "chronological_order": 126,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 533535,
    "poster_path": "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    "is_released": true,
    "release_date": "2024-01-01",
    "overview": "A listless Wade Wilson toils away in civilian life until a threat to his home world sends him on a mission with Wolverine."
  },
  {
    "id": "marvel-56",
    "universe": "mcu",
    "title": "Agatha All Along (Season 1)",
    "media_type": "show",
    "release_order": 56,
    "chronological_order": 127,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 138501,
    "poster_path": "https://image.tmdb.org/t/p/w500/mGsxKwXUjojitRv2E9qMTbxbBRd.jpg",
    "is_released": true,
    "release_date": "2024-01-01",
    "overview": "Agatha Harkness gathers an eclectic coven of witches to walk the Witches' Road and regain her power."
  },
  {
    "id": "marvel-57",
    "universe": "mcu",
    "title": "What If...? (Season 3)",
    "media_type": "show",
    "release_order": 57,
    "chronological_order": 128,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 91363,
    "poster_path": "https://image.tmdb.org/t/p/w500/zaqfFDUrSfIljdD0OBxSjcutX8n.jpg",
    "is_released": true,
    "release_date": "2024-01-01",
    "overview": "The culminating third season of Marvel Studios' What If...? explores alternate realities."
  },
  {
    "id": "marvel-58",
    "universe": "mcu",
    "title": "Your Friendly Neighborhood Spider-Man (Season 1)",
    "media_type": "show",
    "release_order": 58,
    "chronological_order": 132,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 138503,
    "poster_path": "https://image.tmdb.org/t/p/w500/5mUBVvYq22t5k01Z7z6u9g2K9uA.jpg",
    "is_released": true,
    "release_date": "2025-01-01",
    "overview": "An animated series following Peter Parker on his way to becoming Spider-Man in the MCU."
  },
  {
    "id": "marvel-59",
    "universe": "mcu",
    "title": "Captain America: Brave New World",
    "media_type": "movie",
    "release_order": 59,
    "chronological_order": 133,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 822119,
    "poster_path": "https://image.tmdb.org/t/p/w500/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
    "is_released": true,
    "release_date": "2025-02-14",
    "overview": "Sam Wilson officially takes up the mantle of Captain America and navigates an international crisis."
  },
  {
    "id": "marvel-60",
    "universe": "mcu",
    "title": "Daredevil: Born Again (Season 1)",
    "media_type": "show",
    "release_order": 60,
    "chronological_order": 134,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 202555,
    "poster_path": "https://image.tmdb.org/t/p/w500/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
    "is_released": true,
    "release_date": "2025-03-04",
    "overview": "Matt Murdock and Wilson Fisk try to leave behind their darker alter-egos to serve the people of New York."
  },
  {
    "id": "marvel-61",
    "universe": "mcu",
    "title": "Thunderbolts*",
    "media_type": "movie",
    "release_order": 61,
    "chronological_order": 135,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 986056,
    "poster_path": "https://image.tmdb.org/t/p/w500/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
    "is_released": true,
    "release_date": "2025-05-02",
    "overview": "An irreverent team-up featuring depressed assassin Yelena Belova alongside the MCU’s least anticipated band of misfits."
  },
  {
    "id": "marvel-62",
    "universe": "mcu",
    "title": "Ironheart (Season 1)",
    "media_type": "show",
    "release_order": 62,
    "chronological_order": 136,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 114473,
    "poster_path": "https://image.tmdb.org/t/p/w500/77w0N4C9m4p6fW5v3A9L1zX3u6A.jpg",
    "is_released": true,
    "release_date": "2025-06-24",
    "overview": "Genius inventor Riri Williams creates the most advanced suit of armor since Iron Man."
  },
  {
    "id": "marvel-63",
    "universe": "mcu",
    "title": "The Fantastic Four: First Steps",
    "media_type": "movie",
    "release_order": 63,
    "chronological_order": 137,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 617126,
    "poster_path": "https://image.tmdb.org/t/p/w500/nf5qaSEvyYSNeFH0YhSs5EsBLX9.jpg",
    "is_released": true,
    "release_date": "2025-07-25",
    "overview": "Set against the vibrant backdrop of a 1960s-inspired retro-futuristic world, Marvel's First Family balances superhero life and Galactus."
  },
  {
    "id": "marvel-64",
    "universe": "mcu",
    "title": "Eyes of Wakanda (Season 1)",
    "media_type": "show",
    "release_order": 64,
    "chronological_order": 138,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 241257,
    "poster_path": "https://image.tmdb.org/t/p/w500/w0w2d3P8fA6e5u2T9s7J7e0p6k2.jpg",
    "is_released": true,
    "release_date": "2025-08-06",
    "overview": "Throughout Wakandan history, brave warriors have been tasked to retrieve dangerous vibranium artifacts around the globe."
  },
  {
    "id": "marvel-65",
    "universe": "mcu",
    "title": "Marvel Zombies (Season 1)",
    "media_type": "show",
    "release_order": 65,
    "chronological_order": 139,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 138505,
    "poster_path": "https://image.tmdb.org/t/p/w500/uYfW8X2qZpL4u5B6W9e5s9q2p3A.jpg",
    "is_released": true,
    "release_date": "2025-10-03",
    "overview": "A new generation of heroes must battle an ever-spreading zombie scourge in this animated TV-MA series."
  },
  {
    "id": "marvel-66",
    "universe": "mcu",
    "title": "Wonder Man (Season 1)",
    "media_type": "show",
    "release_order": 66,
    "chronological_order": 140,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 204541,
    "poster_path": "https://image.tmdb.org/t/p/w500/e9s9v2q4f5f8s7w6e5r4t3y2u1o.jpg",
    "is_released": true,
    "release_date": "2025-12-01",
    "overview": "Simon Williams is an actor and stuntman who gains superpowers to become superhero Wonder Man."
  },
  {
    "id": "marvel-67",
    "universe": "mcu",
    "title": "Daredevil: Born Again (Season 2)",
    "media_type": "show",
    "release_order": 67,
    "chronological_order": 141,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 202555,
    "poster_path": "https://image.tmdb.org/t/p/w500/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
    "is_released": false,
    "release_date": "2026-03-01",
    "overview": "The next chapter in Matt Murdock's crusade across Hell's Kitchen and New York City."
  },
  {
    "id": "marvel-68",
    "universe": "mcu",
    "title": "The Punisher: One Last Kill",
    "media_type": "special",
    "release_order": 68,
    "chronological_order": 142,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": null,
    "poster_path": "https://image.tmdb.org/t/p/w500/dOkJ6TJKQjsz2XwXyp2VYpkeE5g.jpg",
    "is_released": false,
    "release_date": "2026-04-01",
    "overview": "Frank Castle returns for a definitive special presentation mission."
  },
  {
    "id": "marvel-69",
    "universe": "mcu",
    "title": "Spider-Man: Brand New Day",
    "media_type": "movie",
    "release_order": 69,
    "chronological_order": 143,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 969681,
    "poster_path": "https://image.tmdb.org/t/p/w500/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    "is_released": false,
    "release_date": "2026-07-24",
    "overview": "Peter Parker navigates a fresh chapter as a street-level Spider-Man in New York City."
  },
  {
    "id": "marvel-70",
    "universe": "mcu",
    "title": "VisionQuest (Season 1)",
    "media_type": "show",
    "release_order": 70,
    "chronological_order": 145,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": null,
    "poster_path": "https://image.tmdb.org/t/p/w500/ijWWwINc8h71NQ8j1LTJMFSj5wr.jpg",
    "is_released": false,
    "release_date": "2026-09-01",
    "overview": "White Vision embarks on a journey of self-discovery to regain his memories and humanity."
  },
  {
    "id": "marvel-71",
    "universe": "mcu",
    "title": "Avengers: Doomsday",
    "media_type": "movie",
    "release_order": 71,
    "chronological_order": 146,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 1003596,
    "poster_path": "https://image.tmdb.org/t/p/w500/h5k0d7f4A9s6w5e4r3t2y1u0i9o.jpg",
    "is_released": false,
    "release_date": "2026-05-01",
    "overview": "Earth's mightiest heroes clash with Doctor Doom in a universe-altering showdown."
  },
  {
    "id": "marvel-72",
    "universe": "mcu",
    "title": "Your Friendly Neighborhood Spider-Man (Season 2)",
    "media_type": "show",
    "release_order": 72,
    "chronological_order": 147,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 138503,
    "poster_path": "https://image.tmdb.org/t/p/w500/5mUBVvYq22t5k01Z7z6u9g2K9uA.jpg",
    "is_released": false,
    "release_date": "2026-11-01",
    "overview": "The second season following Peter Parker's high school superhero journey."
  },
  {
    "id": "marvel-73",
    "universe": "mcu",
    "title": "Daredevil: Born Again (Season 3)",
    "media_type": "show",
    "release_order": 73,
    "chronological_order": 148,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 202555,
    "poster_path": "https://image.tmdb.org/t/p/w500/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
    "is_released": false,
    "release_date": "2027-01-01",
    "overview": "The third season of Marvel Studios' Daredevil: Born Again."
  },
  {
    "id": "marvel-74",
    "universe": "mcu",
    "title": "Avengers: Secret Wars",
    "media_type": "movie",
    "release_order": 74,
    "chronological_order": 149,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 1003598,
    "poster_path": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    "is_released": false,
    "release_date": "2027-05-07",
    "overview": "The catastrophic culmination of the Multiverse Saga as realities collide on Battleworld."
  },
  {
    "id": "marvel-75",
    "universe": "mcu",
    "title": "Venom",
    "media_type": "movie",
    "release_order": 75,
    "chronological_order": 87,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 335983,
    "poster_path": "https://image.tmdb.org/t/p/w500/2uNW4WbgBHg5576P6KAlVPfgwh1.jpg",
    "is_released": true,
    "release_date": "2018-01-01",
    "overview": "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of an alien symbiote."
  },
  {
    "id": "marvel-76",
    "universe": "mcu",
    "title": "Venom: Let There Be Carnage",
    "media_type": "movie",
    "release_order": 76,
    "chronological_order": 103,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 580489,
    "poster_path": "https://image.tmdb.org/t/p/w500/1I7uztLcGmK8aE6r0VfA2yG8Uf.jpg",
    "is_released": true,
    "release_date": "2021-01-01",
    "overview": "Eddie Brock struggles to adjust to life as the host of the alien symbiote Venom, while serial killer Cletus Kasady becomes Carnage."
  },
  {
    "id": "marvel-77",
    "universe": "mcu",
    "title": "Morbius",
    "media_type": "movie",
    "release_order": 77,
    "chronological_order": 123,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 526896,
    "poster_path": "https://image.tmdb.org/t/p/w500/6JjfSchHsiCc0vmNTivA9b965Ej.jpg",
    "is_released": true,
    "release_date": "2022-01-01",
    "overview": "Dangerously ill with a rare blood disorder, Dr. Morbius attempts a desperate gamble that unleashes a darkness inside him."
  },
  {
    "id": "marvel-78",
    "universe": "mcu",
    "title": "Madame Web",
    "media_type": "movie",
    "release_order": 78,
    "chronological_order": 18,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 634492,
    "poster_path": "https://image.tmdb.org/t/p/w500/rULWuutDcN5NvtiZi4xZa35whW4.jpg",
    "is_released": true,
    "release_date": "2024-01-01",
    "overview": "Cassandra Webb is a New York City paramedic who develops the ability to see the future."
  },
  {
    "id": "marvel-79",
    "universe": "mcu",
    "title": "Venom: The Last Dance",
    "media_type": "movie",
    "release_order": 79,
    "chronological_order": 124,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 912649,
    "poster_path": "https://image.tmdb.org/t/p/w500/aosm8Vh9ilBt69SvFDg9RStAcUb.jpg",
    "is_released": true,
    "release_date": "2024-01-01",
    "overview": "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision."
  },
  {
    "id": "marvel-80",
    "universe": "mcu",
    "title": "Kraven the Hunter",
    "media_type": "movie",
    "release_order": 80,
    "chronological_order": 125,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 558449,
    "poster_path": "https://image.tmdb.org/t/p/w500/1GvBhIvdBqLh10m1r78wY74Y59T.jpg",
    "is_released": true,
    "release_date": "2024-01-01",
    "overview": "Kraven's complex relationship with his ruthless father Nikolai Kravinoff starts him down a path of vengeance."
  },
  {
    "id": "marvel-81",
    "universe": "mcu",
    "title": "Spider-Man: Into the Spider-Verse",
    "media_type": "movie",
    "release_order": 81,
    "chronological_order": 88,
    "phase_or_chapter": "Sony's Spider-Verse Animated",
    "trakt_id": null,
    "tmdb_id": 324857,
    "poster_path": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    "is_released": true,
    "release_date": "2018-01-01",
    "overview": "Teen Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from across parallel universes."
  },
  {
    "id": "marvel-82",
    "universe": "mcu",
    "title": "Spider-Man: Across the Spider-Verse",
    "media_type": "movie",
    "release_order": 82,
    "chronological_order": 122,
    "phase_or_chapter": "Sony's Spider-Verse Animated",
    "trakt_id": null,
    "tmdb_id": 569094,
    "poster_path": "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    "is_released": true,
    "release_date": "2023-01-01",
    "overview": "Miles Morales catapults across the Multiverse, where he encounters the Spider-Society and must redefine what it means to be a hero."
  },
  {
    "id": "marvel-83",
    "universe": "mcu",
    "title": "Spider-Man: Beyond the Spider-Verse",
    "media_type": "movie",
    "release_order": 83,
    "chronological_order": 144,
    "phase_or_chapter": "Sony's Spider-Verse Animated",
    "trakt_id": null,
    "tmdb_id": 911916,
    "poster_path": "https://image.tmdb.org/t/p/w500/9KAe39xqyZnv9J4W3DRGdQqX82h.jpg",
    "is_released": false,
    "release_date": "2027-01-01",
    "overview": "The epic conclusion to the Spider-Verse trilogy as Miles Morales battles across dimensions to save the multiverse and his family."
  },
  {
    "id": "marvel-84",
    "universe": "mcu",
    "title": "Spider-Man",
    "media_type": "movie",
    "release_order": 84,
    "chronological_order": 14,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 557,
    "poster_path": "https://image.tmdb.org/t/p/w500/gh4c2ubiUzBsNyIQfZkYGlHgC39.jpg",
    "is_released": true,
    "release_date": "2002-01-01",
    "overview": "After being bitten by a genetically altered spider, high school student Peter Parker gains superpowers to fight the Green Goblin."
  },
  {
    "id": "marvel-85",
    "universe": "mcu",
    "title": "Spider-Man 2",
    "media_type": "movie",
    "release_order": 85,
    "chronological_order": 20,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 558,
    "poster_path": "https://image.tmdb.org/t/p/w500/olxpyq9kJAZ2NU1iEv96mst5JQf.jpg",
    "is_released": true,
    "release_date": "2004-01-01",
    "overview": "Peter Parker is beset with troubles in his failing personal life as he battles a brilliant scientist named Doctor Octopus."
  },
  {
    "id": "marvel-86",
    "universe": "mcu",
    "title": "Spider-Man 3",
    "media_type": "movie",
    "release_order": 86,
    "chronological_order": 28,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 559,
    "poster_path": "https://image.tmdb.org/t/p/w500/2jLxvdY5qYvdvNf1lK2lC88e44s.jpg",
    "is_released": true,
    "release_date": "2007-01-01",
    "overview": "The seemingly invincible Spider-Man goes up against an alien symbiote and villains Sandman and Venom."
  },
  {
    "id": "marvel-87",
    "universe": "mcu",
    "title": "The Amazing Spider-Man",
    "media_type": "movie",
    "release_order": 87,
    "chronological_order": 40,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 1930,
    "poster_path": "https://image.tmdb.org/t/p/w500/fSbkkk6gWqQkS8b9r7U3U9m4c2A.jpg",
    "is_released": true,
    "release_date": "2012-01-01",
    "overview": "Peter Parker tries to find out who he is and how he got to be the person he is today while battling the Lizard."
  },
  {
    "id": "marvel-88",
    "universe": "mcu",
    "title": "The Amazing Spider-Man 2",
    "media_type": "movie",
    "release_order": 88,
    "chronological_order": 47,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 102382,
    "poster_path": "https://image.tmdb.org/t/p/w500/c3eBqBq48QjV7n0lJ9z5a7n9m5A.jpg",
    "is_released": true,
    "release_date": "2014-01-01",
    "overview": "When New York is put under siege by Oscorp, it is up to Spider-Man to save the city he swore to protect as well as the ones he loves."
  },
  {
    "id": "marvel-89",
    "universe": "mcu",
    "title": "X-Men",
    "media_type": "movie",
    "release_order": 89,
    "chronological_order": 12,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 36657,
    "poster_path": "https://image.tmdb.org/t/p/w500/bRDAc4GogS9ciRZWh9P7qlTH7ip.jpg",
    "is_released": true,
    "release_date": "2000-01-01",
    "overview": "Two mutants come to a private academy for their kind whose resident superhero team must oppose a terrorist organization."
  },
  {
    "id": "marvel-90",
    "universe": "mcu",
    "title": "X2: X-Men United",
    "media_type": "movie",
    "release_order": 90,
    "chronological_order": 16,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 36658,
    "poster_path": "https://image.tmdb.org/t/p/w500/a3IUp9L2j1p4k3l5m6b7v8c9d0e.jpg",
    "is_released": true,
    "release_date": "2003-01-01",
    "overview": "The X-Men band together to find a mutant assassin who has made an attempt on the President's life."
  },
  {
    "id": "marvel-91",
    "universe": "mcu",
    "title": "X-Men: The Last Stand",
    "media_type": "movie",
    "release_order": 91,
    "chronological_order": 25,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 36668,
    "poster_path": "https://image.tmdb.org/t/p/w500/kh7B91bMl2lZ0mH9WhPfaNUIEQH.jpg",
    "is_released": true,
    "release_date": "2006-01-01",
    "overview": "When a cure is found to treat mutations, lines are drawn among the X-Men and The Brotherhood of Mutants."
  },
  {
    "id": "marvel-92",
    "universe": "mcu",
    "title": "X-Men Origins: Wolverine",
    "media_type": "movie",
    "release_order": 92,
    "chronological_order": 7,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 2080,
    "poster_path": "https://image.tmdb.org/t/p/w500/mCRg7l2Wq1v6Jk0lP9m5A4s8d9f.jpg",
    "is_released": true,
    "release_date": "2009-01-01",
    "overview": "A look at Wolverine's early life, in particular his time with the government squad Team X and the Weapon X program."
  },
  {
    "id": "marvel-93",
    "universe": "mcu",
    "title": "X-Men: First Class",
    "media_type": "movie",
    "release_order": 93,
    "chronological_order": 5,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 49538,
    "poster_path": "https://image.tmdb.org/t/p/w500/4n254oGf8z244XoZ76GZ8x0HqY6.jpg",
    "is_released": true,
    "release_date": "2011-01-01",
    "overview": "In the 1960s, Charles Xavier and Erik Lehnsherr work together to find other mutants to stop the Hellfire Club."
  },
  {
    "id": "marvel-94",
    "universe": "mcu",
    "title": "The Wolverine",
    "media_type": "movie",
    "release_order": 94,
    "chronological_order": 45,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 76170,
    "poster_path": "https://image.tmdb.org/t/p/w500/xW3fL8u0r4t8y2u1o9p7q6w5e4r.jpg",
    "is_released": true,
    "release_date": "2013-01-01",
    "overview": "Wolverine faces his ultimate nemesis - and tests of his physical, emotional, and mortal limits - in modern-day Japan."
  },
  {
    "id": "marvel-95",
    "universe": "mcu",
    "title": "X-Men: Days of Future Past",
    "media_type": "movie",
    "release_order": 95,
    "chronological_order": 6,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 127585,
    "poster_path": "https://image.tmdb.org/t/p/w500/tK6T5q0r8y2u1o9p7q6w5e4r3t2.jpg",
    "is_released": true,
    "release_date": "2014-01-01",
    "overview": "The X-Men send Wolverine to the past in a desperate effort to change history and prevent an event that results in doom."
  },
  {
    "id": "marvel-96",
    "universe": "mcu",
    "title": "Deadpool",
    "media_type": "movie",
    "release_order": 96,
    "chronological_order": 61,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 293660,
    "poster_path": "https://image.tmdb.org/t/p/w500/fSRb7vyIP8rQpL0I47P3q5Y6r0s.jpg",
    "is_released": true,
    "release_date": "2016-01-01",
    "overview": "A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks."
  },
  {
    "id": "marvel-97",
    "universe": "mcu",
    "title": "X-Men: Apocalypse",
    "media_type": "movie",
    "release_order": 97,
    "chronological_order": 8,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 246655,
    "poster_path": "https://image.tmdb.org/t/p/w500/2mtQwJKCSEHgMZaUNvB3QHx11fJ.jpg",
    "is_released": true,
    "release_date": "2016-01-01",
    "overview": "Since the dawn of civilization, he was worshipped as a god. Apocalypse, the first and most powerful mutant, awakens."
  },
  {
    "id": "marvel-98",
    "universe": "mcu",
    "title": "Logan",
    "media_type": "movie",
    "release_order": 98,
    "chronological_order": 150,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 263115,
    "poster_path": "https://image.tmdb.org/t/p/w500/fSQb8qyX4v5r6t7y8u9i0o1p2a3.jpg",
    "is_released": true,
    "release_date": "2017-01-01",
    "overview": "In the near future, a weary Logan cares for an ailing Professor X near the Mexican border until a young mutant arrives."
  },
  {
    "id": "marvel-99",
    "universe": "mcu",
    "title": "Legion (Seasons 1–3)",
    "media_type": "show",
    "release_order": 99,
    "chronological_order": 73,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 67195,
    "poster_path": "https://image.tmdb.org/t/p/w500/4zT4v8q9p7o2i3u5y6r1t8e9w0q.jpg",
    "is_released": true,
    "release_date": "2017-01-01",
    "overview": "David Haller, a troubled young man diagnosed with schizophrenia, discovers he may be the most powerful mutant."
  },
  {
    "id": "marvel-100",
    "universe": "mcu",
    "title": "The Gifted (Seasons 1–2)",
    "media_type": "show",
    "release_order": 100,
    "chronological_order": 74,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 69629,
    "poster_path": "https://image.tmdb.org/t/p/w500/nshCqszjTNuqhrB53vrSqWO18sE.jpg",
    "is_released": true,
    "release_date": "2017-01-01",
    "overview": "A suburban couple's ordinary lives are rocked by the discovery that their children possess mutant powers."
  },
  {
    "id": "marvel-101",
    "universe": "mcu",
    "title": "Deadpool 2",
    "media_type": "movie",
    "release_order": 101,
    "chronological_order": 86,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 383498,
    "poster_path": "https://image.tmdb.org/t/p/w500/to0spRl1CMDvyUbvdIO320Q6RkG.jpg",
    "is_released": true,
    "release_date": "2018-01-01",
    "overview": "Wisecracking mercenary Deadpool battles the time-traveling cybernetic soldier Cable to protect a mutant boy."
  },
  {
    "id": "marvel-102",
    "universe": "mcu",
    "title": "Dark Phoenix",
    "media_type": "movie",
    "release_order": 102,
    "chronological_order": 9,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 320288,
    "poster_path": "https://image.tmdb.org/t/p/w500/cCTjpXZqGtFfgxKa04CJ91GwBt.jpg",
    "is_released": true,
    "release_date": "2019-01-01",
    "overview": "During a rescue mission in space, Jean Grey is hit by a cosmic force that transforms her into the Dark Phoenix."
  },
  {
    "id": "marvel-103",
    "universe": "mcu",
    "title": "The New Mutants",
    "media_type": "movie",
    "release_order": 103,
    "chronological_order": 95,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 340102,
    "poster_path": "https://image.tmdb.org/t/p/w500/xrIaa7m7pL2v0c1m6b7v8c9d0e.jpg",
    "is_released": true,
    "release_date": "2020-01-01",
    "overview": "Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape."
  },
  {
    "id": "marvel-104",
    "universe": "mcu",
    "title": "Daredevil",
    "media_type": "movie",
    "release_order": 104,
    "chronological_order": 15,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 9480,
    "poster_path": "https://image.tmdb.org/t/p/w500/4zT4v8q9p7o2i3u5y6r1t8e9w0q.jpg",
    "is_released": true,
    "release_date": "2003-01-01",
    "overview": "A man blinded by toxic waste which also enhanced his other senses becomes a crime-fighting hero."
  },
  {
    "id": "marvel-105",
    "universe": "mcu",
    "title": "Elektra",
    "media_type": "movie",
    "release_order": 105,
    "chronological_order": 22,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 9353,
    "poster_path": "https://image.tmdb.org/t/p/w500/5k7T4v8q9p7o2i3u5y6r1t8e9w0.jpg",
    "is_released": true,
    "release_date": "2005-01-01",
    "overview": "Elektra the warrior survives her near-death experience, becomes an assassin-for-hire, and tries to protect a father and daughter."
  },
  {
    "id": "marvel-106",
    "universe": "mcu",
    "title": "Fantastic Four",
    "media_type": "movie",
    "release_order": 106,
    "chronological_order": 23,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 9738,
    "poster_path": "https://image.tmdb.org/t/p/w500/4YMcYEFS8sFuW3soP1HVmgR3cSm.jpg",
    "is_released": true,
    "release_date": "2005-01-01",
    "overview": "Four scientists gain extraordinary superhuman powers after being exposed to cosmic radiation."
  },
  {
    "id": "marvel-107",
    "universe": "mcu",
    "title": "Fantastic Four: Rise of the Silver Surfer",
    "media_type": "movie",
    "release_order": 107,
    "chronological_order": 29,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 1979,
    "poster_path": "https://image.tmdb.org/t/p/w500/9wRfzTcMyyzkQxVDqBHv8RwuZOv.jpg",
    "is_released": true,
    "release_date": "2007-01-01",
    "overview": "The Fantastic Four encounter the mysterious Silver Surfer and face the cosmic planet-devouring threat of Galactus."
  },
  {
    "id": "marvel-108",
    "universe": "mcu",
    "title": "Fantastic Four (Fant4stic)",
    "media_type": "movie",
    "release_order": 108,
    "chronological_order": 56,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 166424,
    "poster_path": "https://image.tmdb.org/t/p/w500/7Yv7k8w9e5r4t3y2u1o9p7q6w5e.jpg",
    "is_released": true,
    "release_date": "2015-01-01",
    "overview": "Four young outsiders teleport to an alternate and dangerous universe which alters their physical form in shocking ways."
  },
  {
    "id": "marvel-tv-109",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 1)",
    "media_type": "show",
    "release_order": 109,
    "chronological_order": 43,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/1CaKyPcZvzzMSwbNFJObxNsxTkK.jpg",
    "is_released": true,
    "release_date": "2013-09-24",
    "overview": "Phil Coulson puts together a small team of S.H.I.E.L.D. agents to handle strange new cases across the globe."
  },
  {
    "id": "marvel-tv-110",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 2)",
    "media_type": "show",
    "release_order": 110,
    "chronological_order": 53,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/p8Qy60OIf0OaJ29KPw6ld51MSP7.jpg",
    "is_released": true,
    "release_date": "2014-09-23",
    "overview": "Following the collapse of S.H.I.E.L.D., Director Coulson and his team rebuild while facing the emergence of Inhumans."
  },
  {
    "id": "marvel-tv-111",
    "universe": "mcu",
    "title": "Agent Carter (Season 1)",
    "media_type": "show",
    "release_order": 111,
    "chronological_order": 2,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61550,
    "poster_path": "https://image.tmdb.org/t/p/w500/gqyjmfFOrKY8iouNTXWj9KW7cC5.jpg",
    "is_released": true,
    "release_date": "2015-01-06",
    "overview": "In 1946, Peggy Carter balances administrative work with secret missions for Howard Stark after WWII."
  },
  {
    "id": "marvel-tv-112",
    "universe": "mcu",
    "title": "Daredevil (Season 1)",
    "media_type": "show",
    "release_order": 112,
    "chronological_order": 52,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61889,
    "poster_path": "https://image.tmdb.org/t/p/w500/zFmJQzl6bFrdpHhDkxXmboyykqD.jpg",
    "is_released": true,
    "release_date": "2015-04-10",
    "overview": "Blind lawyer Matt Murdock fights injustice by night in Hell's Kitchen as Daredevil against crime lord Wilson Fisk."
  },
  {
    "id": "marvel-tv-113",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 3)",
    "media_type": "show",
    "release_order": 113,
    "chronological_order": 60,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/y0cxxcvCk9lEG4DEorTz5GxC9sj.jpg",
    "is_released": true,
    "release_date": "2015-09-29",
    "overview": "Director Coulson searches the globe for Secret Warriors as ancient Inhuman threat Hive arises."
  },
  {
    "id": "marvel-tv-114",
    "universe": "mcu",
    "title": "Jessica Jones (Season 1)",
    "media_type": "show",
    "release_order": 114,
    "chronological_order": 57,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 38472,
    "poster_path": "https://image.tmdb.org/t/p/w500/9wwfowgVJDouHQdUsIcNhgbIUlG.jpg",
    "is_released": true,
    "release_date": "2015-11-20",
    "overview": "Traumatized private eye Jessica Jones must confront her mind-controlling abuser Kilgrave."
  },
  {
    "id": "marvel-tv-115",
    "universe": "mcu",
    "title": "Agent Carter (Season 2)",
    "media_type": "show",
    "release_order": 115,
    "chronological_order": 3,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61550,
    "poster_path": "https://image.tmdb.org/t/p/w500/h3yPRRiWZk6HrFD2oo3xqpLt6bc.jpg",
    "is_released": true,
    "release_date": "2016-01-19",
    "overview": "Peggy Carter moves to Hollywood to investigate mysterious Zero Matter and Hollywood villain Whitney Frost."
  },
  {
    "id": "marvel-tv-116",
    "universe": "mcu",
    "title": "Daredevil (Season 2)",
    "media_type": "show",
    "release_order": 116,
    "chronological_order": 58,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61889,
    "poster_path": "https://image.tmdb.org/t/p/w500/opHoslNCxkgoCaGhfO66fvCSH83.jpg",
    "is_released": true,
    "release_date": "2016-03-18",
    "overview": "Daredevil clashes with lethal vigilante Frank Castle (The Punisher) and mystic ninja clan The Hand."
  },
  {
    "id": "marvel-tv-117",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 4)",
    "media_type": "show",
    "release_order": 117,
    "chronological_order": 70,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/mgyMzTTIFVdKoejD0gKIyaCgWOP.jpg",
    "is_released": true,
    "release_date": "2016-09-20",
    "overview": "Ghost Rider Robbie Reyes arrives, the Darkhold awakens, and the team enters the Framework simulation."
  },
  {
    "id": "marvel-tv-118",
    "universe": "mcu",
    "title": "Luke Cage (Season 1)",
    "media_type": "show",
    "release_order": 118,
    "chronological_order": 59,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67070,
    "poster_path": "https://image.tmdb.org/t/p/w500/qI85n9DBgRv6ghhJuzHOCaKXk3v.jpg",
    "is_released": true,
    "release_date": "2016-09-30",
    "overview": "Bulletproof hero Luke Cage defends Harlem from corrupt nightclub mogul Cottonmouth and Diamondback."
  },
  {
    "id": "marvel-tv-119",
    "universe": "mcu",
    "title": "Iron Fist (Season 1)",
    "media_type": "show",
    "release_order": 119,
    "chronological_order": 66,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 62127,
    "poster_path": "https://image.tmdb.org/t/p/w500/usGfoL4RfX15f1sQcX3Sgw4YRf4.jpg",
    "is_released": true,
    "release_date": "2017-03-17",
    "overview": "Danny Rand returns to New York after 15 years with the power of the Iron Fist to reclaim his legacy."
  },
  {
    "id": "marvel-tv-120",
    "universe": "mcu",
    "title": "The Defenders (Limited Series)",
    "media_type": "show",
    "release_order": 120,
    "chronological_order": 67,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 62285,
    "poster_path": "https://image.tmdb.org/t/p/w500/4COAMPA6LPkPBd1xdm9paN4LCD8.jpg",
    "is_released": true,
    "release_date": "2017-08-18",
    "overview": "Daredevil, Jessica Jones, Luke Cage, and Iron Fist unite to protect NYC from The Hand."
  },
  {
    "id": "marvel-tv-121",
    "universe": "mcu",
    "title": "Inhumans (Season 1)",
    "media_type": "show",
    "release_order": 121,
    "chronological_order": 71,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 68716,
    "poster_path": "https://image.tmdb.org/t/p/w500/doCIoaV9ffAJbK3TW2AsGp4ytOQ.jpg",
    "is_released": true,
    "release_date": "2017-09-29",
    "overview": "The Inhuman Royal Family is splintered by a military coup in Attilan and escapes to Hawaii."
  },
  {
    "id": "marvel-tv-122",
    "universe": "mcu",
    "title": "The Punisher (Season 1)",
    "media_type": "show",
    "release_order": 122,
    "chronological_order": 69,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67178,
    "poster_path": "https://image.tmdb.org/t/p/w500/dOkJ6TJKQjsz2XwXyp2VYpkeE5g.jpg",
    "is_released": true,
    "release_date": "2017-11-17",
    "overview": "Frank Castle uncovers a high-level military conspiracy running deeper than New York's criminal underworld."
  },
  {
    "id": "marvel-tv-123",
    "universe": "mcu",
    "title": "Runaways (Season 1)",
    "media_type": "show",
    "release_order": 123,
    "chronological_order": 75,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67466,
    "poster_path": "https://image.tmdb.org/t/p/w500/hMsaGkDyCM3Y3EWcdYK5Uu8qEok.jpg",
    "is_released": true,
    "release_date": "2017-11-21",
    "overview": "Six teenagers discover their parents are secretly members of a supervillain organization named Pride."
  },
  {
    "id": "marvel-tv-124",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 5)",
    "media_type": "show",
    "release_order": 124,
    "chronological_order": 85,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/zndNDiqH0SvIlFHURYCWY060qE8.jpg",
    "is_released": true,
    "release_date": "2017-12-01",
    "overview": "Coulson and the team are transported to a dystopian space station in the shattered future."
  },
  {
    "id": "marvel-tv-125",
    "universe": "mcu",
    "title": "Jessica Jones (Season 2)",
    "media_type": "show",
    "release_order": 125,
    "chronological_order": 76,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 38472,
    "poster_path": "https://image.tmdb.org/t/p/w500/tKirVNmDmwYjqehjPpyjr1n3U2F.jpg",
    "is_released": true,
    "release_date": "2018-03-08",
    "overview": "Jessica Jones investigates IGH, the secretive biotech organization responsible for giving her powers."
  },
  {
    "id": "marvel-tv-126",
    "universe": "mcu",
    "title": "Cloak & Dagger (Season 1)",
    "media_type": "show",
    "release_order": 126,
    "chronological_order": 78,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 66190,
    "poster_path": "https://image.tmdb.org/t/p/w500/nluzawv8wEo0AeECpnLo3wO2YLZ.jpg",
    "is_released": true,
    "release_date": "2018-06-07",
    "overview": "Tandy Bowen and Tyrone Johnson discover they have acquired superpowers that are mysteriously linked."
  },
  {
    "id": "marvel-tv-127",
    "universe": "mcu",
    "title": "Luke Cage (Season 2)",
    "media_type": "show",
    "release_order": 127,
    "chronological_order": 77,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67070,
    "poster_path": "https://image.tmdb.org/t/p/w500/o7ytmKNlOIcCyWXLdtDSRXi5Ruc.jpg",
    "is_released": true,
    "release_date": "2018-06-22",
    "overview": "Luke faces Bushmaster and Mariah Dillard as he struggles with the burden of Harlem's hero."
  },
  {
    "id": "marvel-tv-128",
    "universe": "mcu",
    "title": "Iron Fist (Season 2)",
    "media_type": "show",
    "release_order": 128,
    "chronological_order": 79,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 62127,
    "poster_path": "https://image.tmdb.org/t/p/w500/vXYvfCWvz5W0rErCpNIq09urhzW.jpg",
    "is_released": true,
    "release_date": "2018-09-07",
    "overview": "Danny Rand steps up to protect Chinatown alongside Colleen Wing and Misty Knight against Davos."
  },
  {
    "id": "marvel-tv-129",
    "universe": "mcu",
    "title": "Daredevil (Season 3)",
    "media_type": "show",
    "release_order": 129,
    "chronological_order": 80,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61889,
    "poster_path": "https://image.tmdb.org/t/p/w500/zH6sgePlr1XX0jSZypbfQmr70Lf.jpg",
    "is_released": true,
    "release_date": "2018-10-19",
    "overview": "A broken Matt Murdock re-emerges to stop a newly released Wilson Fisk and FBI assassin Bullseye."
  },
  {
    "id": "marvel-tv-130",
    "universe": "mcu",
    "title": "Runaways (Season 2)",
    "media_type": "show",
    "release_order": 130,
    "chronological_order": 81,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67466,
    "poster_path": "https://image.tmdb.org/t/p/w500/r2e50wFzTsMgsSVLAyIB8uX1EGu.jpg",
    "is_released": true,
    "release_date": "2018-12-21",
    "overview": "The kids must survive on their own in the Hostel while planning how to stop their parents' excavation."
  },
  {
    "id": "marvel-tv-131",
    "universe": "mcu",
    "title": "The Punisher (Season 2)",
    "media_type": "show",
    "release_order": 131,
    "chronological_order": 82,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67178,
    "poster_path": "https://image.tmdb.org/t/p/w500/agNYq5XZnGfmYetUMyyM2RdPY70.jpg",
    "is_released": true,
    "release_date": "2019-01-18",
    "overview": "Frank Castle protects a young runaway from fundamentalist hitman John Pilgrim and scarred Billy Russo."
  },
  {
    "id": "marvel-tv-132",
    "universe": "mcu",
    "title": "Cloak & Dagger (Season 2)",
    "media_type": "show",
    "release_order": 132,
    "chronological_order": 83,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 66190,
    "poster_path": "https://image.tmdb.org/t/p/w500/pYnRJuBPEqZO1o4fcxBTgmKNHfy.jpg",
    "is_released": true,
    "release_date": "2019-04-04",
    "overview": "Tyrone and Tandy take their vigilante crusade into New Orleans against human trafficking rings."
  },
  {
    "id": "marvel-tv-133",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 6)",
    "media_type": "show",
    "release_order": 133,
    "chronological_order": 91,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/QU0NjcvDonZLKhjRuxRv6AVo5l.jpg",
    "is_released": true,
    "release_date": "2019-05-10",
    "overview": "The team searches deep space for Fitz while an alien doppelgänger of Coulson named Sarge arrives on Earth."
  },
  {
    "id": "marvel-tv-134",
    "universe": "mcu",
    "title": "Jessica Jones (Season 3)",
    "media_type": "show",
    "release_order": 134,
    "chronological_order": 84,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 38472,
    "poster_path": "https://image.tmdb.org/t/p/w500/dOPx3bj3x6eXYXQJUUIHXvWRSSB.jpg",
    "is_released": true,
    "release_date": "2019-06-14",
    "overview": "Jessica and Trish Walker confront psychopathic serial killer Gregory Salinger, testing their sisterhood."
  },
  {
    "id": "marvel-tv-135",
    "universe": "mcu",
    "title": "Runaways (Season 3)",
    "media_type": "show",
    "release_order": 135,
    "chronological_order": 92,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67466,
    "poster_path": "https://image.tmdb.org/t/p/w500/m83skvEvoFQoo1szIMpFQ6kbCe6.jpg",
    "is_released": true,
    "release_date": "2019-12-13",
    "overview": "The Runaways face dark sorceress Morgan le Fay and team up with Cloak & Dagger in the Dark Dimension."
  },
  {
    "id": "marvel-tv-136",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 7)",
    "media_type": "show",
    "release_order": 136,
    "chronological_order": 93,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/qM95u55G8xVyfgoSZ2qTlY3MDl6.jpg",
    "is_released": true,
    "release_date": "2020-05-27",
    "overview": "The S.H.I.E.L.D. team time travels across the 20th century to prevent alien Chronicoms from erasing history."
  },
  {
    "id": "marvel-tv-137",
    "universe": "mcu",
    "title": "Helstrom (Season 1)",
    "media_type": "show",
    "release_order": 137,
    "chronological_order": 94,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 89456,
    "poster_path": "https://image.tmdb.org/t/p/w500/dBzcVyuWQeQgS2xaMFila9Wk3xE.jpg",
    "is_released": true,
    "release_date": "2020-10-16",
    "overview": "Daimon and Ana Helstrom track down the worst of humanity using their unique occult abilities."
  },
  {
    "id": "marvel-tv-138",
    "universe": "mcu",
    "title": "M.O.D.O.K. (Season 1)",
    "media_type": "show",
    "release_order": 138,
    "chronological_order": 129,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 86831,
    "poster_path": "https://image.tmdb.org/t/p/w500/rlrRI2b6RvM9I9xOBTKqcTaehkE.jpg",
    "is_released": true,
    "release_date": "2021-05-21",
    "overview": "Megalomanic supervillain M.O.D.O.K. balances running his bankrupt evil organization A.I.M. and family life."
  },
  {
    "id": "marvel-tv-139",
    "universe": "mcu",
    "title": "Hit-Monkey (Season 1)",
    "media_type": "show",
    "release_order": 139,
    "chronological_order": 130,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 125910,
    "poster_path": "https://image.tmdb.org/t/p/w500/s14pvZaymWeBjhJBUwaC0RKzvZz.jpg",
    "is_released": true,
    "release_date": "2021-11-17",
    "overview": "A wronged Japanese snow monkey goes on a revenge quest through Tokyo with the ghost of an American assassin."
  },
  {
    "id": "marvel-tv-140",
    "universe": "mcu",
    "title": "Hit-Monkey (Season 2)",
    "media_type": "show",
    "release_order": 140,
    "chronological_order": 131,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 125910,
    "poster_path": "https://image.tmdb.org/t/p/w500/fAS1b6UKKhLrK9hNybbD0s3ZRE2.jpg",
    "is_released": true,
    "release_date": "2024-07-15",
    "overview": "Monkey and Bryce move to New York City trying to escape their violent past while facing new supernatural threats."
  },
  {
    "id": "marvel-141",
    "universe": "mcu",
    "title": "Blade",
    "media_type": "movie",
    "release_order": 141,
    "chronological_order": 11,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 36647,
    "poster_path": "https://image.tmdb.org/t/p/w500/oVQ4Fv7a7n9m5A4s8d9f0g1h2j3.jpg",
    "is_released": true,
    "release_date": "1998-01-01",
    "overview": "A half-vampire, half-mortal man-turned-protector of the human race battles evil vampires."
  },
  {
    "id": "marvel-142",
    "universe": "mcu",
    "title": "Blade II",
    "media_type": "movie",
    "release_order": 142,
    "chronological_order": 13,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 36586,
    "poster_path": "https://image.tmdb.org/t/p/w500/p8Qy60OIf0OaJ29KPw6ld51MSP7.jpg",
    "is_released": true,
    "release_date": "2002-01-01",
    "overview": "Blade forms an uneasy alliance with the vampire council to combat the Reapers."
  },
  {
    "id": "marvel-143",
    "universe": "mcu",
    "title": "Hulk (2003)",
    "media_type": "movie",
    "release_order": 143,
    "chronological_order": 17,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 1927,
    "poster_path": "https://image.tmdb.org/t/p/w500/4zT4v8q9p7o2i3u5y6r1t8e9w0q.jpg",
    "is_released": true,
    "release_date": "2003-01-01",
    "overview": "Bruce Banner, a genetics researcher with a tragic past, suffers an accident that causes him to transform into a raging green monster."
  },
  {
    "id": "marvel-144",
    "universe": "mcu",
    "title": "The Punisher (2004)",
    "media_type": "movie",
    "release_order": 144,
    "chronological_order": 19,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 7220,
    "poster_path": "https://image.tmdb.org/t/p/w500/5k7T4v8q9p7o2i3u5y6r1t8e9w0.jpg",
    "is_released": true,
    "release_date": "2004-01-01",
    "overview": "An undercover FBI agent becomes a vengeful vigilante after his wife and son are murdered by a ruthless criminal."
  },
  {
    "id": "marvel-145",
    "universe": "mcu",
    "title": "Blade: Trinity",
    "media_type": "movie",
    "release_order": 145,
    "chronological_order": 21,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 36588,
    "poster_path": "https://image.tmdb.org/t/p/w500/7Yv7k8w9e5r4t3y2u1o9p7q6w5e.jpg",
    "is_released": true,
    "release_date": "2004-01-01",
    "overview": "Blade joins forces with the Nightstalkers to take down Dracula himself."
  },
  {
    "id": "marvel-146",
    "universe": "mcu",
    "title": "Man-Thing",
    "media_type": "special",
    "release_order": 146,
    "chronological_order": 24,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 24254,
    "poster_path": "https://image.tmdb.org/t/p/w500/1I7uztLcGmK8aE6r0VfA2yG8Uf.jpg",
    "is_released": true,
    "release_date": "2005-01-01",
    "overview": "Agents of an oil tycoon disappear in a swamp; the new sheriff investigates and finds a swamp creature."
  },
  {
    "id": "marvel-147",
    "universe": "mcu",
    "title": "Blade: The Series",
    "media_type": "show",
    "release_order": 147,
    "chronological_order": 26,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 2424,
    "poster_path": "https://image.tmdb.org/t/p/w500/2mtQwJKCSEHgMZaUNvB3QHx11fJ.jpg",
    "is_released": true,
    "release_date": "2006-01-01",
    "overview": "Blade continues his war against the vampires in Detroit with the help of Krista Starr."
  },
  {
    "id": "marvel-148",
    "universe": "mcu",
    "title": "Ghost Rider",
    "media_type": "movie",
    "release_order": 148,
    "chronological_order": 27,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 1250,
    "poster_path": "https://image.tmdb.org/t/p/w500/to0spRl1CMDvyUbvdIO320Q6RkG.jpg",
    "is_released": true,
    "release_date": "2007-01-01",
    "overview": "Stunt motorcyclist Johnny Blaze gives up his soul to become a hell-blazing vigilante."
  },
  {
    "id": "marvel-149",
    "universe": "mcu",
    "title": "Punisher: War Zone",
    "media_type": "movie",
    "release_order": 149,
    "chronological_order": 30,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 13056,
    "poster_path": "https://image.tmdb.org/t/p/w500/cCTjpXZqGtFfgxKa04CJ91GwBt.jpg",
    "is_released": true,
    "release_date": "2008-01-01",
    "overview": "Frank Castle wages a one-man war on the mob and battles disfigured mob boss Jigsaw."
  },
  {
    "id": "marvel-150",
    "universe": "mcu",
    "title": "Ghost Rider: Spirit of Vengeance",
    "media_type": "movie",
    "release_order": 150,
    "chronological_order": 31,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 71676,
    "poster_path": "https://image.tmdb.org/t/p/w500/xrIaa7m7pL2v0c1m6b7v8c9d0e.jpg",
    "is_released": true,
    "release_date": "2011-01-01",
    "overview": "Johnny Blaze is hiding out in Eastern Europe when he is called upon to stop the devil from taking over his son."
  }
];
