import { FranchiseMedia } from "../types";

export const MCU_SEED_DATA: FranchiseMedia[] = [
  {
    "id": "marvel-1",
    "universe": "mcu",
    "title": "Iron Man",
    "media_type": "movie",
    "release_order": 1,
    "chronological_order": 33,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 1726,
    "poster_path": "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    "is_released": true,
    "release_date": "2008-04-30",
    "overview": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil."
  },
  {
    "id": "marvel-2",
    "universe": "mcu",
    "title": "The Incredible Hulk",
    "media_type": "movie",
    "release_order": 2,
    "chronological_order": 35,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 1724,
    "poster_path": "https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
    "is_released": true,
    "release_date": "2008-06-12",
    "overview": "Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him."
  },
  {
    "id": "marvel-3",
    "universe": "mcu",
    "title": "Iron Man 2",
    "media_type": "movie",
    "release_order": 3,
    "chronological_order": 34,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 10138,
    "poster_path": "https://image.tmdb.org/t/p/w500/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg",
    "is_released": true,
    "release_date": "2010-04-28",
    "overview": "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful madman."
  },
  {
    "id": "marvel-4",
    "universe": "mcu",
    "title": "Thor",
    "media_type": "movie",
    "release_order": 4,
    "chronological_order": 38,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 10195,
    "poster_path": "https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
    "is_released": true,
    "release_date": "2011-04-21",
    "overview": "Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - is cast down to Earth."
  },
  {
    "id": "marvel-5",
    "universe": "mcu",
    "title": "Captain America: The First Avenger",
    "media_type": "movie",
    "release_order": 5,
    "chronological_order": 1,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 1771,
    "poster_path": "https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg",
    "is_released": true,
    "release_date": "2011-07-22",
    "overview": "During World War II, Steve Rogers is transformed into the super-soldier Captain America."
  },
  {
    "id": "marvel-6",
    "universe": "mcu",
    "title": "The Consultant",
    "media_type": "special",
    "release_order": 6,
    "chronological_order": 36,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 76122,
    "poster_path": "https://image.tmdb.org/t/p/w500/xqNLXUUvBnfVk6m3QFGGU0Grgs7.jpg",
    "is_released": true,
    "release_date": "2011-09-13",
    "overview": "Agents Coulson and Sitwell plot how to prevent Emil Blonsky from being released into the Avengers Initiative."
  },
  {
    "id": "marvel-7",
    "universe": "mcu",
    "title": "A Funny Thing Happened on the Way to Thor's Hammer",
    "media_type": "special",
    "release_order": 7,
    "chronological_order": 37,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 76535,
    "poster_path": "https://image.tmdb.org/t/p/w500/njrOqsmFH4pxBrhcoslqLfw2OGk.jpg",
    "is_released": true,
    "release_date": "2011-10-25",
    "overview": "Agent Phil Coulson stops at a convenience store on his way to New Mexico and handles a robbery."
  },
  {
    "id": "marvel-8",
    "universe": "mcu",
    "title": "The Avengers",
    "media_type": "movie",
    "release_order": 8,
    "chronological_order": 39,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 24428,
    "poster_path": "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    "is_released": true,
    "release_date": "2012-04-25",
    "overview": "Earth's Mightiest Heroes must come together and learn to fight as a team to stop Loki and an alien army."
  },
  {
    "id": "marvel-9",
    "universe": "mcu",
    "title": "Item 47",
    "media_type": "special",
    "release_order": 9,
    "chronological_order": 4,
    "phase_or_chapter": "Phase 1",
    "trakt_id": null,
    "tmdb_id": 119569,
    "poster_path": "https://image.tmdb.org/t/p/w500/hnSxG8clwLuAXEkp9emc8HCUcHD.jpg",
    "is_released": true,
    "release_date": "2012-08-29",
    "overview": "A down-on-their-luck couple finds a discarded Chitauri gun following the Battle of New York."
  },
  {
    "id": "marvel-10",
    "universe": "mcu",
    "title": "Iron Man 3",
    "media_type": "movie",
    "release_order": 10,
    "chronological_order": 40,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 68721,
    "poster_path": "https://image.tmdb.org/t/p/w500/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg",
    "is_released": true,
    "release_date": "2013-04-18",
    "overview": "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding."
  },
  {
    "id": "marvel-11",
    "universe": "mcu",
    "title": "Agent Carter",
    "media_type": "special",
    "release_order": 11,
    "chronological_order": 42,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 211387,
    "poster_path": "https://image.tmdb.org/t/p/w500/4vFKKWPvCVDJTOWiwReBfpAMScP.jpg",
    "is_released": true,
    "release_date": "2013-10-04",
    "overview": "Peggy Carter undertakes a solo field mission to retrieve the mysterious Zodiac key."
  },
  {
    "id": "marvel-12",
    "universe": "mcu",
    "title": "Thor: The Dark World",
    "media_type": "movie",
    "release_order": 12,
    "chronological_order": 43,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 76338,
    "poster_path": "https://image.tmdb.org/t/p/w500/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
    "is_released": true,
    "release_date": "2013-10-30",
    "overview": "Thor fights to restore order across the cosmos as an ancient race led by Malekith returns."
  },
  {
    "id": "marvel-13",
    "universe": "mcu",
    "title": "All Hail the King",
    "media_type": "special",
    "release_order": 13,
    "chronological_order": 45,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 253980,
    "poster_path": "https://image.tmdb.org/t/p/w500/y0QYZPWgeGKOvyrzi6Oz3aJPxJa.jpg",
    "is_released": true,
    "release_date": "2014-02-04",
    "overview": "Trevor Slattery is enjoying his newfound fame behind bars at Seagate Prison until an unexpected visitor arrives."
  },
  {
    "id": "marvel-14",
    "universe": "mcu",
    "title": "Captain America: The Winter Soldier",
    "media_type": "movie",
    "release_order": 14,
    "chronological_order": 47,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 100402,
    "poster_path": "https://image.tmdb.org/t/p/w500/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
    "is_released": true,
    "release_date": "2014-03-20",
    "overview": "Steve Rogers teams up with Natasha Romanoff and Sam Wilson to battle a powerful enemy within S.H.I.E.L.D."
  },
  {
    "id": "marvel-15",
    "universe": "mcu",
    "title": "Guardians of the Galaxy",
    "media_type": "movie",
    "release_order": 15,
    "chronological_order": 49,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 118340,
    "poster_path": "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    "is_released": true,
    "release_date": "2014-07-30",
    "overview": "An unruly band of galactic misfits must rally together to stop a cosmic warrior from cleansing the universe."
  },
  {
    "id": "marvel-16",
    "universe": "mcu",
    "title": "Avengers: Age of Ultron",
    "media_type": "movie",
    "release_order": 16,
    "chronological_order": 55,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 99861,
    "poster_path": "https://image.tmdb.org/t/p/w500/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
    "is_released": true,
    "release_date": "2015-04-22",
    "overview": "When Tony Stark jumpstarts a dormant peacekeeping program, things go awry and the Avengers face Ultron."
  },
  {
    "id": "marvel-17",
    "universe": "mcu",
    "title": "Ant-Man",
    "media_type": "movie",
    "release_order": 17,
    "chronological_order": 56,
    "phase_or_chapter": "Phase 2",
    "trakt_id": null,
    "tmdb_id": 102899,
    "poster_path": "https://image.tmdb.org/t/p/w500/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
    "is_released": true,
    "release_date": "2015-07-14",
    "overview": "Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang becomes Ant-Man."
  },
  {
    "id": "marvel-18",
    "universe": "mcu",
    "title": "Captain America: Civil War",
    "media_type": "movie",
    "release_order": 18,
    "chronological_order": 63,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 271110,
    "poster_path": "https://image.tmdb.org/t/p/w500/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
    "is_released": true,
    "release_date": "2016-04-27",
    "overview": "Political pressure mounts to install a system of accountability when the actions of the Avengers lead to collateral damage."
  },
  {
    "id": "marvel-19",
    "universe": "mcu",
    "title": "Doctor Strange",
    "media_type": "movie",
    "release_order": 19,
    "chronological_order": 69,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 284052,
    "poster_path": "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
    "is_released": true,
    "release_date": "2016-10-25",
    "overview": "After a horrific car crash robs him of his hands, brilliant neurosurgeon Stephen Strange learns the mystic arts."
  },
  {
    "id": "marvel-20",
    "universe": "mcu",
    "title": "Guardians of the Galaxy Vol. 2",
    "media_type": "movie",
    "release_order": 20,
    "chronological_order": 51,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 283995,
    "poster_path": "https://image.tmdb.org/t/p/w500/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
    "is_released": true,
    "release_date": "2017-04-25",
    "overview": "The Guardians must fight to keep their newfound family together as they unravel the mystery of Peter Quill's true parentage."
  },
  {
    "id": "marvel-21",
    "universe": "mcu",
    "title": "Spider-Man: Homecoming",
    "media_type": "movie",
    "release_order": 21,
    "chronological_order": 66,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 315635,
    "poster_path": "https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
    "is_released": true,
    "release_date": "2017-07-05",
    "overview": "Following the events of Captain America: Civil War, Peter Parker navigates high school life while fighting the Vulture."
  },
  {
    "id": "marvel-22",
    "universe": "mcu",
    "title": "Thor: Ragnarok",
    "media_type": "movie",
    "release_order": 22,
    "chronological_order": 73,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 284053,
    "poster_path": "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    "is_released": true,
    "release_date": "2017-10-02",
    "overview": "Thor is imprisoned on the other side of the universe and must race against time to stop Hela from destroying Asgard."
  },
  {
    "id": "marvel-23",
    "universe": "mcu",
    "title": "Black Panther",
    "media_type": "movie",
    "release_order": 23,
    "chronological_order": 65,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 284054,
    "poster_path": "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    "is_released": true,
    "release_date": "2018-02-13",
    "overview": "T'Challa returns home to the isolated, technologically advanced African nation of Wakanda to serve as its new king."
  },
  {
    "id": "marvel-24",
    "universe": "mcu",
    "title": "Avengers: Infinity War",
    "media_type": "movie",
    "release_order": 24,
    "chronological_order": 93,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 299536,
    "poster_path": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    "is_released": true,
    "release_date": "2018-04-25",
    "overview": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos."
  },
  {
    "id": "marvel-25",
    "universe": "mcu",
    "title": "Ant-Man and the Wasp",
    "media_type": "movie",
    "release_order": 25,
    "chronological_order": 92,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 363088,
    "poster_path": "https://image.tmdb.org/t/p/w500/cFQEO687n1K6umXbInzocxcnAQz.jpg",
    "is_released": true,
    "release_date": "2018-07-04",
    "overview": "Scott Lang grapples with the consequences of his choices as both a superhero and a father as he teams with Hope van Dyne."
  },
  {
    "id": "marvel-26",
    "universe": "mcu",
    "title": "Captain Marvel",
    "media_type": "movie",
    "release_order": 26,
    "chronological_order": 10,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 299537,
    "poster_path": "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg",
    "is_released": true,
    "release_date": "2019-03-06",
    "overview": "The story follows Carol Danvers as she becomes one of the universe's most powerful heroes when galactic war reaches Earth."
  },
  {
    "id": "marvel-27",
    "universe": "mcu",
    "title": "Avengers: Endgame",
    "media_type": "movie",
    "release_order": 27,
    "chronological_order": 100,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 299534,
    "poster_path": "https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
    "is_released": true,
    "release_date": "2019-04-24",
    "overview": "After the devastating events of Infinity War, the surviving Avengers assemble once more to reverse Thanos's actions."
  },
  {
    "id": "marvel-28",
    "universe": "mcu",
    "title": "Spider-Man: Far From Home",
    "media_type": "movie",
    "release_order": 28,
    "chronological_order": 106,
    "phase_or_chapter": "Phase 3",
    "trakt_id": null,
    "tmdb_id": 429617,
    "poster_path": "https://image.tmdb.org/t/p/w500/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    "is_released": true,
    "release_date": "2019-06-28",
    "overview": "Peter Parker and his friends go on a summer trip to Europe, where Peter finds himself helping Nick Fury against Elementals."
  },
  {
    "id": "marvel-29",
    "universe": "mcu",
    "title": "WandaVision (Season 1)",
    "media_type": "show",
    "release_order": 29,
    "chronological_order": 103,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 85271,
    "poster_path": "https://image.tmdb.org/t/p/w500/8BSVNGpZwZDScVv8e5S1c8XIjeJ.jpg",
    "is_released": true,
    "release_date": "2021-01-15",
    "overview": "Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.",
    "seasons": 1,
    "episodes": 9
  },
  {
    "id": "marvel-30",
    "universe": "mcu",
    "title": "The Falcon and the Winter Soldier (Season 1)",
    "media_type": "show",
    "release_order": 30,
    "chronological_order": 105,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 88396,
    "poster_path": "https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
    "is_released": true,
    "release_date": "2021-03-19",
    "overview": "Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.",
    "seasons": 1,
    "episodes": 6
  },
  {
    "id": "marvel-31",
    "universe": "mcu",
    "title": "Loki (Season 1)",
    "media_type": "show",
    "release_order": 31,
    "chronological_order": 101,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 84958,
    "poster_path": "https://image.tmdb.org/t/p/w500/8uVqe9ThcuYVNdh4O0kuijIWMLL.jpg",
    "is_released": true,
    "release_date": "2021-06-09",
    "overview": "Loki, the God of Mischief, steps out of his brother's shadow to embark on an adventure that takes place after the events of \"Avengers: Endgame.\"",
    "seasons": 1,
    "episodes": 6
  },
  {
    "id": "marvel-32",
    "universe": "mcu",
    "title": "Black Widow",
    "media_type": "movie",
    "release_order": 32,
    "chronological_order": 64,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 497698,
    "poster_path": "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    "is_released": true,
    "release_date": "2021-07-07",
    "overview": "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises."
  },
  {
    "id": "marvel-33",
    "universe": "mcu",
    "title": "What If...? (Season 1)",
    "media_type": "show",
    "release_order": 33,
    "chronological_order": 102,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 91363,
    "poster_path": "https://image.tmdb.org/t/p/w500/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg",
    "is_released": true,
    "release_date": "2021-08-11",
    "overview": "Taking inspiration from the comic books of the same name, each episode of this animated anthology series questions, revisits and twists classic Marvel Cinematic moments.",
    "seasons": 1,
    "episodes": 9
  },
  {
    "id": "marvel-34",
    "universe": "mcu",
    "title": "Shang-Chi and the Legend of the Ten Rings",
    "media_type": "movie",
    "release_order": 34,
    "chronological_order": 104,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 566525,
    "poster_path": "https://image.tmdb.org/t/p/w500/9f2Q0U3IOsLgrI2HkvldwSABZy5.jpg",
    "is_released": true,
    "release_date": "2021-09-01",
    "overview": "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization."
  },
  {
    "id": "marvel-35",
    "universe": "mcu",
    "title": "Eternals",
    "media_type": "movie",
    "release_order": 35,
    "chronological_order": 109,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 524434,
    "poster_path": "https://image.tmdb.org/t/p/w500/lFByFSLV5WDJEv3KabbdAF959F2.jpg",
    "is_released": true,
    "release_date": "2021-11-03",
    "overview": "The Eternals, a race of immortal beings with superhuman powers who have secretly lived on Earth for thousands of years, reunite."
  },
  {
    "id": "marvel-36",
    "universe": "mcu",
    "title": "Hawkeye (Season 1)",
    "media_type": "show",
    "release_order": 36,
    "chronological_order": 111,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 88329,
    "poster_path": "https://image.tmdb.org/t/p/w500/nGcqeKieycPFvsxOeLJssCTt3mL.jpg",
    "is_released": true,
    "release_date": "2021-11-24",
    "overview": "Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas. Possible? Maybe with the help of Kate Bishop, a 22-year-old archer with dreams of becoming a superhero. The two are forced to work together when a presence from Barton’s past threatens to derail far more than the festive spirit.",
    "seasons": 1,
    "episodes": 6
  },
  {
    "id": "marvel-37",
    "universe": "mcu",
    "title": "Spider-Man: No Way Home",
    "media_type": "movie",
    "release_order": 37,
    "chronological_order": 108,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 634649,
    "poster_path": "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    "is_released": true,
    "release_date": "2021-12-15",
    "overview": "Peter Parker seeks Doctor Strange's help to make everyone forget he is Spider-Man, which breaks the multiverse open."
  },
  {
    "id": "marvel-38",
    "universe": "mcu",
    "title": "Moon Knight (Season 1)",
    "media_type": "show",
    "release_order": 38,
    "chronological_order": 112,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 92749,
    "poster_path": "https://image.tmdb.org/t/p/w500/zPFm8ZbvdzoViRHnLi8cH7TBS1B.jpg",
    "is_released": true,
    "release_date": "2022-03-30",
    "overview": "When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc’s enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.",
    "seasons": 1,
    "episodes": 6
  },
  {
    "id": "marvel-39",
    "universe": "mcu",
    "title": "Doctor Strange in the Multiverse of Madness",
    "media_type": "movie",
    "release_order": 39,
    "chronological_order": 110,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 453395,
    "poster_path": "https://image.tmdb.org/t/p/w500/ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg",
    "is_released": true,
    "release_date": "2022-05-04",
    "overview": "Doctor Strange traverses the mind-bending and dangerous alternate realities of the Multiverse with America Chavez."
  },
  {
    "id": "marvel-40",
    "universe": "mcu",
    "title": "Ms. Marvel (Season 1)",
    "media_type": "show",
    "release_order": 40,
    "chronological_order": 116,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 92782,
    "poster_path": "https://image.tmdb.org/t/p/w500/4qoFtoPvFGjlIXYfFVNKhOwZ6zD.jpg",
    "is_released": true,
    "release_date": "2022-06-08",
    "overview": "A great student, avid gamer, and voracious fan-fic scribe, Kamala Khan has a special affinity for superheroes, particularly Captain Marvel. However, she struggles to fit in at home and at school — that is, until she gets superpowers like the heroes she’s always looked up to. Life is easier with superpowers, right?",
    "seasons": 1,
    "episodes": 6
  },
  {
    "id": "marvel-41",
    "universe": "mcu",
    "title": "Thor: Love and Thunder",
    "media_type": "movie",
    "release_order": 41,
    "chronological_order": 117,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 616037,
    "poster_path": "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    "is_released": true,
    "release_date": "2022-07-06",
    "overview": "Thor embarks on a journey unlike anything he's ever faced -- a quest for inner peace. But his retirement is interrupted by Gorr."
  },
  {
    "id": "marvel-42",
    "universe": "mcu",
    "title": "I Am Groot (Season 1)",
    "media_type": "show",
    "release_order": 42,
    "chronological_order": 50,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 232125,
    "poster_path": "https://image.tmdb.org/t/p/w500/3QfQYECgu6DX5UUWCBvv1Fl0BAJ.jpg",
    "is_released": true,
    "release_date": "2021-09-22",
    "overview": "This anthology of animated shorts from around the world celebrates the mythos of Star Wars through unique cultural lenses."
  },
  {
    "id": "marvel-43",
    "universe": "mcu",
    "title": "She-Hulk: Attorney at Law (Season 1)",
    "media_type": "show",
    "release_order": 43,
    "chronological_order": 115,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 92783,
    "poster_path": "https://image.tmdb.org/t/p/w500/41Iekrap0j80u808Z2004t88r6o.jpg",
    "is_released": true,
    "release_date": "2022-08-18",
    "overview": "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
    "seasons": 1,
    "episodes": 9
  },
  {
    "id": "marvel-44",
    "universe": "mcu",
    "title": "Werewolf by Night",
    "media_type": "special",
    "release_order": 44,
    "chronological_order": 118,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 894205,
    "poster_path": "https://image.tmdb.org/t/p/w500/mvIvNKRIJPPS7WSFarFhOAGIVnU.jpg",
    "is_released": true,
    "release_date": "2022-09-25",
    "overview": "On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the Bloodstone Temple."
  },
  {
    "id": "marvel-45",
    "universe": "mcu",
    "title": "Black Panther: Wakanda Forever",
    "media_type": "movie",
    "release_order": 45,
    "chronological_order": 113,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 505642,
    "poster_path": "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    "is_released": true,
    "release_date": "2022-11-09",
    "overview": "Queen Ramonda, Shuri, M'Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers and Namor."
  },
  {
    "id": "marvel-46",
    "universe": "mcu",
    "title": "The Guardians of the Galaxy Holiday Special",
    "media_type": "special",
    "release_order": 46,
    "chronological_order": 119,
    "phase_or_chapter": "Phase 4",
    "trakt_id": null,
    "tmdb_id": 774752,
    "poster_path": "https://image.tmdb.org/t/p/w500/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
    "is_released": true,
    "release_date": "2022-11-24",
    "overview": "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present."
  },
  {
    "id": "marvel-47",
    "universe": "mcu",
    "title": "Ant-Man and the Wasp: Quantumania",
    "media_type": "movie",
    "release_order": 47,
    "chronological_order": 120,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 640146,
    "poster_path": "https://image.tmdb.org/t/p/w500/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
    "is_released": true,
    "release_date": "2023-02-15",
    "overview": "Super-Hero partners Scott Lang and Hope van Dyne return to continue their adventures as Ant-Man and the Wasp in the Quantum Realm."
  },
  {
    "id": "marvel-48",
    "universe": "mcu",
    "title": "Guardians of the Galaxy Vol. 3",
    "media_type": "movie",
    "release_order": 48,
    "chronological_order": 121,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 447365,
    "poster_path": "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    "is_released": true,
    "release_date": "2023-05-03",
    "overview": "Peter Quill must rally his team around him to defend the universe along with protecting one of their own: Rocket."
  },
  {
    "id": "marvel-49",
    "universe": "mcu",
    "title": "Secret Invasion (Season 1)",
    "media_type": "show",
    "release_order": 49,
    "chronological_order": 122,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 114479,
    "poster_path": "https://image.tmdb.org/t/p/w500/uk60hHZW6Svot6DLPLKwAkD9BlN.jpg",
    "is_released": true,
    "release_date": "2024-06-04",
    "overview": "A hundred years before the rise of the Empire, the Jedi Order and the Galactic Republic have prospered for centuries without war. During this time, an investigation into a shocking crime spree pits a Jedi Master against a dangerous warrior from his past.",
    "seasons": 1,
    "episodes": 8
  },
  {
    "id": "marvel-50",
    "universe": "mcu",
    "title": "I Am Groot (Season 2)",
    "media_type": "show",
    "release_order": 50,
    "chronological_order": 52,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 232125,
    "poster_path": "https://image.tmdb.org/t/p/w500/lYwFSsP4KsoRhOLhJvBFp3GEGEm.jpg",
    "is_released": true,
    "release_date": "2023-05-04",
    "overview": "This anthology of animated shorts from around the world celebrates the mythos of Star Wars through unique cultural lenses."
  },
  {
    "id": "marvel-51",
    "universe": "mcu",
    "title": "Loki (Season 2)",
    "media_type": "show",
    "release_order": 51,
    "chronological_order": 124,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 84958,
    "poster_path": "https://image.tmdb.org/t/p/w500/oJdVHUYrjdS2IqiNztVIP4GPB1p.jpg",
    "is_released": true,
    "release_date": "2023-10-05",
    "overview": "In the aftermath of Season 1, Loki finds himself in a battle for the soul of the Time Variance Authority. Along with Mobius, Hunter B-15 and a team of new and returning characters, Loki navigates an ever-expanding and increasingly dangerous multiverse in search of Sylvie, Judge Renslayer, Miss Minutes and the truth of what it means to possess free will and glorious purpose.",
    "seasons": 2,
    "episodes": 6
  },
  {
    "id": "marvel-52",
    "universe": "mcu",
    "title": "The Marvels",
    "media_type": "movie",
    "release_order": 52,
    "chronological_order": 123,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 609681,
    "poster_path": "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
    "is_released": true,
    "release_date": "2023-11-08",
    "overview": "Carol Danvers, Kamala Khan, and Monica Rambeau discover their powers have become entangled, swapping places whenever they are used."
  },
  {
    "id": "marvel-53",
    "universe": "mcu",
    "title": "What If...? (Season 2)",
    "media_type": "show",
    "release_order": 53,
    "chronological_order": 125,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 91363,
    "poster_path": "https://image.tmdb.org/t/p/w500/3yhoq5LVMgKy9rEriH6ytq9BoJV.jpg",
    "is_released": true,
    "release_date": "2023-12-22",
    "overview": "Season two continues the journey as The Watcher guides viewers through the vast multiverse, introducing brand new and familiar faces throughout the MCU.",
    "seasons": 2,
    "episodes": 9
  },
  {
    "id": "marvel-54",
    "universe": "mcu",
    "title": "Echo (Season 1)",
    "media_type": "show",
    "release_order": 54,
    "chronological_order": 114,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 122226,
    "poster_path": "https://image.tmdb.org/t/p/w500/eVqz9zgvGYVqvHOg1QlHWrGTpz3.jpg",
    "is_released": true,
    "release_date": "2024-01-09",
    "overview": "Pursued by Wilson Fisk's criminal empire, Maya's journey brings her home and she must confront her own family and legacy.",
    "seasons": 1,
    "episodes": 5
  },
  {
    "id": "marvel-xmen97-s1",
    "universe": "mcu",
    "title": "X-Men '97 (Season 1)",
    "media_type": "show",
    "release_order": 55,
    "chronological_order": 11,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 138502,
    "poster_path": "https://image.tmdb.org/t/p/w500/383PV0WolYYQvTriH0NfvMUA28R.jpg",
    "is_released": true,
    "release_date": "2024-03-20",
    "overview": "A band of mutants use their uncanny gifts to protect a world that hates and fears them, challenged like never before and forced to face a dangerous and unexpected new future in 1997.",
    "seasons": 1,
    "episodes": 10
  },
  {
    "id": "marvel-55",
    "universe": "mcu",
    "title": "Deadpool & Wolverine",
    "media_type": "movie",
    "release_order": 56,
    "chronological_order": 130,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 533535,
    "poster_path": "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    "is_released": true,
    "release_date": "2024-07-24",
    "overview": "A listless Wade Wilson toils away in civilian life until a threat to his home world sends him on a mission with Wolverine."
  },
  {
    "id": "marvel-56",
    "universe": "mcu",
    "title": "Agatha All Along (Season 1)",
    "media_type": "show",
    "release_order": 57,
    "chronological_order": 131,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 138501,
    "poster_path": "https://image.tmdb.org/t/p/w500/cXEE6EsLJNwEwOCedX04Uixfq5O.jpg",
    "is_released": true,
    "release_date": "2024-09-18",
    "overview": "The infamous Agatha Harkness finds herself down and out of power after a suspicious goth Teen helps break her free from a distorted spell. Her interest is piqued when he begs her to take him on the legendary Witches' Road, a magical gauntlet of trials that, if survived, rewards a witch with what they're missing. Together, Agatha and this mysterious Teen pull together a desperate coven, and set off down, down, down the Road...",
    "seasons": 1,
    "episodes": 9
  },
  {
    "id": "marvel-57",
    "universe": "mcu",
    "title": "What If...? (Season 3)",
    "media_type": "show",
    "release_order": 58,
    "chronological_order": 132,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 91363,
    "poster_path": "https://image.tmdb.org/t/p/w500/bbGeKXKoualYRYqvFYiv8fPZK0d.jpg",
    "is_released": true,
    "release_date": "2024-12-22",
    "overview": "Season 3 follows classic characters as they make unexpected choices that will mutate their worlds into spectacular alternate versions of the MCU.",
    "seasons": 3,
    "episodes": 8
  },
  {
    "id": "marvel-58",
    "universe": "mcu",
    "title": "Your Friendly Neighborhood Spider-Man (Season 1)",
    "media_type": "show",
    "release_order": 59,
    "chronological_order": 136,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 138503,
    "poster_path": "https://image.tmdb.org/t/p/w500/bifTEU63VFt2ugUte9LqNBb1Dno.jpg",
    "is_released": true,
    "release_date": "2025-01-27",
    "overview": "Peter Parker is on his way to becoming a hero, but his path to get there is anything but ordinary.",
    "seasons": 1,
    "episodes": 10
  },
  {
    "id": "marvel-59",
    "universe": "mcu",
    "title": "Captain America: Brave New World",
    "media_type": "movie",
    "release_order": 60,
    "chronological_order": 137,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 822119,
    "poster_path": "https://image.tmdb.org/t/p/w500/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
    "is_released": true,
    "release_date": "2025-02-12",
    "overview": "Sam Wilson officially takes up the mantle of Captain America and navigates an international crisis."
  },
  {
    "id": "marvel-60",
    "universe": "mcu",
    "title": "Daredevil: Born Again (Season 1)",
    "media_type": "show",
    "release_order": 61,
    "chronological_order": 138,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 202555,
    "poster_path": "https://image.tmdb.org/t/p/w500/9lLuhV703HGCbnz6FxnqCwIwzAZ.jpg",
    "is_released": true,
    "release_date": "2025-03-04",
    "overview": "It has been a year since Matt Murdock retired from crime fighting as Daredevil. Wilson Fisk has been elected mayor of New York City after running on an anti-vigilante platform. The Kingpin may force Daredevil to come out of retirement.",
    "seasons": 1,
    "episodes": 9
  },
  {
    "id": "marvel-61",
    "universe": "mcu",
    "title": "Thunderbolts*",
    "media_type": "movie",
    "release_order": 62,
    "chronological_order": 139,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 986056,
    "poster_path": "https://image.tmdb.org/t/p/w500/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
    "is_released": true,
    "release_date": "2025-04-30",
    "overview": "An irreverent team-up featuring depressed assassin Yelena Belova alongside the MCU’s least anticipated band of misfits."
  },
  {
    "id": "marvel-62",
    "universe": "mcu",
    "title": "Ironheart (Season 1)",
    "media_type": "show",
    "release_order": 63,
    "chronological_order": 140,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 114471,
    "poster_path": "https://image.tmdb.org/t/p/w500/dOh6MJpdlQhYpLBhzhNQeYGKTZ5.jpg",
    "is_released": true,
    "release_date": "2019-11-03",
    "overview": "\"Detective College\", as a derivative of the fifth season of \"Who's the Murderer\", is a star reasoning variety show where selected detective assistants launched by Mango TV. The star guests determine the number of advances by rolling the dice on the checkerboard. When the game is triggered, the corresponding game needs to be completed. The first guest to reach the end becomes the current No.1. The program combines the form of team battles and individual battles to inspire the star guests ’IQ and Contest of logical ability. No. 1 selected in the show will appear on the scene of the fifth season of \"Who's the Murderer\". \"Detective College\" consists of Pu Yixing, Zhou Junwei, Tang Jiuzhou, Qi Sijun, Shi Kai, Guo Wentao, Shao Mingming, etc., and premiered on November 3, 2019."
  },
  {
    "id": "marvel-63",
    "universe": "mcu",
    "title": "The Fantastic Four: First Steps",
    "media_type": "movie",
    "release_order": 64,
    "chronological_order": 141,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 617126,
    "poster_path": "https://image.tmdb.org/t/p/w500/nf5qaSEvyYSNeFH0YhSs5EsBLX9.jpg",
    "is_released": true,
    "release_date": "2025-07-23",
    "overview": "Set against the vibrant backdrop of a 1960s-inspired retro-futuristic world, Marvel's First Family balances superhero life and Galactus."
  },
  {
    "id": "marvel-64",
    "universe": "mcu",
    "title": "Eyes of Wakanda (Season 1)",
    "media_type": "show",
    "release_order": 65,
    "chronological_order": 142,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 241388,
    "poster_path": "https://image.tmdb.org/t/p/w500/bG23nZW96LxmWkJjsagRZI9hF6t.jpg",
    "is_released": true,
    "release_date": "2024-05-08",
    "overview": "A ragtag crew of podcasters sets out to investigate mysterious disappearances from decades earlier in a charming Irish town with dark, dreadful secrets."
  },
  {
    "id": "marvel-65",
    "universe": "mcu",
    "title": "Marvel Zombies (Season 1)",
    "media_type": "show",
    "release_order": 66,
    "chronological_order": 143,
    "phase_or_chapter": "Phase 5",
    "trakt_id": null,
    "tmdb_id": 138505,
    "poster_path": "https://image.tmdb.org/t/p/w500/wofiHMsXxmp0lTafcBrgciSxBVx.jpg",
    "is_released": true,
    "release_date": "2025-09-24",
    "overview": "After the Avengers are overtaken by a zombie plague, a desperate group of survivors discover the key to bringing an end to the super-powered undead, racing across a dystopian landscape and risking life and limb to save their world.",
    "seasons": 1,
    "episodes": 4
  },
  {
    "id": "marvel-66",
    "universe": "mcu",
    "title": "Wonder Man (Season 1)",
    "media_type": "show",
    "release_order": 67,
    "chronological_order": 144,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 198178,
    "poster_path": "https://image.tmdb.org/t/p/w500/o2obeixL5uePdveNyv3oYVaoAC3.jpg",
    "is_released": true,
    "release_date": "2023-01-15",
    "overview": "Nanotechnology researcher Wang Miao is taken to the Joint Operations Center by police officer Shi Qiang, who's investigating the mysterious suicide wave among scientists worldwide.  He is recruited to sneak into an organization called the Frontiers of Science to help the investigation. When Wang Miao is contacted by the leader of the organization, Shen Yufei, she introduces him to a sophisticated VR video game called Three-Body, but soon he discovers that it's more than just a game."
  },
  {
    "id": "marvel-67",
    "universe": "mcu",
    "title": "Daredevil: Born Again (Season 2)",
    "media_type": "show",
    "release_order": 68,
    "chronological_order": 145,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 202555,
    "poster_path": "https://image.tmdb.org/t/p/w500/timvsedxh5ce795tsv6EDTZmmXW.jpg",
    "is_released": false,
    "release_date": "2026-03-24",
    "overview": "Mayor Wilson Fisk crushes New York City underfoot as he hunts down public enemy number one, the Hell's Kitchen vigilante known as Daredevil. But beneath the horned mask, Matt Murdock will try to fight back from the shadows to tear down the Kingpin's corrupt empire and redeem his home. Resist. Rebel. Rebuild.",
    "seasons": 2,
    "episodes": 8
  },
  {
    "id": "marvel-68",
    "universe": "mcu",
    "title": "The Punisher: One Last Kill",
    "media_type": "special",
    "release_order": 69,
    "chronological_order": 146,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": null,
    "poster_path": "https://image.tmdb.org/t/p/w500/dOkJ6TJKQjsz2XwXyp2VYpkeE5g.jpg",
    "is_released": false,
    "release_date": "2026-04-01",
    "overview": "Frank Castle returns for a definitive special presentation mission."
  },
  {
    "id": "marvel-69",
    "universe": "mcu",
    "title": "Spider-Man: Brand New Day",
    "media_type": "movie",
    "release_order": 70,
    "chronological_order": 147,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 969681,
    "poster_path": "https://image.tmdb.org/t/p/w500/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg",
    "is_released": false,
    "release_date": "2026-07-29",
    "overview": "Peter Parker navigates a fresh chapter as a street-level Spider-Man in New York City."
  },
  {
    "id": "marvel-70",
    "universe": "mcu",
    "title": "VisionQuest (Season 1)",
    "media_type": "show",
    "release_order": 71,
    "chronological_order": 149,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 213375,
    "poster_path": "https://image.tmdb.org/t/p/w500/xK27l5uwaVyZSlENWnmLlWwDQNS.jpg",
    "is_released": false,
    "release_date": "2026-09-01",
    "overview": "White Vision embarks on a journey of self-discovery to regain his memories and humanity."
  },
  {
    "id": "marvel-71",
    "universe": "mcu",
    "title": "Avengers: Doomsday",
    "media_type": "movie",
    "release_order": 72,
    "chronological_order": 150,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 1003596,
    "poster_path": "https://image.tmdb.org/t/p/w500/jzPwsojjFStf5lR5Nm07w2hH56G.jpg",
    "is_released": false,
    "release_date": "2026-12-16",
    "overview": "Earth's mightiest heroes clash with Doctor Doom in a universe-altering showdown."
  },
  {
    "id": "marvel-72",
    "universe": "mcu",
    "title": "Your Friendly Neighborhood Spider-Man (Season 2)",
    "media_type": "show",
    "release_order": 73,
    "chronological_order": 151,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 138503,
    "poster_path": "https://image.tmdb.org/t/p/w500/kjcsNeqF52YUQ2rUBGLMHwLkxvR.jpg",
    "is_released": false,
    "release_date": "2026-11-01",
    "overview": "The second season following Peter Parker's high school superhero journey."
  },
  {
    "id": "marvel-73",
    "universe": "mcu",
    "title": "Daredevil: Born Again (Season 3)",
    "media_type": "show",
    "release_order": 74,
    "chronological_order": 152,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 202555,
    "poster_path": "https://image.tmdb.org/t/p/w500/xDUoAsU8lQHOOoRkFiBuarmACDN.jpg",
    "is_released": false,
    "release_date": "2027-01-01",
    "overview": "The third season of Marvel Studios' Daredevil: Born Again."
  },
  {
    "id": "marvel-74",
    "universe": "mcu",
    "title": "Avengers: Secret Wars",
    "media_type": "movie",
    "release_order": 75,
    "chronological_order": 153,
    "phase_or_chapter": "Phase 6 & Beyond",
    "trakt_id": null,
    "tmdb_id": 1003598,
    "poster_path": "https://image.tmdb.org/t/p/w500/f0YBuh4hyiAheXhh4JnJWoKi9g5.jpg",
    "is_released": false,
    "release_date": "2027-12-15",
    "overview": "The catastrophic culmination of the Multiverse Saga as realities collide on Battleworld."
  },
  {
    "id": "marvel-75",
    "universe": "mcu",
    "title": "Venom",
    "media_type": "movie",
    "release_order": 76,
    "chronological_order": 90,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 335983,
    "poster_path": "https://image.tmdb.org/t/p/w500/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
    "is_released": true,
    "release_date": "2018-09-28",
    "overview": "Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of an alien symbiote."
  },
  {
    "id": "marvel-76",
    "universe": "mcu",
    "title": "Venom: Let There Be Carnage",
    "media_type": "movie",
    "release_order": 77,
    "chronological_order": 107,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 580489,
    "poster_path": "https://image.tmdb.org/t/p/w500/pzKsRuKLFmYrW5Q0q8E8G78Tcgo.jpg",
    "is_released": true,
    "release_date": "2021-09-30",
    "overview": "Eddie Brock struggles to adjust to life as the host of the alien symbiote Venom, while serial killer Cletus Kasady becomes Carnage."
  },
  {
    "id": "marvel-77",
    "universe": "mcu",
    "title": "Morbius",
    "media_type": "movie",
    "release_order": 78,
    "chronological_order": 127,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 526896,
    "poster_path": "https://image.tmdb.org/t/p/w500/Av8Z2jZhEm1FLkFzMThzz9hndJF.jpg",
    "is_released": true,
    "release_date": "2022-03-30",
    "overview": "Dangerously ill with a rare blood disorder, Dr. Morbius attempts a desperate gamble that unleashes a darkness inside him."
  },
  {
    "id": "marvel-78",
    "universe": "mcu",
    "title": "Madame Web",
    "media_type": "movie",
    "release_order": 79,
    "chronological_order": 19,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 634492,
    "poster_path": "https://image.tmdb.org/t/p/w500/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg",
    "is_released": true,
    "release_date": "2024-02-14",
    "overview": "Cassandra Webb is a New York City paramedic who develops the ability to see the future."
  },
  {
    "id": "marvel-79",
    "universe": "mcu",
    "title": "Venom: The Last Dance",
    "media_type": "movie",
    "release_order": 80,
    "chronological_order": 128,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 912649,
    "poster_path": "https://image.tmdb.org/t/p/w500/vGXptEdgZIhPg3cGlc7e8sNPC2e.jpg",
    "is_released": true,
    "release_date": "2024-10-22",
    "overview": "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision."
  },
  {
    "id": "marvel-80",
    "universe": "mcu",
    "title": "Kraven the Hunter",
    "media_type": "movie",
    "release_order": 81,
    "chronological_order": 129,
    "phase_or_chapter": "Sony's Spider-Man Universe (SSU)",
    "trakt_id": null,
    "tmdb_id": 539972,
    "poster_path": "https://image.tmdb.org/t/p/w500/1GvBhRxY6MELDfxFrete6BNhBB5.jpg",
    "is_released": true,
    "release_date": "2024-11-13",
    "overview": "Kraven's complex relationship with his ruthless father Nikolai Kravinoff starts him down a path of vengeance."
  },
  {
    "id": "marvel-81",
    "universe": "mcu",
    "title": "Spider-Man: Into the Spider-Verse",
    "media_type": "movie",
    "release_order": 82,
    "chronological_order": 91,
    "phase_or_chapter": "Sony's Spider-Verse Animated",
    "trakt_id": null,
    "tmdb_id": 324857,
    "poster_path": "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    "is_released": true,
    "release_date": "2018-12-06",
    "overview": "Teen Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from across parallel universes."
  },
  {
    "id": "marvel-82",
    "universe": "mcu",
    "title": "Spider-Man: Across the Spider-Verse",
    "media_type": "movie",
    "release_order": 83,
    "chronological_order": 126,
    "phase_or_chapter": "Sony's Spider-Verse Animated",
    "trakt_id": null,
    "tmdb_id": 569094,
    "poster_path": "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    "is_released": true,
    "release_date": "2023-05-31",
    "overview": "Miles Morales catapults across the Multiverse, where he encounters the Spider-Society and must redefine what it means to be a hero."
  },
  {
    "id": "marvel-83",
    "universe": "mcu",
    "title": "Spider-Man: Beyond the Spider-Verse",
    "media_type": "movie",
    "release_order": 84,
    "chronological_order": 148,
    "phase_or_chapter": "Sony's Spider-Verse Animated",
    "trakt_id": null,
    "tmdb_id": 911916,
    "poster_path": "https://image.tmdb.org/t/p/w500/9KAe39xqyZnv9J4W3DRGdQqX82h.jpg",
    "is_released": false,
    "release_date": "2027-06-17",
    "overview": "The epic conclusion to the Spider-Verse trilogy as Miles Morales battles across dimensions to save the multiverse and his family."
  },
  {
    "id": "marvel-84",
    "universe": "mcu",
    "title": "Spider-Man",
    "media_type": "movie",
    "release_order": 85,
    "chronological_order": 15,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 557,
    "poster_path": "https://image.tmdb.org/t/p/w500/or6XJBVpcEbIkma0V9zshnbEtx4.jpg",
    "is_released": true,
    "release_date": "2002-05-01",
    "overview": "After being bitten by a genetically altered spider, high school student Peter Parker gains superpowers to fight the Green Goblin."
  },
  {
    "id": "marvel-85",
    "universe": "mcu",
    "title": "Spider-Man 2",
    "media_type": "movie",
    "release_order": 86,
    "chronological_order": 21,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 558,
    "poster_path": "https://image.tmdb.org/t/p/w500/aGuvNAaaZuWXYQQ6N2v7DeuP6mB.jpg",
    "is_released": true,
    "release_date": "2004-06-25",
    "overview": "Peter Parker is beset with troubles in his failing personal life as he battles a brilliant scientist named Doctor Octopus."
  },
  {
    "id": "marvel-86",
    "universe": "mcu",
    "title": "Spider-Man 3",
    "media_type": "movie",
    "release_order": 87,
    "chronological_order": 29,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 559,
    "poster_path": "https://image.tmdb.org/t/p/w500/sJMTTGjtjvrMZ7G0oP9D13wNUum.jpg",
    "is_released": true,
    "release_date": "2007-05-01",
    "overview": "The seemingly invincible Spider-Man goes up against an alien symbiote and villains Sandman and Venom."
  },
  {
    "id": "marvel-87",
    "universe": "mcu",
    "title": "The Amazing Spider-Man",
    "media_type": "movie",
    "release_order": 88,
    "chronological_order": 41,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 1930,
    "poster_path": "https://image.tmdb.org/t/p/w500/jexoNYnPd6vVrmygwF6QZmWPFdu.jpg",
    "is_released": true,
    "release_date": "2012-06-23",
    "overview": "Peter Parker tries to find out who he is and how he got to be the person he is today while battling the Lizard."
  },
  {
    "id": "marvel-88",
    "universe": "mcu",
    "title": "The Amazing Spider-Man 2",
    "media_type": "movie",
    "release_order": 89,
    "chronological_order": 48,
    "phase_or_chapter": "Sony's Legacy Spider-Man",
    "trakt_id": null,
    "tmdb_id": 102382,
    "poster_path": "https://image.tmdb.org/t/p/w500/dGjoPttcbKR5VWg1jQuNFB247KL.jpg",
    "is_released": true,
    "release_date": "2014-04-16",
    "overview": "When New York is put under siege by Oscorp, it is up to Spider-Man to save the city he swore to protect as well as the ones he loves."
  },
  {
    "id": "marvel-89",
    "universe": "mcu",
    "title": "X-Men",
    "media_type": "movie",
    "release_order": 90,
    "chronological_order": 13,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 36657,
    "poster_path": "https://image.tmdb.org/t/p/w500/bRDAc4GogyS9ci3ow7UnInOcriN.jpg",
    "is_released": true,
    "release_date": "2000-07-13",
    "overview": "Two mutants come to a private academy for their kind whose resident superhero team must oppose a terrorist organization."
  },
  {
    "id": "marvel-90",
    "universe": "mcu",
    "title": "X2: X-Men United",
    "media_type": "movie",
    "release_order": 91,
    "chronological_order": 17,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 36658,
    "poster_path": "https://image.tmdb.org/t/p/w500/bst4alFUXCxISwdRUKSMhhkrX1M.jpg",
    "is_released": true,
    "release_date": "2003-04-27",
    "overview": "The X-Men band together to find a mutant assassin who has made an attempt on the President's life."
  },
  {
    "id": "marvel-91",
    "universe": "mcu",
    "title": "X-Men: The Last Stand",
    "media_type": "movie",
    "release_order": 92,
    "chronological_order": 26,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 36668,
    "poster_path": "https://image.tmdb.org/t/p/w500/a2xicU8DpKtRizOHjQLC1JyCSRS.jpg",
    "is_released": true,
    "release_date": "2006-05-24",
    "overview": "When a cure is found to treat mutations, lines are drawn among the X-Men and The Brotherhood of Mutants."
  },
  {
    "id": "marvel-92",
    "universe": "mcu",
    "title": "X-Men Origins: Wolverine",
    "media_type": "movie",
    "release_order": 93,
    "chronological_order": 7,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 2080,
    "poster_path": "https://image.tmdb.org/t/p/w500/yj8LbTju1p7CUJg7US2unSBk33s.jpg",
    "is_released": true,
    "release_date": "2009-04-28",
    "overview": "A look at Wolverine's early life, in particular his time with the government squad Team X and the Weapon X program."
  },
  {
    "id": "marvel-93",
    "universe": "mcu",
    "title": "X-Men: First Class",
    "media_type": "movie",
    "release_order": 94,
    "chronological_order": 5,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 49538,
    "poster_path": "https://image.tmdb.org/t/p/w500/hNEokmUke0dazoBhttFN0o3L7Xv.jpg",
    "is_released": true,
    "release_date": "2011-06-01",
    "overview": "In the 1960s, Charles Xavier and Erik Lehnsherr work together to find other mutants to stop the Hellfire Club."
  },
  {
    "id": "marvel-94",
    "universe": "mcu",
    "title": "The Wolverine",
    "media_type": "movie",
    "release_order": 95,
    "chronological_order": 46,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 76170,
    "poster_path": "https://image.tmdb.org/t/p/w500/t2wVAcoRlKvEIVSbiYDb8d0QqqS.jpg",
    "is_released": true,
    "release_date": "2013-07-21",
    "overview": "Wolverine faces his ultimate nemesis - and tests of his physical, emotional, and mortal limits - in modern-day Japan."
  },
  {
    "id": "marvel-95",
    "universe": "mcu",
    "title": "X-Men: Days of Future Past",
    "media_type": "movie",
    "release_order": 96,
    "chronological_order": 6,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 127585,
    "poster_path": "https://image.tmdb.org/t/p/w500/tYfijzolzgoMOtegh1Y7j2Enorg.jpg",
    "is_released": true,
    "release_date": "2014-05-15",
    "overview": "The X-Men send Wolverine to the past in a desperate effort to change history and prevent an event that results in doom."
  },
  {
    "id": "marvel-96",
    "universe": "mcu",
    "title": "Deadpool",
    "media_type": "movie",
    "release_order": 97,
    "chronological_order": 62,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 293660,
    "poster_path": "https://image.tmdb.org/t/p/w500/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
    "is_released": true,
    "release_date": "2016-02-09",
    "overview": "A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks."
  },
  {
    "id": "marvel-97",
    "universe": "mcu",
    "title": "X-Men: Apocalypse",
    "media_type": "movie",
    "release_order": 98,
    "chronological_order": 8,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 246655,
    "poster_path": "https://image.tmdb.org/t/p/w500/ikA8UhYdTGpqbatFa93nIf6noSr.jpg",
    "is_released": true,
    "release_date": "2016-05-18",
    "overview": "Since the dawn of civilization, he was worshipped as a god. Apocalypse, the first and most powerful mutant, awakens."
  },
  {
    "id": "marvel-98",
    "universe": "mcu",
    "title": "Logan",
    "media_type": "movie",
    "release_order": 99,
    "chronological_order": 154,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 263115,
    "poster_path": "https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
    "is_released": true,
    "release_date": "2017-02-28",
    "overview": "In the near future, a weary Logan cares for an ailing Professor X near the Mexican border until a young mutant arrives."
  },
  {
    "id": "marvel-99-s1",
    "universe": "mcu",
    "title": "Legion (Season 1)",
    "media_type": "show",
    "release_order": 100,
    "chronological_order": 74,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 67195,
    "poster_path": "https://image.tmdb.org/t/p/w500/au5hsZ20QzOVXSOWgx7umAhHC6A.jpg",
    "is_released": true,
    "release_date": "2017-02-08",
    "overview": "Troubled by unsettling visions, young David Haller begins piecing together his fragmented memories and realizes he may have special powers.",
    "seasons": 1,
    "episodes": 8
  },
  {
    "id": "marvel-100-s1",
    "universe": "mcu",
    "title": "The Gifted (Season 1)",
    "media_type": "show",
    "release_order": 101,
    "chronological_order": 75,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 69629,
    "poster_path": "https://image.tmdb.org/t/p/w500/nYkGYVzn4Df3V5fZS9xYyKZn551.jpg",
    "is_released": true,
    "release_date": "2017-10-02",
    "overview": "A suburban couple's ordinary lives are rocked by the sudden discovery that their children possess mutant powers. Forced to go on the run from a hostile government, the family joins up with an underground network of mutants and must fight to survive.",
    "seasons": 1,
    "episodes": 13
  },
  {
    "id": "marvel-99-s2",
    "universe": "mcu",
    "title": "Legion (Season 2)",
    "media_type": "show",
    "release_order": 102,
    "chronological_order": 82,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 67195,
    "poster_path": "https://image.tmdb.org/t/p/w500/wMPFWmM7VLu2AwBzpF3JiWTnTkt.jpg",
    "is_released": true,
    "release_date": "2018-04-03",
    "overview": "With David and Oliver missing and Farouk on the loose, the team forms an unlikely alliance with their former enemy Clark and his well-funded government is on a new path to attaining infinite and world-ending power.",
    "seasons": 2,
    "episodes": 11
  },
  {
    "id": "marvel-100-s2",
    "universe": "mcu",
    "title": "The Gifted (Season 2)",
    "media_type": "show",
    "release_order": 103,
    "chronological_order": 83,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 69629,
    "poster_path": "https://image.tmdb.org/t/p/w500/bUL8MBcB4OeVA2YkA3q1AMbpJL1.jpg",
    "is_released": true,
    "release_date": "2018-09-25",
    "overview": "A suburban couple's ordinary lives are rocked by the sudden discovery that their children possess mutant powers. Forced to go on the run from a hostile government, the family joins up with an underground network of mutants and must fight to survive.",
    "seasons": 2,
    "episodes": 16
  },
  {
    "id": "marvel-99-s3",
    "universe": "mcu",
    "title": "Legion (Season 3)",
    "media_type": "show",
    "release_order": 104,
    "chronological_order": 94,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 67195,
    "poster_path": "https://image.tmdb.org/t/p/w500/4THIqrWWYdsxy6zkfzzYvWnXR6Z.jpg",
    "is_released": true,
    "release_date": "2019-06-24",
    "overview": "As Farouk and Syd embark on a search, David gains a following, teams up with a time traveler named Switch and prepares to wage war.",
    "seasons": 3,
    "episodes": 8
  },
  {
    "id": "marvel-101",
    "universe": "mcu",
    "title": "Deadpool 2",
    "media_type": "movie",
    "release_order": 105,
    "chronological_order": 89,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 383498,
    "poster_path": "https://image.tmdb.org/t/p/w500/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
    "is_released": true,
    "release_date": "2018-05-15",
    "overview": "Wisecracking mercenary Deadpool battles the time-traveling cybernetic soldier Cable to protect a mutant boy."
  },
  {
    "id": "marvel-102",
    "universe": "mcu",
    "title": "Dark Phoenix",
    "media_type": "movie",
    "release_order": 106,
    "chronological_order": 9,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 320288,
    "poster_path": "https://image.tmdb.org/t/p/w500/cCTJPelKGLhALq3r51A9uMonxKj.jpg",
    "is_released": true,
    "release_date": "2019-06-05",
    "overview": "During a rescue mission in space, Jean Grey is hit by a cosmic force that transforms her into the Dark Phoenix."
  },
  {
    "id": "marvel-103",
    "universe": "mcu",
    "title": "The New Mutants",
    "media_type": "movie",
    "release_order": 107,
    "chronological_order": 99,
    "phase_or_chapter": "Fox X-Men Universe",
    "trakt_id": null,
    "tmdb_id": 340102,
    "poster_path": "https://image.tmdb.org/t/p/w500/xiDGcXJTvu1lazFRYip6g1eLt9c.jpg",
    "is_released": true,
    "release_date": "2020-04-02",
    "overview": "Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape."
  },
  {
    "id": "marvel-104",
    "universe": "mcu",
    "title": "Daredevil",
    "media_type": "movie",
    "release_order": 108,
    "chronological_order": 16,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 9480,
    "poster_path": "https://image.tmdb.org/t/p/w500/oCDBwSkntYamuw8VJIxMRCtDBmi.jpg",
    "is_released": true,
    "release_date": "2003-02-14",
    "overview": "A man blinded by toxic waste which also enhanced his other senses becomes a crime-fighting hero."
  },
  {
    "id": "marvel-105",
    "universe": "mcu",
    "title": "Elektra",
    "media_type": "movie",
    "release_order": 109,
    "chronological_order": 23,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 9947,
    "poster_path": "https://image.tmdb.org/t/p/w500/gC6s6NKHneSrOKyQZnUMb443RKU.jpg",
    "is_released": true,
    "release_date": "2006-06-16",
    "overview": "Elektra the warrior survives her near-death experience, becomes an assassin-for-hire, and tries to protect a father and daughter."
  },
  {
    "id": "marvel-106",
    "universe": "mcu",
    "title": "Fantastic Four",
    "media_type": "movie",
    "release_order": 110,
    "chronological_order": 24,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 9738,
    "poster_path": "https://image.tmdb.org/t/p/w500/4YMcYEFS8sFuW3soP1HVmgR3cSm.jpg",
    "is_released": true,
    "release_date": "2005-06-29",
    "overview": "Four scientists gain extraordinary superhuman powers after being exposed to cosmic radiation."
  },
  {
    "id": "marvel-107",
    "universe": "mcu",
    "title": "Fantastic Four: Rise of the Silver Surfer",
    "media_type": "movie",
    "release_order": 111,
    "chronological_order": 30,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 1979,
    "poster_path": "https://image.tmdb.org/t/p/w500/9wRfzTcMyyzkQxVDqBHv8RwuZOv.jpg",
    "is_released": true,
    "release_date": "2007-06-13",
    "overview": "The Fantastic Four encounter the mysterious Silver Surfer and face the cosmic planet-devouring threat of Galactus."
  },
  {
    "id": "marvel-108",
    "universe": "mcu",
    "title": "Fantastic Four (Fant4stic)",
    "media_type": "movie",
    "release_order": 112,
    "chronological_order": 57,
    "phase_or_chapter": "Fox Fantastic Four & Daredevil",
    "trakt_id": null,
    "tmdb_id": 166424,
    "poster_path": "https://image.tmdb.org/t/p/w500/cDroz5qSlP8xZ6tOpeYoPkBvKyL.jpg",
    "is_released": true,
    "release_date": "2015-08-05",
    "overview": "Four young outsiders teleport to an alternate and dangerous universe which alters their physical form in shocking ways."
  },
  {
    "id": "marvel-tv-109",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 1)",
    "media_type": "show",
    "release_order": 113,
    "chronological_order": 44,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/1CaKyPcZvzzMSwbNFJObxNsxTkK.jpg",
    "is_released": true,
    "release_date": "2013-09-24",
    "overview": "Season one begins where the “Marvel's The Avengers” left off. It's just after the battle of New York, and now that the existence of superheroes and aliens has become public knowledge, the world is trying to come to grips with this new reality. Agent Phil Coulson is back in action and now has his eye on a mysterious group called The Rising Tide. In order to track this unseen, unknown enemy, he has assembled a small, highly select group of Agents from the worldwide law-enforcement organization known as S.H.I.E.L.D.",
    "seasons": 1,
    "episodes": 22
  },
  {
    "id": "marvel-tv-110",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 2)",
    "media_type": "show",
    "release_order": 114,
    "chronological_order": 54,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/p8Qy60OIf0OaJ29KPw6ld51MSP7.jpg",
    "is_released": true,
    "release_date": "2014-09-23",
    "overview": "In the second season, Coulson and his team look to restore trust from the government and public following S.H.I.E.L.D.'s collapse.",
    "seasons": 2,
    "episodes": 22
  },
  {
    "id": "marvel-tv-111",
    "universe": "mcu",
    "title": "Agent Carter (Season 1)",
    "media_type": "show",
    "release_order": 115,
    "chronological_order": 2,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61550,
    "poster_path": "https://image.tmdb.org/t/p/w500/gqyjmfFOrKY8iouNTXWj9KW7cC5.jpg",
    "is_released": true,
    "release_date": "2015-01-06",
    "overview": "Years before Agent Phil Coulson and his S.H.I.E.L.D. team swore to protect those who cannot protect themselves from threats they cannot conceive, there was Agent Peggy Carter, who pledged the same oath but lived in a different time, when women weren't recognized as being as smart or as tough as their male counterparts. But no one should ever underestimate Peggy.",
    "seasons": 1,
    "episodes": 8
  },
  {
    "id": "marvel-tv-112",
    "universe": "mcu",
    "title": "Daredevil (Season 1)",
    "media_type": "show",
    "release_order": 116,
    "chronological_order": 53,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61889,
    "poster_path": "https://image.tmdb.org/t/p/w500/zFmJQzl6bFrdpHhDkxXmboyykqD.jpg",
    "is_released": true,
    "release_date": "2015-04-10",
    "overview": "Blinded as a young boy, Matt Murdock fights injustice by day as a lawyer and by night as the superhero Daredevil in Hell's Kitchen, New York City.",
    "seasons": 1,
    "episodes": 13
  },
  {
    "id": "marvel-tv-113",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 3)",
    "media_type": "show",
    "release_order": 117,
    "chronological_order": 61,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/y0cxxcvCk9lEG4DEorTz5GxC9sj.jpg",
    "is_released": true,
    "release_date": "2015-09-29",
    "overview": "Many months after their war with a rogue group of Inhumans, the team is still reeling. Coulson is again trying to put the pieces of his once revered organization back together while also dealing with the loss of his hand. His confidante and second in command, Agent Melinda May, has yet to return from an impromptu vacation with ex-husband Andrew; deadly superspy Agent Bobbi Morse is recovering from her traumatic torture at the hands of Grant Ward; Fitz is obsessed with discovering the truth behind the mysterious disappearance of Simmons; and all are on high-alert for the next move from Ward and Hydra.",
    "seasons": 3,
    "episodes": 22
  },
  {
    "id": "marvel-tv-114",
    "universe": "mcu",
    "title": "Jessica Jones (Season 1)",
    "media_type": "show",
    "release_order": 118,
    "chronological_order": 58,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 38472,
    "poster_path": "https://image.tmdb.org/t/p/w500/9wwfowgVJDouHQdUsIcNhgbIUlG.jpg",
    "is_released": true,
    "release_date": "2015-11-20",
    "overview": "Haunted by a traumatic past, Jessica Jones uses her gifts as a private eye to find her tormentor before he can harm anyone else in Hell's Kitchen.",
    "seasons": 1,
    "episodes": 13
  },
  {
    "id": "marvel-tv-115",
    "universe": "mcu",
    "title": "Agent Carter (Season 2)",
    "media_type": "show",
    "release_order": 119,
    "chronological_order": 3,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61550,
    "poster_path": "https://image.tmdb.org/t/p/w500/h3yPRRiWZk6HrFD2oo3xqpLt6bc.jpg",
    "is_released": true,
    "release_date": "2016-01-19",
    "overview": "Dedicated to the fight against new Atomic Age threats in the wake of World War II, Peggy must now journey from New York City to Los Angeles and she's about to find out that the bright lights of the post-war Hollywood mask a more sinister threat to everyone she is sworn to protect.",
    "seasons": 2,
    "episodes": 10
  },
  {
    "id": "marvel-tv-116",
    "universe": "mcu",
    "title": "Daredevil (Season 2)",
    "media_type": "show",
    "release_order": 120,
    "chronological_order": 59,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61889,
    "poster_path": "https://image.tmdb.org/t/p/w500/opHoslNCxkgoCaGhfO66fvCSH83.jpg",
    "is_released": true,
    "release_date": "2016-03-18",
    "overview": "Dark forces are tearing Hell's Kitchen apart once again, but this time Daredevil may have to choose between the city and his friends.",
    "seasons": 2,
    "episodes": 13
  },
  {
    "id": "marvel-tv-117",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 4)",
    "media_type": "show",
    "release_order": 121,
    "chronological_order": 71,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/mgyMzTTIFVdKoejD0gKIyaCgWOP.jpg",
    "is_released": true,
    "release_date": "2016-09-20",
    "overview": "Vengeance runs rampant this season as Coulson is a mere agent again, and Daisy has gone rogue after being under Hive's control. How will S.H.I.E.L.D. deal with the arrival of The Ghost Rider?",
    "seasons": 4,
    "episodes": 22
  },
  {
    "id": "marvel-tv-118",
    "universe": "mcu",
    "title": "Luke Cage (Season 1)",
    "media_type": "show",
    "release_order": 122,
    "chronological_order": 60,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 62126,
    "poster_path": "https://image.tmdb.org/t/p/w500/yzM1hMB3PUJqbISX0f421b3xOjB.jpg",
    "is_released": true,
    "release_date": "2016-07-21",
    "overview": "A bittersweet portrait into the mind of a dry-witted, sexual, angry, porn-watching, grief-riddled woman, trying to make sense of the world. As she hurls herself headlong at modern living, Fleabag is thrown roughly up against the walls of contemporary London, with all its frenetic energy, late nights, and bright lights, in this very modern mix of fatalism and hedonism, sustaining a merry-go-round of broken dreamers. By turns hilarious and heartbreaking, this is the thoroughly disarming confessional of a woman so totally detached, she’s utterly lost, and ultimately wondering what the hell she ought to be doing in life. Much like the rest of us."
  },
  {
    "id": "marvel-tv-119",
    "universe": "mcu",
    "title": "Iron Fist (Season 1)",
    "media_type": "show",
    "release_order": 123,
    "chronological_order": 67,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 62127,
    "poster_path": "https://image.tmdb.org/t/p/w500/usGfoL4RfX15f1sQcX3Sgw4YRf4.jpg",
    "is_released": true,
    "release_date": "2017-03-17",
    "overview": "Fifteen years after being presumed dead in a plane crash, Danny Rand mysteriously returns to New York City determined to reclaim his birthright and family company. However, when a long-destined enemy rises in New York, this living weapon is forced to choose between his family’s legacy and his duties as the Iron Fist.",
    "seasons": 1,
    "episodes": 13
  },
  {
    "id": "marvel-tv-120",
    "universe": "mcu",
    "title": "The Defenders (Limited Series)",
    "media_type": "show",
    "release_order": 124,
    "chronological_order": 68,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 62285,
    "poster_path": "https://image.tmdb.org/t/p/w500/4COAMPA6LPkPBd1xdm9paN4LCD8.jpg",
    "is_released": true,
    "release_date": "2017-08-18",
    "overview": "Daredevil, Jessica Jones, Luke Cage, and Iron Fist unite to protect NYC from The Hand.",
    "seasons": 1,
    "episodes": 8
  },
  {
    "id": "marvel-tv-121",
    "universe": "mcu",
    "title": "Inhumans (Season 1)",
    "media_type": "show",
    "release_order": 125,
    "chronological_order": 72,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 68716,
    "poster_path": "https://image.tmdb.org/t/p/w500/doCIoaV9ffAJbK3TW2AsGp4ytOQ.jpg",
    "is_released": true,
    "release_date": "2017-09-29",
    "overview": "After the Royal Family of Inhumans is splintered by a military coup, they barely escape to Hawaii where their surprising interactions with the lush world and humanity around them may prove to not only save them, but Earth itself.",
    "seasons": 1,
    "episodes": 8
  },
  {
    "id": "marvel-tv-122",
    "universe": "mcu",
    "title": "The Punisher (Season 1)",
    "media_type": "show",
    "release_order": 126,
    "chronological_order": 70,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67178,
    "poster_path": "https://image.tmdb.org/t/p/w500/dOkJ6TJKQjsz2XwXyp2VYpkeE5g.jpg",
    "is_released": true,
    "release_date": "2017-11-17",
    "overview": "A former Marine out to punish the criminals responsible for his family's murder finds himself ensnared in a military conspiracy.",
    "seasons": 1,
    "episodes": 13
  },
  {
    "id": "marvel-tv-123",
    "universe": "mcu",
    "title": "Runaways (Season 1)",
    "media_type": "show",
    "release_order": 127,
    "chronological_order": 76,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67466,
    "poster_path": "https://image.tmdb.org/t/p/w500/hMsaGkDyCM3Y3EWcdYK5Uu8qEok.jpg",
    "is_released": true,
    "release_date": "2017-11-21",
    "overview": "Every teenager thinks their parents are evil. What if you found out they actually were? Six diverse teenagers who can barely stand each other must unite against a common foe – their parents.",
    "seasons": 1,
    "episodes": 10
  },
  {
    "id": "marvel-tv-124",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 5)",
    "media_type": "show",
    "release_order": 128,
    "chronological_order": 88,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/zndNDiqH0SvIlFHURYCWY060qE8.jpg",
    "is_released": true,
    "release_date": "2017-12-01",
    "overview": "Agent Coulson and the team escaped LMD Aida’s Framework and awakened in the real world. Little did they know that Aida was now fully human – and with multiple Inhuman abilities – with the dangerous notion that, with Fitz by her side, she could change the world. After defeating her with the aid of Ghost Rider, the team went out for a celebration but were interrupted by a mysterious man who rendered them frozen. The next thing we see is Coulson onboard a ship … in space. Coulson will discover that some, but not all, of his S.H.I.E.L.D. colleagues were taken with him and placed onboard the ship. As they come in contact with some of the vessel’s inhabitants, it becomes abundantly clear that something has gone terribly awry, and the team will need to figure out their role and delve deeper into this nightmarish mystery to try to right what has gone incredibly wrong.",
    "seasons": 5,
    "episodes": 22
  },
  {
    "id": "marvel-tv-125",
    "universe": "mcu",
    "title": "Jessica Jones (Season 2)",
    "media_type": "show",
    "release_order": 129,
    "chronological_order": 77,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 38472,
    "poster_path": "https://image.tmdb.org/t/p/w500/tKirVNmDmwYjqehjPpyjr1n3U2F.jpg",
    "is_released": true,
    "release_date": "2018-03-08",
    "overview": "Drowning in anger, Jessica Jones is forced to reckon with her past, her powers and her newfound fame as she dishes out her own messy form of justice. Finally ready to face her past, Jessica hunts down the source of her powers and uncovers a link to a shadowy killer who's terrorizing the city.",
    "seasons": 2,
    "episodes": 13
  },
  {
    "id": "marvel-tv-126",
    "universe": "mcu",
    "title": "Cloak & Dagger (Season 1)",
    "media_type": "show",
    "release_order": 130,
    "chronological_order": 79,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 66190,
    "poster_path": "https://image.tmdb.org/t/p/w500/nluzawv8wEo0AeECpnLo3wO2YLZ.jpg",
    "is_released": true,
    "release_date": "2018-06-07",
    "overview": "Two teenagers from very different backgrounds awaken to newly acquired superpowers which mysteriously link them to one another.",
    "seasons": 1,
    "episodes": 10
  },
  {
    "id": "marvel-tv-127",
    "universe": "mcu",
    "title": "Luke Cage (Season 2)",
    "media_type": "show",
    "release_order": 131,
    "chronological_order": 78,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 62126,
    "poster_path": "https://image.tmdb.org/t/p/w500/6R62oGGufhsf6DiMknCi047N0b7.jpg",
    "is_released": true,
    "release_date": "2019-03-04",
    "overview": "Picking up one year after the end of the first series, while Fleabag appears to be more at ease with herself and her newly bustling café, her family seems to be whirling into further turmoil around her. Having not spoken to her sister since we last left her, Fleabag reconnects with Claire at their father’s engagement party, which turns out to be far from a celebration. There, she meets a Catholic priest who turns her life upside down… Series 2 is an exploration into everything that makes us human: love, religion, hope and heartbreak."
  },
  {
    "id": "marvel-tv-128",
    "universe": "mcu",
    "title": "Iron Fist (Season 2)",
    "media_type": "show",
    "release_order": 132,
    "chronological_order": 80,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 62127,
    "poster_path": "https://image.tmdb.org/t/p/w500/vXYvfCWvz5W0rErCpNIq09urhzW.jpg",
    "is_released": true,
    "release_date": "2018-09-07",
    "overview": "As a gang war brews in New York's Chinatown, Danny and Colleen strive to protect the innocent while battling fearsome enemies both old and new.",
    "seasons": 2,
    "episodes": 10
  },
  {
    "id": "marvel-tv-129",
    "universe": "mcu",
    "title": "Daredevil (Season 3)",
    "media_type": "show",
    "release_order": 133,
    "chronological_order": 81,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 61889,
    "poster_path": "https://image.tmdb.org/t/p/w500/zH6sgePlr1XX0jSZypbfQmr70Lf.jpg",
    "is_released": true,
    "release_date": "2018-10-19",
    "overview": "Missing for months, Matt Murdock reemerges a broken man, putting into question his future as both vigilante Daredevil and lawyer Matthew Murdock. But when his archenemy Wilson Fisk is released from prison, Matt must choose between hiding from the world, or embracing his destiny as a hero.",
    "seasons": 3,
    "episodes": 13
  },
  {
    "id": "marvel-tv-130",
    "universe": "mcu",
    "title": "Runaways (Season 2)",
    "media_type": "show",
    "release_order": 134,
    "chronological_order": 84,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67466,
    "poster_path": "https://image.tmdb.org/t/p/w500/r2e50wFzTsMgsSVLAyIB8uX1EGu.jpg",
    "is_released": true,
    "release_date": "2018-12-21",
    "overview": "The Runaways have left their homes (and evil parents) behind and now have to learn to live on their own. As they scavenge for food, search for shelter, and take care of one another, our kids begin to realize that, for better or worse, they’re stuck with each other. And it’s up to them to take down PRIDE once and for all. But someone sent a mysterious message to Jonah… Is there a mole in the Runaways? Meanwhile PRIDE is focused on finding their children, and Jonah has his own dangerous plan in mind.",
    "seasons": 2,
    "episodes": 13
  },
  {
    "id": "marvel-tv-131",
    "universe": "mcu",
    "title": "The Punisher (Season 2)",
    "media_type": "show",
    "release_order": 135,
    "chronological_order": 85,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67178,
    "poster_path": "https://image.tmdb.org/t/p/w500/agNYq5XZnGfmYetUMyyM2RdPY70.jpg",
    "is_released": true,
    "release_date": "2019-01-18",
    "overview": "Frank strives to protect a teenager caught in a sinister conspiracy while doing whatever it takes -- and then some -- to end Russo once and for all.",
    "seasons": 2,
    "episodes": 13
  },
  {
    "id": "marvel-tv-132",
    "universe": "mcu",
    "title": "Cloak & Dagger (Season 2)",
    "media_type": "show",
    "release_order": 136,
    "chronological_order": 86,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 66190,
    "poster_path": "https://image.tmdb.org/t/p/w500/pYnRJuBPEqZO1o4fcxBTgmKNHfy.jpg",
    "is_released": true,
    "release_date": "2019-04-04",
    "overview": "Season two turns the heat up on our young heroes as Tyrone and Tandy try to find their place as more active heroes in this world. As they learn and grow emotionally, so will their skills. With enhanced powers and a decision to make about the type of heroes they want to be, they make the choice to run into the danger, head first. They tackle a heartless vigilante and uncover an evil that’s been preying on the young women of the city, as the show takes on more serious topics like gang violence and human trafficking.",
    "seasons": 2,
    "episodes": 10
  },
  {
    "id": "marvel-tv-133",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 6)",
    "media_type": "show",
    "release_order": 137,
    "chronological_order": 95,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/QU0NjcvDonZLKhjRuxRv6AVo5l.jpg",
    "is_released": true,
    "release_date": "2019-05-10",
    "overview": "Last season, the team leaped forward in time to a dystopian future they soon realized must be prevented. While facing multiple timelines and new enemies from faraway planets, they found family, friends, teammates and the courage to pull off their biggest challenge yet. Their next challenge? Coming to grips with the knowledge that bending the laws of space and time may have saved the planet, but it couldn’t save Fitz or Coulson.",
    "seasons": 6,
    "episodes": 13
  },
  {
    "id": "marvel-tv-134",
    "universe": "mcu",
    "title": "Jessica Jones (Season 3)",
    "media_type": "show",
    "release_order": 138,
    "chronological_order": 87,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 38472,
    "poster_path": "https://image.tmdb.org/t/p/w500/dOPx3bj3x6eXYXQJUUIHXvWRSSB.jpg",
    "is_released": true,
    "release_date": "2019-06-14",
    "overview": "Jessica matches wits with a calculating serial killer, and a newly powered Trish goes to extremes to stamp out evil.",
    "seasons": 3,
    "episodes": 13
  },
  {
    "id": "marvel-tv-135",
    "universe": "mcu",
    "title": "Runaways (Season 3)",
    "media_type": "show",
    "release_order": 139,
    "chronological_order": 96,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 67466,
    "poster_path": "https://image.tmdb.org/t/p/w500/m83skvEvoFQoo1szIMpFQ6kbCe6.jpg",
    "is_released": true,
    "release_date": "2019-12-13",
    "overview": "The Runaways frantically search for their captured friends Chase, Gert and Karolina. The kids go head to head with an unstoppable enemy who has targeted Leslie - or more accurately, the child she's carrying. Nico draws them all into a dark realm where its ruler Morgan le Fay, is much more nefarious than anyone the kids have yet to face.",
    "seasons": 3,
    "episodes": 10
  },
  {
    "id": "marvel-tv-136",
    "universe": "mcu",
    "title": "Agents of S.H.I.E.L.D. (Season 7)",
    "media_type": "show",
    "release_order": 140,
    "chronological_order": 97,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 1403,
    "poster_path": "https://image.tmdb.org/t/p/w500/qM95u55G8xVyfgoSZ2qTlY3MDl6.jpg",
    "is_released": true,
    "release_date": "2020-05-27",
    "overview": "Coulson and the Agents of S.H.I.E.L.D. are thrust backward in time and stranded in 1931 New York City. With the all-new Zephyr set to time-jump at any moment, the team must hurry to find out exactly what happened. If they fail, it would mean disaster for the past, present and future of the world.",
    "seasons": 7,
    "episodes": 13
  },
  {
    "id": "marvel-tv-137",
    "universe": "mcu",
    "title": "Helstrom (Season 1)",
    "media_type": "show",
    "release_order": 141,
    "chronological_order": 98,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 88987,
    "poster_path": "https://image.tmdb.org/t/p/w500/5QmcKsepYpO9XYsWNLwsiULoaAu.jpg",
    "is_released": true,
    "release_date": "2019-10-08",
    "overview": "A caveman forms a bond with a dinosaur as they struggle to survive in a hostile world."
  },
  {
    "id": "marvel-tv-138",
    "universe": "mcu",
    "title": "M.O.D.O.K. (Season 1)",
    "media_type": "show",
    "release_order": 142,
    "chronological_order": 133,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 111312,
    "poster_path": "https://image.tmdb.org/t/p/w500/2kXRzRjQZs9kAIm3K9MkQgsZR9C.jpg",
    "is_released": true,
    "release_date": "2019-03-15",
    "overview": "Terrifying creatures, wicked surprises and dark comedy converge in this NSFW anthology of animated stories presented by Tim Miller and David Fincher."
  },
  {
    "id": "marvel-tv-139",
    "universe": "mcu",
    "title": "Hit-Monkey (Season 1)",
    "media_type": "show",
    "release_order": 143,
    "chronological_order": 134,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 133903,
    "poster_path": "https://image.tmdb.org/t/p/w500/1aK7hApRSDUv8xxDQXyQil7qBjN.jpg",
    "is_released": true,
    "release_date": "2021-07-01",
    "overview": "After a video of Prince Wilhelm of Sweden fighting at a party is posted online, he is given a script for an apology speech and learns that his parents have enrolled him at Hillerska Boarding School, a prestigious boarding school in the country."
  },
  {
    "id": "marvel-tv-140",
    "universe": "mcu",
    "title": "Hit-Monkey (Season 2)",
    "media_type": "show",
    "release_order": 144,
    "chronological_order": 135,
    "phase_or_chapter": "Marvel Television & Defenders Saga",
    "trakt_id": null,
    "tmdb_id": 133903,
    "poster_path": "https://image.tmdb.org/t/p/w500/slf1cSDiFBeMp8gKUqxjwyWtd1p.jpg",
    "is_released": true,
    "release_date": "2022-11-01",
    "overview": "A winter break has passed and Prince Wilhelm and the rest of his classmates are back at Hillerska. When Wilhelm tries to take revenge on August, and win back Simon's trust, he creates problems that threaten the entire monarchy."
  },
  {
    "id": "marvel-141",
    "universe": "mcu",
    "title": "Blade",
    "media_type": "movie",
    "release_order": 145,
    "chronological_order": 12,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 36647,
    "poster_path": "https://image.tmdb.org/t/p/w500/oWT70TvbsmQaqyphCZpsnQR7R32.jpg",
    "is_released": true,
    "release_date": "1998-08-21",
    "overview": "A half-vampire, half-mortal man-turned-protector of the human race battles evil vampires."
  },
  {
    "id": "marvel-142",
    "universe": "mcu",
    "title": "Blade II",
    "media_type": "movie",
    "release_order": 146,
    "chronological_order": 14,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 36586,
    "poster_path": "https://image.tmdb.org/t/p/w500/yDHwo3eWcMiy5LnnEnlGV9iLu9k.jpg",
    "is_released": true,
    "release_date": "2002-03-22",
    "overview": "Blade forms an uneasy alliance with the vampire council to combat the Reapers."
  },
  {
    "id": "marvel-143",
    "universe": "mcu",
    "title": "Hulk (2003)",
    "media_type": "movie",
    "release_order": 147,
    "chronological_order": 18,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 1927,
    "poster_path": "https://image.tmdb.org/t/p/w500/UllIft2jLSBaay3zQyMV4GNdfy.jpg",
    "is_released": true,
    "release_date": "2003-06-19",
    "overview": "Bruce Banner, a genetics researcher with a tragic past, suffers an accident that causes him to transform into a raging green monster."
  },
  {
    "id": "marvel-144",
    "universe": "mcu",
    "title": "The Punisher (2004)",
    "media_type": "movie",
    "release_order": 148,
    "chronological_order": 20,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 7220,
    "poster_path": "https://image.tmdb.org/t/p/w500/7rmA1HwYp2GKM85BL0cVwCaosGr.jpg",
    "is_released": true,
    "release_date": "2004-04-15",
    "overview": "An undercover FBI agent becomes a vengeful vigilante after his wife and son are murdered by a ruthless criminal."
  },
  {
    "id": "marvel-145",
    "universe": "mcu",
    "title": "Blade: Trinity",
    "media_type": "movie",
    "release_order": 149,
    "chronological_order": 22,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 36588,
    "poster_path": "https://image.tmdb.org/t/p/w500/eMH0bxn3GCpqn5igOhBZMkAsLQP.jpg",
    "is_released": true,
    "release_date": "2009-01-17",
    "overview": "Blade joins forces with the Nightstalkers to take down Dracula himself."
  },
  {
    "id": "marvel-146",
    "universe": "mcu",
    "title": "Man-Thing",
    "media_type": "special",
    "release_order": 150,
    "chronological_order": 25,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 24254,
    "poster_path": "https://image.tmdb.org/t/p/w500/3i6wviquq8F8hTVAGdMOXBwmtGX.jpg",
    "is_released": true,
    "release_date": "1989-08-16",
    "overview": "Agents of an oil tycoon disappear in a swamp; the new sheriff investigates and finds a swamp creature."
  },
  {
    "id": "marvel-147",
    "universe": "mcu",
    "title": "Blade: The Series",
    "media_type": "show",
    "release_order": 151,
    "chronological_order": 27,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 2424,
    "poster_path": "https://image.tmdb.org/t/p/w500/mAbYL7lSKMBLANXgqVp8PAbpxRN.jpg",
    "is_released": true,
    "release_date": "2006-01-02",
    "overview": "Blade continues his war against the vampires in Detroit with the help of Krista Starr.",
    "seasons": 2,
    "episodes": 104
  },
  {
    "id": "marvel-148",
    "universe": "mcu",
    "title": "Ghost Rider",
    "media_type": "movie",
    "release_order": 152,
    "chronological_order": 28,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 1250,
    "poster_path": "https://image.tmdb.org/t/p/w500/4quwR1VwZouD0YF9AaD72kQAjxH.jpg",
    "is_released": true,
    "release_date": "2007-01-15",
    "overview": "Stunt motorcyclist Johnny Blaze gives up his soul to become a hell-blazing vigilante."
  },
  {
    "id": "marvel-149",
    "universe": "mcu",
    "title": "Punisher: War Zone",
    "media_type": "movie",
    "release_order": 153,
    "chronological_order": 31,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 13056,
    "poster_path": "https://image.tmdb.org/t/p/w500/oOvKJgYUIpfswGHAdW6159bPbvM.jpg",
    "is_released": true,
    "release_date": "2008-12-05",
    "overview": "Frank Castle wages a one-man war on the mob and battles disfigured mob boss Jigsaw."
  },
  {
    "id": "marvel-150",
    "universe": "mcu",
    "title": "Ghost Rider: Spirit of Vengeance",
    "media_type": "movie",
    "release_order": 154,
    "chronological_order": 32,
    "phase_or_chapter": "Marvel Legacy Standalone",
    "trakt_id": null,
    "tmdb_id": 71676,
    "poster_path": "https://image.tmdb.org/t/p/w500/xEoBT6lYfQNpSpTm8gJMTrQytiw.jpg",
    "is_released": true,
    "release_date": "2011-12-10",
    "overview": "Johnny Blaze is hiding out in Eastern Europe when he is called upon to stop the devil from taking over his son."
  }
];
